import {describe,it,expect,afterEach} from 'vitest';
import {inspectBackup,backupReminder,personalWork} from '../../src/backup/inspection';
import {normaliseComfortBackup,normaliseComfortPreferences} from '../../src/features/comfort/preferences';
import {readingPositionKey,normalisePosition} from '../../src/features/comfort/reading-position';
import {deviceChecks,emptyDeviceReport,recordDeviceCheck,normaliseDeviceReport} from '../../src/features/comfort/device-report';
import {inspectOfflineCache} from '../../src/features/comfort/offline';
import {StudyDatabase} from '../../src/storage/database';
import {StudyRepository,defaultSettings} from '../../src/storage/repository';
import {exportBackup,restoreBackup} from '../../src/backup/restore';
import {validateBackup} from '../../src/backup/validate';
import Dexie from 'dexie';
import {pack} from '../fixtures';
const databases:StudyDatabase[]=[];
function repo(){const db=new StudyDatabase('comfort-'+crypto.randomUUID());databases.push(db);return new StudyRepository(db)}
afterEach(async()=>{for(const db of databases.splice(0))await db.delete()});
describe('backup inspection',()=>{
 it('previews all portable counts and distinguishes archived approval from restore authority',async()=>{const r=repo();await r.installPack(pack(),[]);await r.saveSettings(defaultSettings);const b=JSON.parse(await exportBackup(await r.getSnapshot()).text());expect(inspectBackup(b)).toMatchObject({schemaVersion:1,questions:1,packs:1,sessions:0,attempts:0,workspace:0});expect(inspectBackup(b).warnings.join(' ')).toMatch(/review/i)});
 it('reminds after the chosen interval and never claims a completed save',()=>{const now=new Date('2026-10-08T00:00:00Z');expect(backupReminder(null,7,now)).toBe('No backup export recorded.');expect(backupReminder('2026-10-01T00:00:00Z',7,now)).toMatch(/due/i);expect(backupReminder('2026-10-07T00:00:00Z',7,now)).toBeNull();expect(backupReminder('bad',7,now)).toMatch(/No backup/)});
 it('restores old schema-1 backups with no workspace and quarantines installed content',async()=>{const source=repo(),target=repo();await source.installPack(pack(),[]);await source.saveSettings({...defaultSettings,theme:'dark'});const b=JSON.parse(await exportBackup(await source.getSnapshot()).text());delete b.workspace;expect(validateBackup(b,1000).valid).toBe(true);await restoreBackup(target,b,{replaceConfirmed:true,recoveryBackup:exportBackup(await target.getSnapshot())});const after=await target.getSnapshot();expect(after.settings[0].theme).toBe('dark');expect(after.workspace).toEqual([]);expect(after.packs[0].questions[0].status).toBe('draft')});
 it('upgrades an actual v1 IndexedDB database without losing settings',async()=>{const name='comfort-upgrade-'+crypto.randomUUID(),old=new Dexie(name);old.version(1).stores({settings:'id',packs:'id',sourceChecks:'referenceId',contentTrust:'[questionId+revision],questionId',sessions:'id,status',attempts:'id,sessionId,questionId',reviews:'questionId,dueAt',bookmarks:'questionId',notes:'questionId',releasedHoldouts:'questionId'});await old.table('settings').put({...defaultSettings,theme:'dark'});old.close();const db=new StudyDatabase(name);databases.push(db);const r=new StudyRepository(db);expect((await r.getSettings()).theme).toBe('dark');expect((await r.getSnapshot()).workspace).toEqual([])});
 it('normalizes valid and malformed comfort metadata without trusting object/array dates or unsupported intervals',()=>{expect(normaliseComfortBackup({lastExportAt:'2026-10-08T10:00:00Z',workFingerprint:'v1:abc'})).toEqual({lastExportAt:'2026-10-08T10:00:00Z',workFingerprint:'v1:abc'});for(const value of [{lastExportAt:{}},{lastExportAt:[]},{lastExportAt:'2026-02-30T10:00:00Z'},null])expect(normaliseComfortBackup(value).lastExportAt).toBeNull();expect(normaliseComfortPreferences({reminderDays:14}).reminderDays).toBe(14);for(const reminderDays of [[],{},-7,Infinity,2,'14'])expect(normaliseComfortPreferences({reminderDays}).reminderDays).toBe(7)});
 it('detects edited notes even when creation time is unchanged, while ignoring reminder metadata',async()=>{const r=repo();await r.installPack(pack(),[]);await r.saveNote('q1',1,'First annotation');const before=await r.getSnapshot(),baseline=personalWork(before);await r.saveNote('q1',1,'Edited annotation');const after=await r.getSnapshot();expect(after.notes[0].createdAt).toBe(before.notes[0].createdAt);expect(personalWork(after).fingerprint).not.toBe(baseline.fingerprint);await r.db.workspace.put({id:'comfort:backup',version:1,value:{lastExportAt:'2026-10-08T10:00:00Z'},updatedAt:'2026-10-08T10:00:00Z'});expect(personalWork(await r.getSnapshot()).fingerprint).toBe(personalWork(after).fingerprint)});
 it('detects an actual durable answer submitted after a captured backup, including draft personal history',async()=>{const r=repo(),p=pack();await r.installPack(p,[]);const {SessionService}=await import('../../src/sessions/service');let clock=new Date('2026-10-08T10:00:00Z');const service=new SessionService(r,()=>clock),session=await service.createSession({mode:'draft-preview',selectedQuestions:p.questions,durationMinutes:null,releasesReservedIds:[]}),captured=personalWork(await r.getSnapshot());clock=new Date('2026-10-08T11:00:00Z');await service.submitLearnAnswer(session.id,'q1',['a'],'confident',1000);const current=personalWork(await r.getSnapshot());expect(current.latestAt).toBe(clock.toISOString());expect(backupReminder('2026-10-08T10:00:00Z',7,clock,current,captured.fingerprint)).toMatch(/New work since last backup/)});
 it('reminds about an answer newer than a recent export and does not nag unchanged/empty work',async()=>{const r=repo(),snapshot=await r.getSnapshot(),now=new Date('2026-10-08T12:00:00Z'),last='2026-10-08T10:00:00Z';expect(backupReminder(last,7,now,{latestAt:'2026-10-08T11:00:00Z',fingerprint:'new',records:1},'old')).toMatch(/New work since last backup/);const work=personalWork(snapshot);expect(backupReminder('2026-09-01T00:00:00Z',7,now,work,work.fingerprint)).toBeNull()});
});
describe('reading positions',()=>{
 it('isolates two sessions and question IDs without separator collisions',()=>{expect(readingPositionKey('s:1','q')).not.toBe(readingPositionKey('s','1:q'));expect(readingPositionKey('s1','q')).not.toBe(readingPositionKey('s2','q'))});
 it('rejects corrupt positions and keeps finite nonnegative scroll offsets',()=>{expect(normalisePosition({scrollY:340})).toBe(340);expect(normalisePosition({scrollY:-20})).toBe(0);expect(normalisePosition({scrollY:Infinity})).toBe(0);expect(normalisePosition(null)).toBe(0)});
});
describe('physical device reports',()=>{
 it('starts with ten unperformed checks and no fabricated metadata',()=>{expect(deviceChecks).toHaveLength(10);expect(emptyDeviceReport()).toMatchObject({model:'',os:'',browser:'',testedOn:'',checks:{}})});
 it('records explicit failed and passed user assertions with dates and failure detail',()=>{let r=emptyDeviceReport();r=recordDeviceCheck(r,'offline','failed','2026-10-08T10:00:00Z','Home screen failed offline');expect(r.checks.offline).toEqual({status:'failed',recordedAt:'2026-10-08T10:00:00Z',notes:'Home screen failed offline',assertedBy:'user'});r=recordDeviceCheck(r,'offline','passed','2026-10-09T10:00:00Z','');expect(r.checks.offline.status).toBe('passed')});
 it('rejects unknown check IDs and invalid recording dates',()=>{expect(()=>recordDeviceCheck(emptyDeviceReport(),'unknown','passed','2026-10-08T10:00:00Z','')).toThrow();expect(()=>recordDeviceCheck(emptyDeviceReport(),'offline','passed','bad','')).toThrow()});
 it('rejects malformed imported device records without inventing acceptance',()=>{expect(normaliseDeviceReport({model:123,checks:{offline:null,accessibility:{status:'passed',recordedAt:'bad',assertedBy:'user'},install:{status:'passed',recordedAt:'2026-10-08T10:00:00Z',assertedBy:'user',notes:'Performed'},storage:{status:'passed',recordedAt:'2026-10-08T10:00:00Z',assertedBy:'automation'}}})).toEqual({...emptyDeviceReport(),checks:{install:{status:'passed',recordedAt:'2026-10-08T10:00:00Z',assertedBy:'user',notes:'Performed'}}})});
});
describe('offline cache audit',()=>{
 it('requires every shell, bank, study-data, app, validator, vendor, style, manifest and icon asset',()=>{const files=['index.html','assets/question-bank-a.js','assets/validators-a.js','assets/vendor-a.js','assets/study-data-a.js','assets/index-a.js','assets/index-a.css','manifest.webmanifest','icons/icon-192.png','icons/icon-512.png','icons/maskable-512.png','offline-assets.json'],urls=files.map(file=>'https://example.test/'+file);expect(inspectOfflineCache(urls,true,files)).toMatchObject({complete:true,missing:[]});const partial=inspectOfflineCache(urls.filter(url=>!url.includes('study-data')&&!url.includes('index-a.js')&&!url.includes('maskable')),true,files);expect(partial.complete).toBe(false);expect(partial.missing).toEqual(expect.arrayContaining(['study data','application code','maskable icon','assets/study-data-a.js','assets/index-a.js','icons/maskable-512.png']));expect(inspectOfflineCache(urls,false,files).complete).toBe(false)});
 it('does not claim completeness without the generated asset inventory and detects a missing extra chunk',()=>{const files=['index.html','assets/extra-lazy-a.js'];expect(inspectOfflineCache(['https://example.test/index.html'],true,files).missing).toContain('assets/extra-lazy-a.js');expect(inspectOfflineCache([],true).complete).toBe(false)});
 it('does not mistake remote paths or query strings for cached chunk names',()=>{expect(inspectOfflineCache(['https://example.test/foo?name=question-bank.js'],true).complete).toBe(false)});
});
