import type {DatabaseSnapshot} from '../../sessions/types';
import {classifyQuestion} from '../../content/trust';
export type PersistenceState='unsupported'|'granted'|'not-granted'|'error';
export interface StorageInspection {estimate:'unsupported'|'available'|'unavailable'|'error';usageBytes?:number;quotaBytes?:number;persistence:PersistenceState}
export type StorageAPI=Partial<Pick<StorageManager,'estimate'|'persist'|'persisted'>>;
export function browserCapabilities(scope: {indexedDB?:unknown;caches?:unknown;isSecureContext?:unknown;navigator?:{serviceWorker?:unknown;storage?:StorageAPI}}=globalThis){return {indexedDB:!!scope.indexedDB,cacheStorage:!!scope.caches,serviceWorker:!!scope.navigator?.serviceWorker,secureContext:scope.isSecureContext===true,storageEstimate:typeof scope.navigator?.storage?.estimate==='function',persistentStorage:typeof scope.navigator?.storage?.persist==='function'}}
function bytes(value:unknown):value is number{return typeof value==='number'&&Number.isFinite(value)&&value>=0}
export async function inspectStorage(storage?:StorageAPI):Promise<StorageInspection>{const result:StorageInspection={estimate:'unsupported',persistence:'unsupported'};if(storage?.estimate){try{const estimate=await storage.estimate();if(bytes(estimate.usage)&&bytes(estimate.quota)){result.estimate='available';result.usageBytes=estimate.usage;result.quotaBytes=estimate.quota}else result.estimate='unavailable'}catch{result.estimate='error'}}if(storage?.persisted){try{result.persistence=await storage.persisted()?'granted':'not-granted'}catch{result.persistence='error'}}return result}
export async function requestPersistence(storage?:StorageAPI):Promise<PersistenceState>{if(!storage?.persist)return 'unsupported';try{return await storage.persist()?'granted':'not-granted'}catch{return 'error'}}
export function createSupportReport(snapshot:DatabaseSnapshot,databaseSchemaVersion:number,capabilities:ReturnType<typeof browserCapabilities>,storage:StorageInspection){const trust={draft:0,eligible:0,retired:0,invalidated:0};const packs=(Array.isArray(snapshot.packs)?snapshot.packs:[]).map((pack,index)=>{const questions=Array.isArray(pack?.questions)?pack.questions:[];for(const question of questions){if(!question||typeof question!=='object')continue;const local=(Array.isArray(snapshot.contentTrust)?snapshot.contentTrust:[]).find(t=>t?.questionId===question.id&&t?.revision===question.revision);trust[classifyQuestion(question,local??null)]++}return {number:index+1,version:Number.isSafeInteger(pack?.version)&&pack.version>=1?pack.version:null,questionCount:questions.length}});return {reportSchemaVersion:1,databaseSchemaVersion,backupSchemaVersion:1,packs,trust,capabilities,storage:{estimate:storage.estimate,persistence:storage.persistence,...(bytes(storage.usageBytes)?{usageBytes:storage.usageBytes}:{}),...(bytes(storage.quotaBytes)?{quotaBytes:storage.quotaBytes}:{})}}}
