import {expect,it} from 'vitest';
import {blueprint,question,pack} from '../fixtures';
import {validatePack} from '../../src/content/validate';
const ordering=()=>question({type:'ordering',requiredSelections:3,correctOptionIds:['a','c','b'],subObjectiveIds:['rbac.1'],exhibits:[{type:'table',title:'Configuration',columns:['Name'],rows:[['Value']]}],caseStudy:{id:'case-one',title:'Case',overview:'Shared context'}});
const matching=()=>question({type:'matching',requiredSelections:3,correctOptionIds:['c','a','b'],matchPrompts:[{id:'p1',text:'First'},{id:'p2',text:'Second'},{id:'p3',text:'Third'}]});
it('accepts ordering, matching, exhibits and exact blueprint subskills',()=>{expect(validatePack(pack([ordering()]),blueprint).issues).toEqual([]);expect(validatePack(pack([matching()]),blueprint).issues).toEqual([])});
it('rejects missing or duplicate matching prompts and incomplete assignments',()=>{const q=matching();expect(validatePack(pack([{...q,matchPrompts:undefined}]),blueprint).pack).toBeNull();expect(validatePack(pack([{...q,matchPrompts:[q.matchPrompts![0],q.matchPrompts![0],q.matchPrompts![2]]}]),blueprint).pack).toBeNull();expect(validatePack(pack([{...q,requiredSelections:2,correctOptionIds:['a','b']}]),blueprint).pack).toBeNull()});
it('rejects unknown or foreign subskills, malformed tables and empty code exhibits',()=>{for(const subObjectiveIds of [['rbac.2'],['entra.1']])expect(validatePack(pack([{...ordering(),subObjectiveIds}]),blueprint).pack).toBeNull();expect(validatePack(pack([{...ordering(),exhibits:[{type:'table',title:'Bad',columns:['One'],rows:[['Two','Three']]}]}]),blueprint).pack).toBeNull();expect(validatePack(pack([{...ordering(),exhibits:[{type:'code',title:'Empty'}]}]),blueprint).pack).toBeNull()});
it('ordering requires every option once and old single-answer snapshots stay valid',()=>{expect(validatePack(pack([{...ordering(),requiredSelections:2,correctOptionIds:['a','b']}]),blueprint).pack).toBeNull();expect(validatePack(pack(),blueprint).issues).toEqual([])});
