import {readFileSync} from 'node:fs';
import {describe,it,expect} from 'vitest';
import {validatePack} from '../../src/content/validate';
import type {Blueprint,ContentPack} from '../../src/content/types';
const read=(path:string)=>JSON.parse(readFileSync(path,'utf8'));
describe('networking expansion evidence and diversity',()=>{
 it('validates fifty original drafts and covers every networking subskill',()=>{const p=read('content/packs/az104-networking-expanded-draft.json') as ContentPack;const b=read('content/blueprints/az104-2026-04-17.json') as Blueprint;expect(validatePack(p,b).issues).toEqual([]);expect(p.questions).toHaveLength(50);expect(new Set(p.questions.map(q=>q.scenario)).size).toBe(50);for(const q of p.questions){expect(q.status).toBe('draft');expect(q.review).toBeNull();expect(q.provenance).toBe('ai-assisted');expect(q.options.every(o=>o.referenceIds.length>0)).toBe(true);}for(const o of b.domains.find(d=>d.id==='networking')!.objectives)for(let i=1;i<=o.subObjectives.length;i++)expect(p.questions.some(q=>q.subObjectiveIds?.includes(`${o.id}.${i}`))).toBe(true);});
 it('supplies required formats, advanced work, reserves, exhibits and intact cases',()=>{const qs=(read('content/packs/az104-networking-expanded-draft.json') as ContentPack).questions;expect(qs.filter(q=>q.difficulty==='advanced').length).toBeGreaterThanOrEqual(10);expect(qs.filter(q=>q.type==='multiple').length).toBeGreaterThanOrEqual(10);for(const type of ['ordering','matching'])expect(qs.filter(q=>q.type===type).length).toBeGreaterThanOrEqual(2);expect(qs.filter(q=>q.assessmentReserved).length).toBeGreaterThanOrEqual(10);expect(qs.filter(q=>q.exhibits?.length).length).toBeGreaterThanOrEqual(8);const groups=new Map<string,number>();for(const q of qs)if(q.caseStudy)groups.set(q.caseStudy.id,(groups.get(q.caseStudy.id)??0)+1);expect(groups.size).toBeGreaterThanOrEqual(2);expect([...groups.values()].every(n=>n===3)).toBe(true);});
 it('links each reference to actual source checks and audits all ten legacy revisions',()=>{const qs=(read('content/packs/az104-networking-expanded-draft.json') as ContentPack).questions;const checks=read('content/sources/networking-expanded.json') as {referenceId:string;canonicalUrl:string;contentHash:string;result:string}[];for(const q of qs)for(const r of q.references){const check=checks.find(c=>c.referenceId===r.id);expect(check?.canonicalUrl).toBe(r.url);expect(check?.result).toBe('checked');expect(check?.contentHash).toMatch(/^[a-f0-9]{64}$/);}const audit=read('content/audits/networking-starter-audit.json');expect(audit.questions).toHaveLength(10);expect(audit.questions.every((q:{revision:number;subObjectiveIds:string[]})=>q.revision===1&&q.subObjectiveIds.length)).toBe(true);});
});
