import {readFileSync,existsSync} from 'node:fs';
import {describe,it,expect} from 'vitest';
import {validatePack} from '../../src/content/validate';
import type {Blueprint,ContentPack,SourceCheck} from '../../src/content/types';
const path='content/packs/az104-storage-expanded-draft.json';
const blueprint=JSON.parse(readFileSync('content/blueprints/az104-2026-04-17.json','utf8')) as Blueprint;
const read=()=>JSON.parse(readFileSync(path,'utf8')) as ContentPack;
describe('expanded storage bank',()=>{
 it('supplies fifty new storage scenarios',()=>{expect(existsSync(path)).toBe(true);const p=read();expect(p.id).toBe('az104-storage-expanded-draft');expect(p.questions).toHaveLength(50);expect(p.questions.map(q=>q.id)).toEqual(Array.from({length:50},(_,i)=>`az104-storage-plus-${String(i+1).padStart(2,'0')}`));expect(new Set(p.questions.map(q=>q.scenario+q.prompt)).size).toBe(50)});
 it('validates grounded unapproved content covering every storage subskill',()=>{const p=read();expect(validatePack(p,blueprint).issues).toEqual([]);const covered=new Set<string>();for(const q of p.questions){expect(q.domainId).toBe('storage');expect(q.status).toBe('draft');expect(q.review).toBeNull();expect(q.provenance).toBe('ai-assisted');const subskills=(q as unknown as {subObjectiveIds:string[]}).subObjectiveIds;expect(subskills.length).toBeGreaterThan(0);for(const id of subskills)covered.add(id)}for(const objective of blueprint.domains.find(d=>d.id==='storage')!.objectives)for(let i=1;i<=objective.subObjectives.length;i++)expect(covered.has(`${objective.id}.${i}`)).toBe(true)});
 it('adds advanced multiselect ordered matching exhibits and linked case practice',()=>{const qs=read().questions;expect(qs.filter(q=>q.difficulty==='advanced').length).toBeGreaterThanOrEqual(10);expect(qs.filter(q=>q.type==='multiple').length).toBeGreaterThanOrEqual(10);for(const type of ['ordering','matching'])expect(qs.filter(q=>String(q.type)===type).length).toBeGreaterThanOrEqual(2);expect(qs.filter(q=>q.assessmentReserved).length).toBeGreaterThanOrEqual(10);const extras=qs as unknown as {caseStudy?:{id:string};exhibits?:unknown[]}[];expect(extras.filter(q=>q.exhibits?.length).length).toBeGreaterThanOrEqual(8);const groups=new Map<string,number>();for(const q of extras)if(q.caseStudy)groups.set(q.caseStudy.id,(groups.get(q.caseStudy.id)??0)+1);expect(groups.size).toBeGreaterThanOrEqual(2);expect([...groups.values()].every(n=>n===3)).toBe(true)});
 it('links every option claim to actually retrieved official evidence',()=>{const checks=JSON.parse(readFileSync('content/sources/storage-expanded.json','utf8')) as SourceCheck[];expect(new Set(checks.map(c=>c.referenceId)).size).toBe(checks.length);for(const q of read().questions){for(const reference of q.references){const check=checks.find(c=>c.referenceId===reference.id);expect(check,reference.id).toBeDefined();expect(check?.result).toBe('checked');expect(reference.url).toBe(check?.canonicalUrl);expect(reference.checkedAt).toBe(check?.checkedAt);expect(check?.contentHash).toMatch(/^[a-f0-9]{64}$/);expect(reference.microsoftOwnershipVerified).toBe(true);expect(reference.evidenceSummary.length).toBeGreaterThan(80)}for(const option of q.options){expect(option.explanation.length).toBeGreaterThan(45);expect(option.referenceIds.length).toBeGreaterThan(0);expect(option.referenceIds.every(id=>q.references.some(r=>r.id===id))).toBe(true)}expect(q.summaryReferenceIds.every(id=>q.references.some(r=>r.id===id))).toBe(true)}});
 it('audits all original ten revisions and supplies their legacy subskill mappings',()=>{const audit=JSON.parse(readFileSync('content/audits/storage-starter-audit.json','utf8')) as {humanReviewCompleted:boolean;questions:{questionId:string;revision:number;subObjectiveIds:string[];findings:unknown[];sourceReferenceIds:string[]}[]};expect(audit.humanReviewCompleted).toBe(false);expect(audit.questions).toHaveLength(10);expect(audit.questions.map(q=>q.questionId)).toEqual(Array.from({length:10},(_,i)=>`az104-storage-${String(i+1).padStart(2,'0')}`));for(const q of audit.questions){expect(q.revision).toBe(1);expect(q.subObjectiveIds.length).toBeGreaterThan(0);expect(q.findings.length).toBeGreaterThan(0);expect(q.sourceReferenceIds.length).toBeGreaterThan(0)}});
});
