import {useState} from 'react';
import learning from '../../../content/learning/az104-learning-draft.json';
import type {StudyRepository} from '../../storage/repository';
import {isAssessmentSession,type DatabaseSnapshot} from '../../sessions/types';
import {workspaceValue,writeWorkspace} from '../../storage/workspace';
import {buildFlashcards,scheduleFlashcard} from '../../study/flashcards';
import type {Flashcard} from '../../study/flashcards';
import {normaliseLearningState,type LearningState,type ReasoningRecord} from './state';
import './learning.css';

type Claim={text:string;referenceIds:string[];checkedAt:string};
type View='summaries'|'glossary'|'comparisons'|'walkthroughs'|'flashcards'|'reasoning';
const sections:{id:View;label:string}[]=[{id:'summaries',label:'Objective summaries'},{id:'glossary',label:'Glossary and acronyms'},{id:'comparisons',label:'Compare choices'},{id:'walkthroughs',label:'Practical walkthroughs'},{id:'flashcards',label:'Reviewed flashcards'},{id:'reasoning',label:'My reasoning and mistakes'}];
function ClaimView({claim}:{claim:Claim}){return <div className="learning-claim"><p>{claim.text}</p><small>{claim.referenceIds.map(id=>{const r=learning.references.find(ref=>ref.id===id);return r?<a key={id} href={r.url} target="_blank" rel="noreferrer">{id}</a>:<span key={id}>{id}</span>})} · Source checked {new Date(claim.checkedAt).toLocaleDateString()}</small></div>}
function CardReferences({card}:{card:Flashcard}){return <ul>{card.references.map(r=><li key={r.id}><a href={r.url} target="_blank" rel="noreferrer">{r.title}</a> · checked {new Date(r.checkedAt).toLocaleDateString()}</li>)}</ul>}
const emptyForm={questionId:'',revision:1,ownReasoning:'',missedCondition:'',correctedReasoning:'',comprehension:''};
export function LearningCenter({repository,snapshot}:{repository:StudyRepository;snapshot:DatabaseSnapshot}) {
 const [view,setView]=useState<View>('summaries'),[objective,setObjective]=useState('all'),[search,setSearch]=useState('');
 const [state,setState]=useState(()=>normaliseLearningState(workspaceValue(snapshot,'learning:state',{})));
 const [status,setStatus]=useState(''),[busy,setBusy]=useState(false),[revealed,setRevealed]=useState<string|null>(null),[position,setPosition]=useState(0);
 const [form,setForm]=useState(emptyForm),[recordObjective,setRecordObjective]=useState(learning.objectives[0].id);
 const questions=snapshot.packs.flatMap(p=>p.questions);
 const protectedQuestions=new Set(snapshot.sessions.filter(s=>s.status==='active'&&isAssessmentSession(s)).flatMap(s=>s.questionSnapshots.map(q=>`${q.id}:${q.revision}`)));
 const cards=buildFlashcards(questions.filter(q=>!protectedQuestions.has(`${q.id}:${q.revision}`)),snapshot.contentTrust,snapshot.releasedHoldouts.map(r=>r.questionId)).filter(c=>objective==='all'||c.objectiveId===objective);
 const now=new Date();
 const due=cards.filter(c=>{const s=state.schedules.find(s=>s.cardId===c.id);return !s||Date.parse(s.dueAt)<=now.getTime()});
 const card=due[position%due.length];
 const matches=(text:string)=>text.toLowerCase().includes(search.toLowerCase().trim());
 const inObjective=(id:string)=>objective==='all'||id===objective;
 async function save(next:LearningState){setBusy(true);setStatus('');try{await writeWorkspace(repository,'learning:state',{schedules:next.schedules,records:next.records});setState(next);setStatus('Saved locally and included in your backup.');return true}catch(e){setStatus(e instanceof Error?e.message:'Could not save.');return false}finally{setBusy(false)}}
 async function grade(value:'again'|'remembered'){if(!card)return;const schedule=scheduleFlashcard(state.schedules.find(s=>s.cardId===card.id)??null,{cardId:card.id,questionId:card.questionId,revision:card.revision},value,new Date());if(await save({...state,schedules:[...state.schedules.filter(s=>s.cardId!==card.id),schedule].slice(-2000)})){setRevealed(null);setPosition(0)}}
 async function saveReasoning(){if(state.records.length>=100){setStatus('Your notebook holds 100 records. Delete an old record before adding another.');return}const entry:ReasoningRecord={...form,id:crypto.randomUUID(),objectiveId:recordObjective,updatedAt:new Date().toISOString()};if(await save({...state,records:[entry,...state.records]}))setForm(emptyForm)}
 return <section className="learning-center" aria-labelledby="learning-title"><h1 id="learning-title">Learning center</h1>
 <p>Read a focused explanation, compare similar choices, or plan a practical exercise.</p>
 <p className="learning-draft"><strong>AI-assisted draft teaching material</strong> · Human factual review remains outstanding. Official source retrieval is evidence, not approval. Original study aids; these are not Microsoft exam questions.</p>
 <div className="learning-controls" aria-label="Learning sections">{sections.map(s=><button key={s.id} aria-pressed={view===s.id} onClick={()=>{setView(s.id);setRevealed(null)}}>{s.label}</button>)}</div>
 <div className="learning-filters"><label>Objective<select value={objective} onChange={e=>{setObjective(e.target.value);setPosition(0);setRevealed(null)}}><option value="all">All objectives</option>{learning.objectives.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label>{!['flashcards','reasoning'].includes(view)&&<label>Find a concept<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label>}</div>
 {status&&<p role="status">{status}</p>}
 {view==='summaries'&&<div>{learning.objectives.filter(o=>inObjective(o.id)&&matches(`${o.title} ${o.focus} ${o.claims.map(c=>c.text).join(' ')}`)).map(o=><article key={o.id}><h2>{o.title}</h2><p>{o.focus}</p>{o.claims.map((c,i)=><ClaimView key={i} claim={c}/>)}<a href={`#/practice?objective=${encodeURIComponent(o.id)}`}>Practice this objective</a></article>)}</div>}
 {view==='glossary'&&<div><p>Search the term, its expanded name or its meaning. Glossary entries cover all objectives.</p>{learning.glossary.filter(g=>matches(`${g.term} ${g.expanded} ${g.claim.text}`)).map(g=><article key={g.term}><h2>{g.term} — {g.expanded}</h2><ClaimView claim={g.claim}/></article>)}</div>}
 {view==='comparisons'&&<div>{learning.comparisons.filter(c=>inObjective(c.objectiveId)&&matches(`${c.title} ${c.claims.map(c=>c.text).join(' ')}`)).map(c=><article key={c.id}><h2>{c.title}</h2>{c.claims.map((c,i)=><ClaimView key={i} claim={c}/>)}</article>)}</div>}
 {view==='walkthroughs'&&<div><p>These are manual, optional exercises. Read and plan first. This app does not create Azure resources. Use an approved disposable environment and check pricing before creating anything.</p>{learning.walkthroughs.filter(w=>w.objectiveIds.some(inObjective)&&matches(`${w.title} ${w.steps.map(s=>s.text).join(' ')}`)).map(w=><article key={w.id}><h2>{w.title}</h2><h3>Prerequisites</h3><ul>{w.prerequisites.map(p=><li key={p}>{p}</li>)}</ul><h3>Cost planning</h3><p>{w.cost}</p><h3>Steps</h3><ol>{w.steps.map((s,i)=><li key={i}><ClaimView claim={s}/></li>)}</ol><h3>Cleanup</h3><p>{w.cleanup}</p></article>)}</div>}
 {view==='flashcards'&&<div><h2>Reviewed flashcards</h2><p>Answer cards and wrong-option cards use only current eligible reviewed question revisions. Reserved questions appear only after an explicit release. Questions in active assessments stay hidden until submission. This schedule is separate from question review and proficiency.</p><p>{cards.length} eligible cards · {due.length} due or new</p>{card?<article><h3>{card.kind==='wrong-option'?'Why this option fails':'Recall the answer'}</h3><p className="learning-card-text">{card.front}</p>{revealed===card.id?<><p className="learning-card-text">{card.back}</p><CardReferences card={card}/><div className="learning-controls"><button disabled={busy} onClick={()=>void grade('again')}>Review again tomorrow</button><button disabled={busy} onClick={()=>void grade('remembered')}>I remembered</button></div></>:<button onClick={()=>setRevealed(card.id)}>Reveal explanation</button>}<button disabled={due.length<2||busy} onClick={()=>{setPosition(position+1);setRevealed(null)}}>Skip card</button></article>:<p>{cards.length?'No cards are due. Return after their scheduled date.':'No eligible reviewed cards yet. Draft teaching material and unreviewed questions cannot generate approved flashcards.'}</p>}</div>}
 {view==='reasoning'&&<div><h2>My reasoning and mistakes</h2><p>Use your own words to identify the missed condition and explain the corrected choice. These personal notes are backed up; they do not approve content or change proficiency.</p><form onSubmit={e=>{e.preventDefault();void saveReasoning()}}><label>Record objective<select value={recordObjective} onChange={e=>{setRecordObjective(e.target.value);setForm({...form,questionId:"",revision:1})}}>{learning.objectives.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label><label>Optional question<select value={form.questionId} onChange={e=>{const q=questions.find(q=>q.id===e.target.value);setForm({...form,questionId:e.target.value,revision:q?.revision??1})}}><option value="">General concept</option>{questions.filter(q=>q.objectiveId===recordObjective).map(q=><option key={`${q.id}:${q.revision}`} value={q.id}>{q.id} · revision {q.revision} · {q.status}</option>)}</select></label>
 {([{key:'ownReasoning',label:'My original reasoning'},{key:'missedCondition',label:'Condition I missed'},{key:'correctedReasoning',label:'My corrected reasoning'},{key:'comprehension',label:'How I know I understand it'}] as const).map(f=><label key={f.key}>{f.label}<textarea maxLength={2000} required={f.key==='ownReasoning'} value={form[f.key]} onChange={e=>setForm({...form,[f.key]:e.target.value})}/></label>)}<button disabled={busy||!form.ownReasoning.trim()} type="submit">Save reasoning record</button></form>
 {state.records.filter(r=>inObjective(r.objectiveId)).map(r=><article key={r.id}><h3>{learning.objectives.find(o=>o.id===r.objectiveId)?.title??r.objectiveId}</h3><p>{r.questionId?`${r.questionId} · revision ${r.revision}`:'General concept'} · {new Date(r.updatedAt).toLocaleDateString()}</p><dl><dt>Original reasoning</dt><dd>{r.ownReasoning}</dd><dt>Missed condition</dt><dd>{r.missedCondition||'Not recorded'}</dd><dt>Corrected reasoning</dt><dd>{r.correctedReasoning||'Not recorded'}</dd><dt>Comprehension check</dt><dd>{r.comprehension||'Not recorded'}</dd></dl><button disabled={busy} onClick={()=>void save({...state,records:state.records.filter(x=>x.id!==r.id)})}>Delete record</button></article>)}</div>}
 </section>
}
