import {useRef,useState} from 'react';
import type {StudyRepository} from '../../storage/repository';
import type {DatabaseSnapshot} from '../../sessions/types';
import {workspaceValue,writeWorkspace} from '../../storage/workspace';
import {categories,JOURNEY_KEY,localDay,moveTask,normaliseJourney,objectives,todayQueue,validDay,weekSummary,type JourneyState,type Task} from './model';
import './journey.css';
export function Journey({repository,snapshot}:{repository:StudyRepository;snapshot:DatabaseSnapshot}){
 const today=localDay(),editVersion=useRef(0);
 const [state,setState]=useState(()=>normaliseJourney(workspaceValue(snapshot,JOURNEY_KEY,{}))),[status,setStatus]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false),[task,setTask]=useState<Task>({id:'',title:'',category:'reading',objectiveId:'',day:today,minutes:10,priority:3,completedAt:null,moves:[]}),[activity,setActivity]=useState({day:today,text:'',minutes:5}),[week,setWeek]=useState(today);
 async function save(next=state){const version=editVersion.current;setSaving(true);setError('');setStatus('Saving…');try{const safe=normaliseJourney(next);await writeWorkspace(repository,JOURNEY_KEY,{...safe});if(version===editVersion.current){setState(safe);setStatus('Saved on this device. Included in personal backups.')}else{setStatus('Earlier plan saved. Unsaved edits remain; Save plan again to keep them.')}}catch{setStatus('');setError('Could not save on this device. Your edits remain here; retry Save plan before leaving.')}finally{setSaving(false)}}
 function change(next:JourneyState){editVersion.current++;setState(next);setStatus('Unsaved edits. Save plan to keep them on this device.');setError('')}
 const summary=weekSummary(state,validDay(week)?week:today),queue=todayQueue(state,today);
 function updateTask(id:string,patch:Partial<Task>){change({...state,tasks:state.tasks.map(t=>t.id===id?{...t,...patch}:t)})}
 return <section className="journey"><h1>My study journey</h1><p>A self-paced personal plan. Choose what fits your time; these records do not measure exam readiness.</p>
 <form onSubmit={e=>{e.preventDefault();void save()}}><label>Personal goal<textarea maxLength={500} value={state.goal} onChange={e=>change({...state,goal:e.target.value})}/></label><label>Daily time budget (minutes)<input type="number" min={5} max={240} required value={state.dailyMinutes} onChange={e=>change({...state,dailyMinutes:Number(e.target.value)})}/></label><fieldset><legend>Days available for study</legend>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,i)=><label key={day} className="journey-check"><input type="checkbox" checked={state.days.includes(i)} onChange={e=>change({...state,days:e.target.checked?[...state.days,i]:state.days.filter(d=>d!==i)})}/>{day}</label>)}</fieldset><button disabled={saving}>Save plan</button></form>
 <button disabled={saving} onClick={()=>{const next={...state,paused:!state.paused,pauseHistory:[...state.pauseHistory,{paused:!state.paused,at:new Date().toISOString()}].slice(-500)};setState(next);void save(next)}}>{state.paused?'Resume plan':'Pause plan'}</button><p>{state.paused?'Plan paused. Tasks and activity history are kept.':'Plan active.'} {state.pauseHistory.length>0&&`${state.pauseHistory.length} pause/resume events saved in plan history.`}</p>
 {status&&<p role="status">{status}</p>}{error&&<p role="alert">{error}</p>}
 <h2>Today’s achievable queue</h2><p>{state.dailyMinutes}-minute budget; lowest priority number goes first. Only today’s tasks that fit are listed; unfinished earlier tasks can be carried forward below.</p>{queue.length?<ul>{queue.map(t=><li key={t.id}>{t.title} · {t.minutes} minutes <button disabled={saving} onClick={()=>{const next={...state,tasks:state.tasks.map(item=>item.id===t.id?{...item,completedAt:new Date().toISOString()}:item)};setState(next);void save(next)}}>Complete {t.title}</button></li>)}</ul>:<p>{state.paused?'Resume whenever you want to study.':'No tasks fit today’s available time. Edit the plan or take a short reading break.'}</p>}
 <p><a href="#/practice?count=5&amp;manual=true">Gentle practice: five questions with manual advancement</a> · <a href="#/practice?mode=draft-preview&count=5&timed=true&duration=5">Optional five-minute draft practice</a> · <a href="#/learning">Reading and flashcards</a> · <a href="#/explorer">Reading and lab explorer</a></p>
 <h2>Add a personal task</h2><form onSubmit={e=>{e.preventDefault();if(state.tasks.length>=500||!task.title.trim()||!validDay(task.day))return;const next={...state,tasks:[...state.tasks,{...task,id:crypto.randomUUID(),title:task.title.trim()}]};setState(next);setTask({...task,title:''});void save(next)}}><label>Task title<input required maxLength={200} value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/></label><label>Task category<select value={task.category} onChange={e=>setTask({...task,category:e.target.value as Task['category']})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>AZ-104 objective<select value={task.objectiveId} onChange={e=>setTask({...task,objectiveId:e.target.value})}><option value="">Personal / no objective</option>{objectives.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label><label>Planned day<input type="date" required value={task.day} onChange={e=>setTask({...task,day:e.target.value})}/></label><label>Estimated minutes<input type="number" min={1} max={240} required value={task.minutes} onChange={e=>setTask({...task,minutes:Number(e.target.value)})}/></label><label>Priority (1 first)<input type="number" min={1} max={99} required value={task.priority} onChange={e=>setTask({...task,priority:Number(e.target.value)})}/></label><button disabled={saving||state.tasks.length>=500}>Add task and save</button></form>
 <h2>Editable weekly plan</h2><label>Week containing<input type="date" value={week} onChange={e=>setWeek(e.target.value)}/></label><p>{summary.from} to {summary.to}. Task edits use Save plan.</p>{state.tasks.filter(t=>t.day>=summary.from&&t.day<=summary.to).sort((a,b)=>a.day.localeCompare(b.day)||a.priority-b.priority).map(t=><article key={t.id}><label>Title for {t.title}<input maxLength={200} value={t.title} onChange={e=>updateTask(t.id,{title:e.target.value})}/></label><p>{t.category} · {objectives.find(o=>o.id===t.objectiveId)?.title??'Personal task'} · {t.minutes} estimated minutes</p><label>Category for {t.title}<select value={t.category} onChange={e=>updateTask(t.id,{category:e.target.value as Task['category']})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Objective for {t.title}<select value={t.objectiveId} onChange={e=>updateTask(t.id,{objectiveId:e.target.value})}><option value="">Personal / no objective</option>{objectives.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label><label>Minutes for {t.title}<input type="number" min={1} max={240} value={t.minutes} onChange={e=>updateTask(t.id,{minutes:Number(e.target.value)})}/></label><label>Priority for {t.title}<input type="number" min={1} max={99} value={t.priority} onChange={e=>updateTask(t.id,{priority:Number(e.target.value)})}/></label><label>Carry {t.title} to day<input type="date" disabled={!!t.completedAt} value={t.day} onChange={e=>change(moveTask(state,t.id,e.target.value))}/></label>{t.moves.length>0&&<p>Carryover history: {t.moves.map(m=>`${m.from} → ${m.to}`).join('; ')}</p>}{t.completedAt?<p>Completed {new Date(t.completedAt).toLocaleString()}</p>:<button disabled={saving} onClick={()=>{const next={...state,tasks:state.tasks.map(item=>item.id===t.id?{...item,completedAt:new Date().toISOString()}:item)};setState(next);void save(next)}}>Mark {t.title} complete</button>}</article>)}
 <h2>Record study activity</h2><form onSubmit={e=>{e.preventDefault();if(state.activity.length>=500||!validDay(activity.day))return;const next={...state,activity:[...state.activity,{...activity,id:crypto.randomUUID()}]};setState(next);setActivity({...activity,text:''});void save(next)}}><label>Activity day<input type="date" required value={activity.day} onChange={e=>setActivity({...activity,day:e.target.value})}/></label><label>Short activity note<textarea maxLength={500} value={activity.text} onChange={e=>setActivity({...activity,text:e.target.value})}/></label><label>Actual minutes studied<input type="number" min={1} max={240} required value={activity.minutes} onChange={e=>setActivity({...activity,minutes:Number(e.target.value)})}/></label><button disabled={saving||state.activity.length>=500}>Record activity and save</button></form>
 <h2>Weekly personal review</h2><p>{summary.completed} tasks completed · {summary.entries} activity entries · {summary.minutes} actual minutes recorded for {summary.from} to {summary.to}.</p><ul>{summary.activity.map(a=><li key={a.id}>{a.day}: {a.text||'Study activity'} · {a.minutes} minutes</li>)}</ul><p>All recorded personal totals: {state.tasks.filter(t=>t.completedAt).length} completed tasks; {state.activity.reduce((n,a)=>n+a.minutes,0)} actual minutes. These are your own records, not coverage or readiness scores.</p><p>Plans store up to 500 tasks and 500 activity entries. Use Settings to export a personal backup.</p>
 </section>
}
