import {expect,it} from 'vitest';
import {question} from '../fixtures';
import {selectBalancedAssessment,selectCaseStudy} from '../../src/study/assessment';
import type {SelectionInput} from '../../src/study/selection';
import type {Question} from '../../src/content/types';
const approval=(q:Question)=>({questionId:q.id,revision:q.revision,sourceCheckedAt:'2026-10-08',humanReviewedAt:'2026-10-08',reviewer:'Owner',invalidatedAt:null});
function input():SelectionInput {const questions=['identity','storage','compute','networking','monitoring'].flatMap(domainId=>Array.from({length:30},(_,i)=>question({id:domainId+i,domainId,objectiveId:i<20?'first':'second',status:'reviewed'})));return {questions,trust:questions.map(approval),reviewItems:[],objectiveStats:[],previousSessionIds:[],attemptedIds:[],requestedCount:20,mode:'timed',useReserved:false,now:new Date(),random:()=>.5}}
it('allocates published midpoint weights and alternates objectives within domains',()=>{const result=selectBalancedAssessment(input());expect(result.allocations).toEqual([5,4,5,4,2]);expect(result.questions.filter(q=>q.domainId==='identity').map(q=>q.objectiveId)).toEqual(['first','second','first','second','first']);expect(result.shortages).toEqual([])});
it('allows drafts and filters reserve before allocation, opt-in releases only selected reserve',()=>{const i=input();i.questions=i.questions.slice(0,3);i.questions[0].status='draft';i.questions[1].assessmentReserved=true;expect(selectBalancedAssessment(i).questions.map(q=>q.id)).toEqual(['identity0','identity2']);expect(selectBalancedAssessment({...i,useReserved:true}).releasesReservedIds).toEqual(['identity1']);expect(selectBalancedAssessment(i).shortages.length).toBeGreaterThan(0)});
it('cases are indivisible when one member is unavailable',()=>{const questions=Array.from({length:3},(_,i)=>question({id:'case'+i,status:'reviewed',caseStudy:{id:'group',title:'Case',overview:'Shared context'},assessmentReserved:i===2}));const options={trust:questions.map(approval),draft:false,useReserved:false};expect(selectCaseStudy(questions,'group',options)).toEqual([]);expect(selectCaseStudy(questions,'group',{...options,useReserved:true})).toEqual(questions);questions[1].status='draft';expect(selectCaseStudy(questions,'group',{...options,useReserved:true})).toEqual(questions);expect(selectCaseStudy(questions,'group',{...options,useReserved:true,draft:true})).toHaveLength(3);expect(selectCaseStudy(questions,'missing',options)).toEqual([])});
it('invalidated case member is unavailable even in draft preview',()=>{const q=question({caseStudy:{id:'group',title:'Case',overview:'Context'}});expect(selectCaseStudy([q],'group',{trust:[{...approval(q),invalidatedAt:'2026-10-08'}],draft:true,useReserved:true})).toEqual([])});
