import {readFile} from 'node:fs/promises';
import {expect,test,chromium,webkit,type BrowserContext} from '@playwright/test';
import {chooseAnswer} from './answer';

async function installed(page:import('@playwright/test').Page){await page.goto('/');await expect(page.getByRole('button',{name:'Start Quick 10 →'})).toBeVisible();await page.evaluate(async()=>{await navigator.serviceWorker.ready});await page.reload();await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true)}

test('offline completeness inspects every required category and new routes reopen offline',async({page,context})=>{
 await installed(page);await page.goto('/#/settings');await page.getByRole('button',{name:'Check offline completeness'}).click();await expect(page.getByRole('status').filter({hasText:'Offline cache complete:'})).toBeVisible();
 const paths=await page.evaluate(async()=>{const result:string[]=[];for(const name of await caches.keys()){if(!name.includes('workbox-precache'))continue;const cache=await caches.open(name);result.push(...(await cache.keys()).map(request=>new URL(request.url).pathname))}return result});
 for(const name of ['question-bank','validators','vendor','study-data'])expect(paths.some(path=>path.includes('/assets/'+name+'-')&&path.endsWith('.js'))).toBe(true);
 await context.setOffline(true);for(const route of ['/library','/learning','/sources','/analytics','/settings']){await page.goto('/#'+route);await page.reload();await expect(page.getByText('Offline',{exact:true})).toBeVisible();await expect(page.locator('main')).not.toContainText('Opening your study workspace');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
});

test('offline completeness reports a deleted teaching-data chunk as incomplete',async({page})=>{
 await installed(page);await page.goto('/#/settings');await page.getByRole('button',{name:'Check offline completeness'}).click();await expect(page.getByRole('status').filter({hasText:'Offline cache complete:'})).toBeVisible();await page.evaluate(async()=>{for(const name of await caches.keys()){if(!name.includes('workbox-precache'))continue;const cache=await caches.open(name);for(const request of await cache.keys())if(new URL(request.url).pathname.includes('/assets/study-data-'))await cache.delete(request)}});await page.getByRole('button',{name:'Check offline completeness'}).click();await expect(page.getByRole('status').filter({hasText:'Offline cache incomplete.'})).toContainText('study data');
});

test('device model, failed checks and user assertion dates survive refresh without invented acceptance',async({page})=>{
 await page.goto('/#/settings');const report=page.locator('.device-checklist');await expect(report).toContainText('0 of 10 physical-device checks passed');await report.getByLabel('Device model').fill('User-entered device');await report.getByLabel('OS and version').fill('User-entered OS');await report.getByLabel('Browser and version').fill('User-entered browser');await report.getByLabel('Date tested').fill('2026-10-08');await report.getByLabel('Offline use result').selectOption('failed');await report.getByLabel('Offline use notes').fill('User reports offline reopen failed');await expect(report).toContainText('1 failed');
 await expect.poll(()=>page.evaluate(()=>new Promise<number>((resolve,reject)=>{const open=indexedDB.open('az104-studyapp');open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,get=db.transaction('workspace').objectStore('workspace').get('device:report');get.onsuccess=()=>{resolve(get.result?.value.checks.offline.notes==='User reports offline reopen failed'?1:0);db.close()};get.onerror=()=>reject(get.error)}}))).toBe(1);
 await page.reload();await expect(report.getByLabel('Device model')).toHaveValue('User-entered device');await expect(report.getByLabel('Offline use result')).toHaveValue('failed');await expect(report.getByLabel('Offline use notes')).toHaveValue('User reports offline reopen failed');await expect(report).toContainText('0 of 10 physical-device checks passed');await expect(report).toContainText('Metadata and results below are user assertions');await expect(report.getByLabel('Screen reader result')).toHaveValue('not-tested');
});

test('five-question manual configuration is available and draft feedback never enables speech',async({page})=>{
 await page.goto('/#/settings');await page.getByRole('link',{name:'Configure a gentle five-question session'}).click();await expect(page.getByRole('radio',{name:'5',exact:true})).toBeChecked();await page.getByRole('radio',{name:'5',exact:true}).check();await page.getByRole('button',{name:'Start session →'}).click();await chooseAnswer(page);await page.getByRole('button',{name:'Submit answer',exact:true}).click();await expect(page.getByRole('button',{name:'Next question',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Play explanation'})).toHaveCount(0);
});

test('reading position and saved answer survive pause, hidden visibility and reopening a page',async({page,context})=>{
 await page.goto('/');await page.getByRole('button',{name:'Start Quick 10 →'}).click();await chooseAnswer(page);await page.getByRole('button',{name:'Submit answer',exact:true}).click();await expect(page.getByRole('button',{name:'Next question',exact:true})).toBeVisible();const sessionURL=page.url();await page.evaluate(()=>{document.dispatchEvent(new Event('visibilitychange'));window.scrollTo(0,Math.min(320,document.documentElement.scrollHeight-innerHeight))});const y=await page.evaluate(()=>scrollY);expect(y).toBeGreaterThan(0);await page.getByRole('button',{name:'Pause & return home'}).click();await expect(page).toHaveURL(/#\/home$/);await page.goto(sessionURL);await expect(page.getByRole('button',{name:'Next question',exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>scrollY)).toBe(y);
 const replacement=await context.newPage();await replacement.goto(sessionURL);await page.close();await expect(replacement.getByRole('button',{name:'Next question',exact:true})).toBeVisible();await expect.poll(()=>replacement.evaluate(()=>scrollY)).toBe(y);await replacement.close();
});

test('a simulated interruption preserves a timed deadline and resume after expiry finalises once',async({page})=>{
 await page.clock.install({time:new Date('2026-10-08T12:00:00Z')});await page.goto('/#/practice');await page.getByRole('button',{name:'Timed practice Feedback when you finish'}).click();await page.getByLabel('Practice duration (minutes)').fill('1');await page.getByRole('button',{name:'Start session →'}).click();await expect(page.getByRole('timer',{name:'Time remaining'})).toBeVisible();const url=page.url(),sessionId=url.split('/session/')[1];const deadline=await page.evaluate(id=>new Promise<string>((resolve,reject)=>{const request=indexedDB.open('az104-studyapp');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,get=db.transaction('sessions').objectStore('sessions').get(id);get.onsuccess=()=>{resolve(get.result.deadlineAt);db.close()}}}),sessionId);await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await page.getByRole('button',{name:'Pause & return home'}).click();await expect(page).toHaveURL(/#\/home$/);await page.clock.fastForward(61000);await page.goto(url);await expect(page.getByRole('heading',{name:'Session complete'})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Session complete'})).toBeVisible();const saved=await page.evaluate(id=>new Promise<{deadline:string;attempts:number;questions:number}>((resolve,reject)=>{const request=indexedDB.open('az104-studyapp');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,transaction=db.transaction(['sessions','attempts']),get=transaction.objectStore('sessions').get(id),attempts=transaction.objectStore('attempts').getAll();transaction.oncomplete=()=>{resolve({deadline:get.result.deadlineAt,attempts:attempts.result.filter(attempt=>attempt.sessionId===id).length,questions:get.result.questionSnapshots.length});db.close()}}}),sessionId);expect(saved.deadline).toBe(deadline);expect(saved.attempts).toBe(saved.questions);
});

test('a five-question learning session finishes offline and its result survives reload',async({page,context})=>{
 await installed(page);await page.goto('/#/practice?count=5&manual=true');await page.getByRole('radio',{name:'5',exact:true}).check();await page.getByRole('button',{name:'Start session →'}).click();await context.setOffline(true);
 for(let index=0;index<5;index++){await chooseAnswer(page);await page.getByRole('button',{name:'Submit answer',exact:true}).click();await expect(page.getByRole('heading',{name:'Microsoft Learn sources'})).toBeVisible();await page.getByRole('button',{name:'Next question',exact:true}).click()}
 await expect(page.getByRole('heading',{name:'Session complete'})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Session complete'})).toBeVisible();await expect(page.locator('main')).toContainText('Your answers are saved');
});

for(const width of [320,430])test(`comfort and device controls remain readable at ${width}px with largest text`,async({page})=>{
 await page.setViewportSize({width,height:844});await page.goto('/#/settings');await page.getByLabel('Text size').selectOption('1.4');await expect(page.locator('html')).toHaveAttribute('data-theme',/system|light|dark/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);for(const label of ['Device model','OS and version','Browser and version','Offline use result']){const box=await page.getByLabel(label).boundingBox();expect(box?.height).toBeGreaterThanOrEqual(48);expect(box?.width).toBeGreaterThan(150)}
});

test('portable backup transfers personal device assertions from Chromium to WebKit with recovery guard',async({baseURL},testInfo)=>{
 test.skip(testInfo.project.name!=='chromium','Cross-engine pair runs once, with actual Chromium and desktop WebKit browser automation.');
 const source=await chromium.launch(),target=await webkit.launch();let from:BrowserContext|undefined,to:BrowserContext|undefined;
 try{from=await source.newContext();to=await target.newContext();const a=await from.newPage(),b=await to.newPage();await a.goto(baseURL+'/#/settings');await a.getByLabel('Device model').fill('Portable user assertion');await a.getByLabel('Offline use result').selectOption('failed');await a.getByLabel('Offline use notes').fill('Transfer this failure record');await expect.poll(()=>a.evaluate(()=>new Promise<string>((resolve,reject)=>{const request=indexedDB.open('az104-studyapp');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,get=db.transaction('workspace').objectStore('workspace').get('device:report');get.onsuccess=()=>{resolve(get.result?.value?.checks?.offline?.notes??'');db.close()}}}))).toBe('Transfer this failure record');const event=a.waitForEvent('download');await a.getByRole('button',{name:'Export backup',exact:true}).click();const file=await event,text=await readFile((await file.path())!,'utf8');await b.goto(baseURL+'/#/settings');await b.getByLabel('Import backup').setInputFiles({name:'chromium-portable.json',mimeType:'application/json',buffer:Buffer.from(text)});await expect(b.getByRole('region',{name:'Backup inspection'})).toContainText('personal workspace records');await expect(b.getByRole('button',{name:'Confirm replace'})).toBeDisabled();const recovery=b.waitForEvent('download');await b.getByRole('button',{name:'Download recovery backup'}).click();await recovery;await b.getByRole('button',{name:'Confirm replace'}).click();await expect(b.getByRole('status').filter({hasText:'Backup restored.'})).toBeVisible();await b.reload();await expect(b.getByLabel('Device model')).toHaveValue('Portable user assertion');await expect(b.getByLabel('Offline use result')).toHaveValue('failed');await expect(b.getByLabel('Offline use notes')).toHaveValue('Transfer this failure record');await expect(b.locator('.device-checklist')).toContainText('0 of 10 physical-device checks passed')}
 finally{await from?.close();await to?.close();await source.close();await target.close()}
});
