import {writeFile} from 'node:fs/promises';
import {expect,test} from '@playwright/test';
import {chooseAnswer} from './answer';

const routes=[['/journey','My study journey'],['/explorer','Cited learning explorer'],['/reports','Session history'],['/maintenance','Local diagnostics'],['/evidence-health','Evidence health']] as const;
test('every second-batch tool is accessible from home and reopens offline',async({page,context})=>{
 await page.goto('/');await expect(page.getByRole('button',{name:'Explore draft questions →'})).toBeVisible();await page.evaluate(async()=>{await navigator.serviceWorker.ready});await page.reload();await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);
 for(const [route] of routes)await expect(page.locator(`a[href="#${route}"]`).first()).toBeVisible();
 await context.setOffline(true);for(const [route,heading] of routes){await page.goto('/#'+route);await page.reload();await expect(page.getByRole('heading',{name:heading,exact:true})).toBeVisible();await expect(page.getByText('Offline',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
});
test('self-paced plan saves, pauses and resumes without losing its personal goal',async({page})=>{
 await page.goto('/#/journey');await page.getByLabel('Personal goal').fill('Read Azure storage when my arm allows');await page.getByLabel('Daily time budget (minutes)').fill('15');await page.getByRole('button',{name:'Save plan',exact:true}).click();await expect(page.getByRole('status')).toContainText('Saved on this device');await page.getByRole('button',{name:'Pause plan',exact:true}).click();await expect(page.getByRole('button',{name:'Resume plan',exact:true})).toBeVisible();await expect(page.getByRole('status')).toContainText('Saved on this device');await page.reload();await expect(page.getByLabel('Personal goal')).toHaveValue('Read Azure storage when my arm allows');await expect(page.getByRole('button',{name:'Resume plan',exact:true})).toBeVisible();await page.getByRole('button',{name:'Resume plan',exact:true}).click();await expect(page.getByRole('button',{name:'Pause plan',exact:true})).toBeVisible();
});
test('question reasoning autosaves before leaving and survives an offline reopen',async({page,context})=>{
 await page.goto('/');await page.evaluate(async()=>{await navigator.serviceWorker.ready});await page.reload();await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await page.getByRole('button',{name:'Explore draft questions →'}).click();await expect(page).toHaveURL(/#\/session\//);const url=page.url();await page.getByLabel('My approach').fill('Identify scope before selecting a role');await page.getByRole('button',{name:'Pause & return home'}).click();await expect(page).toHaveURL(/#\/home$/);await context.setOffline(true);await page.goto(url);await page.reload();await expect(page.getByLabel('My approach')).toHaveValue('Identify scope before selecting a role');await chooseAnswer(page);await page.getByRole('button',{name:'Submit answer',exact:true}).click();await expect(page.getByRole('button',{name:'Next question',exact:true})).toBeVisible();await expect(page.getByLabel('My post-answer reflection')).toBeVisible();
});
for(const width of [320,430])test(`second-batch tools fit ${width}px at largest text size`,async({page})=>{
 await page.setViewportSize({width,height:844});await page.goto('/#/settings');await page.getByLabel('Text size').selectOption('1.4');for(const [route,heading] of routes){await page.goto('/#'+route);await expect(page.getByRole('heading',{name:heading,exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route).toBe(true)}
});
test('home leaves heavy factual-audit and teaching modules deferred',async({browser,baseURL})=>{
 const context=await browser.newContext({serviceWorkers:'block'});try{const page=await context.newPage(),requests:string[]=[];page.on('request',request=>requests.push(request.url()));await page.goto(baseURL!+'/');await expect(page.getByRole('button',{name:'Explore draft questions →'})).toBeVisible();expect(requests.filter(url=>/\/assets\/(study-data|learning-data)-/.test(url))).toEqual([]);const transfers=await page.evaluate(()=>performance.getEntriesByType('resource').filter(entry=>new URL(entry.name).pathname.endsWith('.js')).map(entry=>({file:new URL(entry.name).pathname,encodedBodySize:(entry as PerformanceResourceTiming).encodedBodySize,decodedBodySize:(entry as PerformanceResourceTiming).decodedBodySize,transferSize:(entry as PerformanceResourceTiming).transferSize})));expect(transfers.reduce((sum,file)=>sum+file.encodedBodySize,0)).toBeGreaterThan(0);await writeFile('/tmp/studyapp-second100-initial-transfer-'+test.info().project.name+'.json',JSON.stringify({kind:'actual-browser-resource-transfer',origin:baseURL,serviceWorkers:'blocked',browserProject:test.info().project.name,checkedAt:new Date().toISOString(),files:transfers,encodedJavaScriptBytes:transfers.reduce((sum,file)=>sum+file.encodedBodySize,0),note:'Actual cold local-preview browser Resource Timing observations. Excludes service-worker installation; no live speed claim.'},null,2)+'\n');await page.goto(baseURL!+'/#/evidence');await expect(page.getByRole('heading',{name:'Evidence workbench'})).toBeVisible();expect(requests.some(url=>/\/assets\/study-data-/.test(url))).toBe(true)}finally{await context.close()}
});

test('journey offers an explicit optional five-minute draft timer',async({page})=>{
 await page.goto('/#/journey');await page.getByRole('link',{name:'Optional five-minute draft practice'}).click();await expect(page.getByRole('checkbox',{name:/Use a practice timer/})).toBeChecked();await expect(page.getByLabel('Practice duration (minutes)')).toHaveValue('5');await expect(page.getByRole('radio',{name:'5',exact:true})).toBeChecked();await page.getByRole('button',{name:'Start session →'}).click();await expect(page.getByRole('timer',{name:'Time remaining'})).toContainText('5:');await expect(page.locator('main')).toContainText('5 original practice questions');
});
