import {useEffect,useState} from 'react';
import type {StudyRepository} from '../../storage/repository';
import type {DatabaseSnapshot} from '../../sessions/types';
import {workspaceValue,writeWorkspace} from '../../storage/workspace';
import {backupReminder,personalWork} from '../../backup/inspection';
import {auditOfflineCache} from './offline';
import {normaliseComfortBackup,normaliseComfortPreferences} from './preferences';
export function ComfortPanel({repository,snapshot}:{repository:StudyRepository;snapshot:DatabaseSnapshot}){
 const preferences=normaliseComfortPreferences(workspaceValue(snapshot,'comfort:preferences',{})),backup=normaliseComfortBackup(workspaceValue(snapshot,'comfort:backup',{})),[days,setDays]=useState(preferences.reminderDays),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>setDays(preferences.reminderDays),[preferences.reminderDays]);
 const reminder=backupReminder(backup.lastExportAt,days,new Date(),personalWork(snapshot),backup.workFingerprint);
 return <section className="card" aria-labelledby="comfort-title"><h2 id="comfort-title">Comfort and reliability</h2><p>Start with five questions and advance manually so you can read at your own pace.</p><a className="button secondary" href="#/practice?count=5&manual=true&mode=learn">Configure a gentle five-question session</a><p>Read-aloud controls appear only on eligible reviewed explanations. Drafts stay visible as text. Pausing saves your reading position; timed assessments keep their original deadline.</p><label>Backup reminder interval<select value={days} onChange={e=>{const next=Number(e.target.value);setDays(next);void writeWorkspace(repository,'comfort:preferences',{reminderDays:next}).then(()=>setMessage('Backup reminder preference saved.')).catch(()=>setMessage('Backup reminder preference could not be saved.'))}}><option value="7">Every week</option><option value="14">Every two weeks</option><option value="30">Every month</option></select></label>{reminder&&<p className="notice">{reminder} <a href="#/settings">Open backup controls</a></p>}<h3>Offline completeness</h3><p>Check every file in this build’s asset inventory, including app code, question banks, teaching data, validation code, styles, manifest and icons. Microsoft Learn pages still need an internet connection. Device speech may also need connectivity.</p><button type="button" disabled={busy} onClick={()=>{setBusy(true);void auditOfflineCache().then(result=>setMessage(result.complete?`Offline cache complete: ${result.cachedFiles} cached files. Test a full session with your device connection disabled.`:`Offline cache incomplete. ${result.controlled?'':'Reopen after installation so the service worker controls this page. '}${result.missing.length?'Missing: '+result.missing.join(', ')+'.':''}`)).catch(error=>setMessage(error instanceof Error?error.message:'Offline cache could not be inspected.')).finally(()=>setBusy(false))}}>Check offline completeness</button>{message&&<p role="status">{message}</p>}</section>
}
