import type {StudyRepository} from '../../storage/repository';
import {useEffect,useRef,useState} from 'react';
import {readWorkspace,writeWorkspace} from '../../storage/workspace';
import './comfort.css';
export function readingPositionKey(sessionId:string,questionId:string){return 'comfort:position:'+encodeURIComponent(sessionId)+':'+encodeURIComponent(questionId)}
export function normalisePosition(input:unknown){if(!input||typeof input!=='object'||!('scrollY' in input)||typeof input.scrollY!=='number'||!Number.isFinite(input.scrollY))return 0;return Math.max(0,Math.round(input.scrollY))}
export function ReadingPosition({repository,sessionId,questionId,children}:{repository:StudyRepository;sessionId:string;questionId:string;children?:React.ReactNode}){
 const key=readingPositionKey(sessionId,questionId),[error,setError]=useState(''),[busy,setBusy]=useState(false),position=useRef(0),touched=useRef(false);
 useEffect(()=>{let live=true,restoring=true;position.current=window.scrollY;touched.current=false;void readWorkspace(repository,key,{scrollY:0}).then(value=>{if(live&&!touched.current){const y=normalisePosition(value);window.scrollTo(0,y);position.current=y}restoring=false}).catch(()=>{restoring=false;if(live)setError('Reading position could not be restored.')});let timer:ReturnType<typeof setTimeout>|undefined;const userIntent=()=>{touched.current=true};const save=()=>{position.current=window.scrollY;if(restoring&&!touched.current)return;touched.current=true;clearTimeout(timer);timer=setTimeout(()=>{void writeWorkspace(repository,key,{scrollY:position.current}).catch(()=>{if(live)setError('Reading position could not be saved. Retry before pausing.')})},250)};window.addEventListener('scroll',save,{passive:true});window.addEventListener('wheel',userIntent,{passive:true});window.addEventListener('touchstart',userIntent,{passive:true});window.addEventListener('keydown',userIntent);return()=>{live=false;clearTimeout(timer);window.removeEventListener('scroll',save);window.removeEventListener('wheel',userIntent);window.removeEventListener('touchstart',userIntent);window.removeEventListener('keydown',userIntent);if(touched.current)void writeWorkspace(repository,key,{scrollY:position.current}).catch(()=>{})}},[repository,key]);
 return <><button className="comfort-pause" type="button" disabled={busy} onClick={()=>{setBusy(true);setError('');touched.current=true;position.current=window.scrollY;void writeWorkspace(repository,key,{scrollY:position.current}).then(()=>{window.location.hash='/home'}).catch(()=>setError('Reading position could not be saved. Retry before pausing.')).finally(()=>setBusy(false))}}>Pause &amp; return home</button>{error&&<p role="alert">{error}</p>}{children}</>
}
