import {useEffect,useRef,useState} from 'react';
export function ReadAloud({text,enabled}:{text:string;enabled:boolean}){
 const [state,setState]=useState<'idle'|'playing'|'paused'>('idle'),[speed,setSpeed]=useState(1),[error,setError]=useState('');const active=useRef<SpeechSynthesisUtterance|null>(null);
 const supported=typeof speechSynthesis!=='undefined'&&typeof SpeechSynthesisUtterance!=='undefined';
 useEffect(()=>{setState('idle');setError('');return()=>{if(active.current&&typeof speechSynthesis!=='undefined'){active.current.onend=null;active.current.onerror=null;speechSynthesis.cancel();active.current=null}}},[text,enabled]);
 if(!enabled)return null;
 if(!supported)return <p className="fine-print">Read aloud is unavailable in this browser. Explanations remain available as text.</p>;
 function play(){try{speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.rate=speed;utterance.onend=()=>{active.current=null;setState('idle')};utterance.onerror=()=>{active.current=null;setState('idle');setError('Reading could not start. Try again or read the explanation as text.')};active.current=utterance;setError('');setState('playing');speechSynthesis.speak(utterance)}catch{setState('idle');setError('Reading could not start in this browser.')}}
 return <section aria-label="Read reviewed explanation"><label>Reading speed<select value={speed} disabled={state!=='idle'} onChange={e=>setSpeed(Number(e.target.value))}>{[.75,1,1.25,1.5].map(rate=><option key={rate} value={rate}>{rate}×</option>)}</select></label>{state==='idle'?<button type="button" onClick={play}>Play explanation</button>:<><button type="button" onClick={()=>{if(state==='playing'){speechSynthesis.pause();setState('paused')}else{speechSynthesis.resume();setState('playing')}}}>{state==='playing'?'Pause reading':'Resume reading'}</button><button type="button" onClick={()=>{speechSynthesis.cancel();active.current=null;setState('idle')}}>Stop reading</button></>}{error&&<p role="alert">{error}</p>}<p className="fine-print">Browser speech reads this eligible reviewed explanation. Use manual advancement while listening. Available voices and offline speech depend on your device.</p></section>
}
