import {backupTables,type BackupV1} from './types';
import type {DatabaseSnapshot} from '../sessions/types';
export interface PersonalWork{latestAt:string|null;fingerprint:string;records:number}
function canonical(value:unknown,exact=false):string{if(exact&&value===undefined)return 'undefined';if(Array.isArray(value))return '['+value.map(item=>canonical(item,exact)).join(',')+']';if(value&&typeof value==='object')return '{'+Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>JSON.stringify(key)+':'+canonical(item,exact)).join(',')+'}';return JSON.stringify(value)??'null'}
/** Exact canonical database contents for recovery replacement guards; no lossy hash. */
export function recoveryState(snapshot:DatabaseSnapshot):string{return canonical(Object.fromEntries(backupTables.map(name=>[name,(snapshot[name]??[]).map(row=>canonical(row,true)).sort()])))}
/** Non-authoritative change fingerprint for reminders; never supplies backup integrity or content trust. */
export function personalWork(snapshot:DatabaseSnapshot):PersonalWork{const workspace=(snapshot.workspace??[]).filter(row=>!row.id.startsWith('comfort:')),sessions=snapshot.sessions.map(({id,mode,answers,flags,currentIndex,status,submittedAt,deadlineAt})=>({id,mode,answers,flags,currentIndex,status,submittedAt,deadlineAt})),attempts=snapshot.attempts.map(({id,submittedAt,selectedOptionIds,confidence,correct,responseMs})=>({id,submittedAt,selectedOptionIds,confidence,correct,responseMs}));const groups={settings:snapshot.settings,sessions,attempts,notes:snapshot.notes,bookmarks:snapshot.bookmarks,reviews:snapshot.reviews,contentTrust:snapshot.contentTrust,releasedHoldouts:snapshot.releasedHoldouts,workspace:workspace.map(({id,value})=>({id,value}))};const encoded=canonical(groups);let hash=2166136261;for(let i=0;i<encoded.length;i++)hash=Math.imul(hash^encoded.charCodeAt(i),16777619);const dates=[...snapshot.attempts.map(row=>row.submittedAt),...snapshot.notes.map(row=>row.createdAt),...snapshot.bookmarks.map(row=>row.createdAt),...snapshot.sessions.flatMap(row=>[row.startedAt,row.submittedAt]),...workspace.map(row=>row.updatedAt),...snapshot.contentTrust.map(row=>row.humanReviewedAt)].filter((date):date is string=>typeof date==='string'&&Number.isFinite(Date.parse(date)));const latest=dates.length?Math.max(...dates.map(Date.parse)):null;return {latestAt:latest===null?null:new Date(latest).toISOString(),fingerprint:'v1:'+(hash>>>0).toString(16)+':'+encoded.length,records:Object.values(groups).reduce((sum,rows)=>sum+rows.length,0)}}
/** Call only after validateBackup succeeds; preview never writes or grants trust. */
export function inspectBackup(backup:BackupV1){return {schemaVersion:backup.schemaVersion,exportedAt:backup.exportedAt,questions:backup.packs.reduce((sum,p)=>sum+p.questions.length,0),packs:backup.packs.length,sessions:backup.sessions.length,attempts:backup.attempts.length,notes:backup.notes.length,bookmarks:backup.bookmarks.length,reviews:backup.reviews.length,workspace:backup.workspace?.length??0,activeSessions:backup.sessions.filter(s=>s.status==='active').length,warnings:['Restore replaces current local data; it does not merge histories.','Imported content needs fresh local review; file approvals do not grant study eligibility.',...(backup.workspace?[]:['Legacy schema-1 backup: workspace preferences start empty.'])]}}
export function backupReminder(last:string|null,days:number,now:Date,work?:PersonalWork,exportFingerprint?:string|null):string|null{if(work&&work.records===0)return null;if(typeof last!=='string'||!Number.isFinite(Date.parse(last)))return 'No backup export recorded.';if(work&&exportFingerprint){if(work.fingerprint===exportFingerprint)return null;return 'New work since last backup export. Keep an updated copy outside this browser.'}if(work?.latestAt&&Date.parse(work.latestAt)>Date.parse(last))return 'New work since last backup export. Keep an updated copy outside this browser.';return now.getTime()-Date.parse(last)>=Math.max(1,days)*86400000?'Backup export reminder due. Keep a copy outside this browser.':null}
