import {afterEach,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {Exam} from '../../src/features/practice/Exam';
import {StudyDatabase} from '../../src/storage/database';
import {StudyRepository} from '../../src/storage/repository';
import {SessionService} from '../../src/sessions/service';
import type {Session} from '../../src/sessions/types';
import {question} from '../fixtures';
const databases:StudyDatabase[]=[];afterEach(async()=>{for(const db of databases.splice(0))await db.delete()});
async function setup(expired=false,beforeRender?:(db:StudyDatabase)=>void){const db=new StudyDatabase(`exam-${crypto.randomUUID()}`);databases.push(db);const repository=new StudyRepository(db),service=new SessionService(repository),now=Date.now();const session:Session={id:'timed',mode:'timed',questionSnapshots:[question(),question({id:'q2',prompt:'Second prompt'})],optionOrders:{q1:['a','b','c'],q2:['a','b','c']},answers:{},flags:[],currentIndex:0,startedAt:new Date(now-1000).toISOString(),deadlineAt:new Date(now+(expired?-1:600000)).toISOString(),status:'active',submittedAt:null,correctionWarnings:[]};await db.sessions.put(session);beforeRender?.(db);let finished=0;render(<Exam session={session} repository={repository} service={service} onChanged={()=>{}} onFinished={async()=>{finished++}}/>);return {db,repository,service,get finished(){return finished}}}
it('feedback_hidden_until_final_submission and explicit unanswered confirmation',async()=>{const t=await setup();expect(screen.queryByText('Test reason')).not.toBeInTheDocument();expect(screen.queryByText('Test source')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Finish practice'}));await screen.findByText(/2 unanswered/);expect(await t.db.attempts.count()).toBe(0);fireEvent.click(screen.getByRole('button',{name:'Cancel submission'}));expect(await t.db.attempts.count()).toBe(0);fireEvent.click(screen.getByRole('button',{name:'Finish practice'}));fireEvent.click(screen.getByRole('button',{name:'Confirm submission'}));await waitFor(()=>expect(t.finished).toBe(1));const attempts=await t.db.attempts.toArray();expect(attempts).toHaveLength(2);expect(attempts.every(a=>!a.correct&&a.selectedOptionIds.length===0)).toBe(true)});
it('flags_and_answers_survive_navigation and edits remain possible',async()=>{const t=await setup();fireEvent.click(screen.getByRole('radio',{name:'A'}));fireEvent.click(screen.getByRole('button',{name:'Flag question'}));await waitFor(async()=>expect((await t.db.sessions.get('timed'))?.flags).toEqual(['q1']));fireEvent.click(screen.getByRole('button',{name:'Go to question 2'}));await screen.findByText('Second prompt');fireEvent.click(screen.getByRole('button',{name:'Go to question 1'}));await screen.findByText('Test prompt');expect(screen.getByRole('radio',{name:'A'})).toBeChecked();expect(screen.getByRole('button',{name:'Unflag question'})).toBeInTheDocument();fireEvent.click(screen.getByRole('radio',{name:'B'}));await waitFor(async()=>expect((await t.db.sessions.get('timed'))?.answers.q1.selectedOptionIds).toEqual(['b']));expect(await t.db.attempts.count()).toBe(0)});
it('background_past_deadline_scores_once and locks edits',async()=>{const t=await setup(true);document.dispatchEvent(new Event('visibilitychange'));document.dispatchEvent(new Event('visibilitychange'));await waitFor(()=>expect(t.finished).toBe(1));expect(await t.db.attempts.count()).toBe(2);const first=(await t.db.sessions.get('timed'))?.result;await t.service.finaliseTimedSession('timed',new Date());expect((await t.db.sessions.get('timed'))?.result).toEqual(first);expect(await t.db.attempts.count()).toBe(2);expect(screen.queryByRole('radio',{name:'A'})).not.toBeInTheDocument()});
it('failed finalisation rolls back and offers retry',async()=>{const t=await setup();const fail=()=>{throw Error('Storage unavailable')};t.db.attempts.hook('creating',fail);fireEvent.click(screen.getByRole('button',{name:'Finish practice'}));await screen.findByRole('button',{name:'Confirm submission'});fireEvent.click(screen.getByRole('button',{name:'Confirm submission'}));expect(await screen.findByRole('alert')).toHaveTextContent('Storage unavailable');expect(await t.db.attempts.count()).toBe(0);expect(t.finished).toBe(0);t.db.attempts.hook('creating').unsubscribe(fail);fireEvent.click(screen.getByRole('button',{name:'Retry final submission'}));await waitFor(()=>expect(t.finished).toBe(1));expect(await t.db.attempts.count()).toBe(2)});
it('countdown derives from deadline when returning from background',async()=>{await setup();expect(screen.getByRole('timer')).toHaveTextContent('10:00');const clock=vi.spyOn(Date,'now').mockReturnValue(Date.now()+120000);try{document.dispatchEvent(new Event('visibilitychange'));await waitFor(()=>expect(screen.getByRole('timer')).toHaveTextContent('8:00'))}finally{clock.mockRestore()}});
it('expiry storage failure waits for explicit retry instead of repeating on visibility',async()=>{let writes=0;const fail=()=>{writes++;throw Error('Quota unavailable')};const t=await setup(true,db=>db.attempts.hook('creating',fail));await screen.findByRole('alert');document.dispatchEvent(new Event('visibilitychange'));await new Promise(resolve=>setTimeout(resolve,20));expect(writes).toBe(1);t.db.attempts.hook('creating').unsubscribe(fail);fireEvent.click(screen.getByRole('button',{name:'Retry final submission'}));await waitFor(()=>expect(t.finished).toBe(1))});
