import {it,expect} from 'vitest';
import {StudyDatabase} from '../../src/storage/database';
import {StudyRepository,defaultSettings} from '../../src/storage/repository';
import {recoveryState} from '../../src/backup/inspection';
import {exportBackup,restoreBackup} from '../../src/backup/restore';
import type {BackupV1} from '../../src/backup/types';
import {pack} from '../fixtures';
it('canonical recovery includes comfort, pack and source values while ignoring row and property order',async()=>{const db=new StudyDatabase(`recovery-state-${crypto.randomUUID()}`),r=new StudyRepository(db);try{await r.saveSettings(defaultSettings);await r.installPack(pack(),[]);const snapshot=await r.getSnapshot(),state=recoveryState(snapshot);expect(recoveryState({...snapshot,settings:[Object.fromEntries(Object.entries(defaultSettings).reverse()) as typeof defaultSettings]})).toBe(state);expect(recoveryState({...snapshot,workspace:[{id:'comfort:preferences',version:1,value:{quiet:true},updatedAt:'2026-10-08T12:00:00Z'}]})).not.toBe(state);expect(recoveryState({...snapshot,packs:[{...snapshot.packs[0],version:2}]})).not.toBe(state);expect(recoveryState({...snapshot,sourceChecks:[{referenceId:'new',canonicalUrl:'https://learn.microsoft.com/',checkedAt:'2026-10-08T12:00:00Z',result:'checked',evidenceSummary:'Changed evidence'}]})).not.toBe(state)}finally{await db.delete()}});
it('checks the actual transaction state before any clears, and permits replacement after fresh recovery',async()=>{const db=new StudyDatabase(`recovery-atomic-${crypto.randomUUID()}`),r=new StudyRepository(db);try{await r.saveSettings(defaultSettings);const captured=await r.getSnapshot(),backup=JSON.parse(await exportBackup({...captured,settings:[{...defaultSettings,theme:'dark'}]}).text()) as BackupV1,confirmation={replaceConfirmed:true,recoveryBackup:exportBackup(captured),expectedRecoveryState:recoveryState(captured)};await db.transaction('rw',db.workspace,async()=>{await db.workspace.put({id:'comfort:preferences',version:1,value:{quiet:true},updatedAt:'2026-10-08T12:00:00Z'})});const before=await r.getSnapshot();let clears=0;const hook=()=>{clears++};db.settings.hook('deleting',hook);await expect(restoreBackup(r,backup,confirmation)).rejects.toThrow(/Download a new recovery backup/);expect(clears).toBe(0);expect(await r.getSnapshot()).toEqual(before);await restoreBackup(r,backup,{...confirmation,recoveryBackup:exportBackup(before),expectedRecoveryState:recoveryState(before)});expect((await r.getSettings()).theme).toBe('dark')}finally{await db.delete()}});
