import {afterEach,it,expect} from 'vitest';
import {StudyDatabase} from '../../src/storage/database';
import {StudyRepository,defaultSettings} from '../../src/storage/repository';
import {question,pack} from '../fixtures';
import {exportBackup,restoreBackup,deletePersonalData} from '../../src/backup/restore';
import {validateBackup} from '../../src/backup/validate';
import type {BackupV1} from '../../src/backup/types';
const databases:StudyDatabase[]=[];
function repo(){const db=new StudyDatabase(`backup-${crypto.randomUUID()}`);databases.push(db);return new StudyRepository(db)}
afterEach(async()=>{for(const db of databases.splice(0))await db.delete()});
async function populated(){const r=repo(),q=question();await r.installPack(pack(),[{referenceId:'s1',canonicalUrl:q.references[0].url,checkedAt:'2026-10-08T12:00:00Z',result:'checked',evidenceSummary:'Saved source evidence',contentHash:'test-hash'}]);await r.saveSettings({...defaultSettings,examDate:'2027-01-01'});await r.db.sessions.put({id:'session',mode:'timed',questionSnapshots:[q],optionOrders:{q1:['a','b','c']},answers:{q1:{selectedOptionIds:['a'],confidence:'confident',responseMs:500}},flags:['q1'],currentIndex:0,startedAt:'2026-10-08T12:00:00Z',deadlineAt:'2026-10-08T12:30:00Z',status:'submitted',submittedAt:'2026-10-08T12:01:00Z',correctionWarnings:[],result:{sessionId:'session',submittedAt:'2026-10-08T12:01:00Z',correct:1,total:1,attemptIds:['session:q1'],domainResults:[{domainId:'identity',correct:1,total:1}]}});await r.db.attempts.put({id:'session:q1',sessionId:'session',questionId:'q1',questionRevision:1,questionSnapshot:q,selectedOptionIds:['a'],confidence:'confident',correct:true,responseMs:500,submittedAt:'2026-10-08T12:01:00Z',mode:'timed'});await r.db.notes.put({questionId:'q1',revision:1,text:'<b>My plain-text note</b>',createdAt:'2026-10-08T12:00:00Z'});await r.db.bookmarks.put({questionId:'q1',revision:1,createdAt:'2026-10-08T12:00:00Z'});await r.db.reviews.put({questionId:'q1',revision:1,stage:1,dueAt:'2026-10-09T12:00:00Z',misconception:false});await r.db.releasedHoldouts.put({questionId:'q1'});return r}
async function backup(r:StudyRepository):Promise<BackupV1>{return JSON.parse(await exportBackup(await r.getSnapshot()).text())}
async function confirmation(r:StudyRepository){return {replaceConfirmed:true,recoveryBackup:exportBackup(await r.getSnapshot())}}
it('complete_round_trip preserves all personal history and quarantines sources',async()=>{const source=await populated(),b=await backup(source),target=repo();expect(validateBackup(b,1000).valid).toBe(true);await restoreBackup(target,b,await confirmation(target));const snap=await target.getSnapshot();for(const key of ['settings','sourceChecks','sessions','attempts','reviews','bookmarks','notes','releasedHoldouts'] as const)expect(snap[key]).toEqual(b[key]);expect(snap.packs[0].questions[0].references[0].microsoftOwnershipVerified).toBe(false)});
it('over_ten_mb_rejected and future_version_rejected',async()=>{const b=await backup(repo());expect(validateBackup(b,10_485_761).valid).toBe(false);expect(validateBackup({...b,schemaVersion:2},1000).valid).toBe(false);expect(validateBackup({...b,schemaVersion:0},1000).valid).toBe(false)});
it('invalid_reference_rejected_before_write including duplicates dates and sources',async()=>{const r=await populated(),b=await backup(r),before=await r.getSnapshot();b.attempts[0].sessionId='missing';await expect(restoreBackup(r,b,await confirmation(r))).rejects.toThrow();expect(await r.getSnapshot()).toEqual(before);const clean=await backup(r);expect(validateBackup({...clean,attempts:[...clean.attempts,...clean.attempts]},1000).valid).toBe(false);clean.sessions[0].deadlineAt='bad';expect(validateBackup(clean,1000).valid).toBe(false);const other=await backup(r);other.packs[0].questions[0].references[0].url='https://evil.test';expect(validateBackup(other,1000).valid).toBe(false)});
it('cancel_keeps_database and recovery is required',async()=>{const r=await populated(),before=await r.getSnapshot(),b=await backup(repo());await restoreBackup(r,b,{replaceConfirmed:false,recoveryBackup:exportBackup(before)});expect(await r.getSnapshot()).toEqual(before);await expect(restoreBackup(r,b,{replaceConfirmed:true,recoveryBackup:new Blob()})).rejects.toThrow(/recovery/i);expect(await r.getSnapshot()).toEqual(before)});
it('failed_replace_rolls_back',async()=>{const r=await populated(),before=await r.getSnapshot(),b=await backup(repo());b.settings=[{...defaultSettings}];const fail=()=>{throw Error('write failed')};r.db.settings.hook('creating',fail);await expect(restoreBackup(r,b,await confirmation(r))).rejects.toThrow('write failed');r.db.settings.hook('creating').unsubscribe(fail);expect(await r.getSnapshot()).toEqual(before)});
it('imported_trust_is_quarantined without erasing attempts',async()=>{const r=await populated(),b=await backup(r);b.packs[0].questions[0].status='verified';b.packs[0].questions[0].review={reviewer:'import',reviewedAt:b.exportedAt,method:'asserted'};b.contentTrust=[{questionId:'q1',revision:1,sourceCheckedAt:b.exportedAt,humanReviewedAt:b.exportedAt,reviewer:'import',invalidatedAt:null}];await restoreBackup(r,b,await confirmation(r));const after=await r.getSnapshot();expect(after.contentTrust).toEqual([]);expect(after.packs[0].questions[0].status).toBe('draft');expect(after.packs[0].questions[0].review).toBeNull();expect(after.attempts).toEqual(b.attempts)});
it('delete_needs_confirmation and clears personal data',async()=>{const r=await populated(),before=await r.getSnapshot();await deletePersonalData(r,false);expect(await r.getSnapshot()).toEqual(before);await deletePersonalData(r,true);expect(Object.values(await r.getSnapshot()).every(rows=>rows.length===0)).toBe(true);await r.installPack(pack(),[]);expect(await r.getQuestions()).toHaveLength(1)});
it('rejects malformed source dates dangling evidence and oversized notes',async()=>{const r=await populated(),b=await backup(r);b.packs[0].questions[0].references[0].checkedAt='2026-02-30T12:00:00Z';expect(validateBackup(b,1000).valid).toBe(false);const c=await backup(r);c.notes[0].text='x'.repeat(10001);expect(validateBackup(c,1000).valid).toBe(false);const d=await backup(r);d.packs[0].questions[0].options[0].referenceIds=['missing'];expect(validateBackup(d,1000).valid).toBe(false)});
it('preserves unanswered timed attempts created at deadline',async()=>{const r=await populated(),b=await backup(r);b.sessions[0].answers={};b.sessions[0].submittedAt=b.sessions[0].deadlineAt;b.sessions[0].result!.submittedAt=b.sessions[0].deadlineAt!;b.attempts[0].submittedAt=b.sessions[0].deadlineAt!;b.attempts[0].responseMs=0;b.attempts[0].selectedOptionIds=[];b.attempts[0].confidence='unknown';b.attempts[0].correct=false;b.sessions[0].result!.correct=0;b.sessions[0].result!.domainResults[0].correct=0;expect(validateBackup(b,1000).valid).toBe(true);const target=repo();await restoreBackup(target,b,await confirmation(target));expect((await target.getSnapshot()).attempts).toEqual(b.attempts)});
it('accepts service-generated composite attempt IDs for maximum-length question IDs',async()=>{const r=await populated(),b=await backup(r),id='q'.repeat(100),s=b.sessions[0];b.packs[0].questions[0].id=id;s.questionSnapshots[0].id=id;s.optionOrders={[id]:['a','b','c']};s.answers={[id]:s.answers.q1};s.flags=[id];const a=b.attempts[0];a.id=`session:${id}`;s.result!.attemptIds=[a.id];a.questionId=id;a.questionSnapshot.id=id;for(const row of [...b.notes,...b.bookmarks,...b.reviews,...b.releasedHoldouts])row.questionId=id;expect(validateBackup(b,1000).valid).toBe(true)});
it('round-trips official source ledger entries not referenced by installed questions',async()=>{const r=await populated();await r.db.sourceChecks.put({referenceId:'blueprint-guide',canonicalUrl:'https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-104',checkedAt:'2026-10-08T12:00:00Z',result:'checked',evidenceSummary:'Blueprint source evidence'});const b=await backup(r);expect(validateBackup(b,1000).valid).toBe(true);const target=repo();await restoreBackup(target,b,await confirmation(target));expect((await target.getSnapshot()).sourceChecks).toEqual(b.sourceChecks)});
it('rejects arbitrary attempt IDs and duplicate session-question attempts before replacing',async()=>{const r=await populated(),before=await r.getSnapshot(),b=await backup(r);b.attempts[0].id='arbitrary';b.sessions[0].result!.attemptIds=['arbitrary'];expect(validateBackup(b,1000).valid).toBe(false);await expect(restoreBackup(r,b,await confirmation(r))).rejects.toThrow();expect(await r.getSnapshot()).toEqual(before);const duplicate=await backup(r);duplicate.attempts.push({...duplicate.attempts[0],id:'other-id'});expect(validateBackup(duplicate,1000).valid).toBe(false)});
it('submitted sessions require complete attempts and matching persisted results',async()=>{const r=await populated(),missingResult=await backup(r);delete missingResult.sessions[0].result;expect(validateBackup(missingResult,1000).valid).toBe(false);const missingAttempt=await backup(r);missingAttempt.attempts=[];missingAttempt.sessions[0].result!.attemptIds=[];expect(validateBackup(missingAttempt,1000).valid).toBe(false);const omittedResultId=await backup(r);omittedResultId.sessions[0].result!.attemptIds=[];expect(validateBackup(omittedResultId,1000).valid).toBe(false);const resultScore=await backup(r);resultScore.sessions[0].result!.correct=0;expect(validateBackup(resultScore,1000).valid).toBe(false);const domainScore=await backup(r);domainScore.sessions[0].result!.domainResults[0].total=2;expect(validateBackup(domainScore,1000).valid).toBe(false)});
it('rejects internally changed attempt snapshots but retains history without its installed pack',async()=>{const r=await populated(),b=await backup(r);b.attempts[0].questionSnapshot.prompt='Changed historical wording';expect(validateBackup(b,1000).valid).toBe(false);const history=await backup(r);history.packs=[];history.contentTrust=[];expect(validateBackup(history,1000).valid).toBe(true);const target=repo();await restoreBackup(target,history,await confirmation(target));expect((await target.getSnapshot()).sessions).toEqual(history.sessions);expect((await target.getSnapshot()).attempts).toEqual(history.attempts)});
it.each(['timed','learn'] as const)('accepts real service-generated %s histories',async mode=>{const r=await populated(),s=(await r.db.sessions.get('session'))!;await r.db.attempts.clear();s.mode=mode;s.status='active';s.submittedAt=null;s.answers={};delete s.result;if(mode==='learn')s.deadlineAt=null;await r.db.sessions.put(s);const {SessionService}=await import('../../src/sessions/service');const service=new SessionService(r,()=>new Date('2026-10-08T12:01:00Z'));if(mode==='timed'){await service.saveDraftAnswer(s.id,'q1',{selectedOptionIds:['b'],confidence:'guessed',responseMs:700});await service.finaliseTimedSession(s.id,new Date('2026-10-08T12:01:00Z'))}else{await service.submitLearnAnswer(s.id,'q1',['a'],'confident',500);await service.advanceSession(s.id)}const b=await backup(r);expect(validateBackup(b,1000).issues).toEqual([])});
it('rejects score timestamp and durable answer mismatches',async()=>{const r=await populated(),score=await backup(r);score.attempts[0].correct=false;score.sessions[0].result!.correct=0;score.sessions[0].result!.domainResults[0].correct=0;expect(validateBackup(score,1000).valid).toBe(false);const date=await backup(r);date.attempts[0].submittedAt='2026-10-08T11:59:00Z';expect(validateBackup(date,1000).valid).toBe(false);const answer=await backup(r);answer.sessions[0].answers.q1.selectedOptionIds=['b'];expect(validateBackup(answer,1000).valid).toBe(false);const active=await backup(r);active.sessions[0].status='active';active.sessions[0].submittedAt=null;expect(validateBackup(active,1000).valid).toBe(false)});
