import {afterEach,expect,it} from 'vitest';
import {StudyDatabase} from '../../src/storage/database';
import {StudyRepository,defaultSettings} from '../../src/storage/repository';
import {validateBackup} from '../../src/backup/validate';
import {exportBackup,restoreBackup} from '../../src/backup/restore';
import type {BackupV1} from '../../src/backup/types';
import {SessionService} from '../../src/sessions/service';
import {question,pack} from '../fixtures';
const databases:StudyDatabase[]=[];
const now=new Date('2026-10-08T12:00:00Z');
function repository(){const db=new StudyDatabase(`backup-preview-${crypto.randomUUID()}`);databases.push(db);return new StudyRepository(db)}
afterEach(async()=>{for(const db of databases.splice(0))await db.delete()});
async function backup(r:StudyRepository):Promise<BackupV1>{return JSON.parse(await exportBackup(await r.getSnapshot()).text())}
it('accepts active and submitted timed previews including unanswered attempts',async()=>{const r=repository(),q=question();await r.installPack(pack([q]),[]);const service=new SessionService(r,()=>now);const s=await service.createSession({mode:'draft-preview',selectedQuestions:[q],durationMinutes:1,releasesReservedIds:[]});await service.finaliseTimedSession(s.id,new Date('2026-10-08T12:01:00Z'));const b=await backup(r);expect(validateBackup(b,1000).issues).toEqual([]);const target=repository();await restoreBackup(target,b,{replaceConfirmed:true,recoveryBackup:exportBackup(await target.getSnapshot())});expect((await target.getSnapshot()).attempts[0].mode).toBe('draft-preview');const active=structuredClone(b);active.sessions[0].status='active';active.sessions[0].submittedAt=null;delete active.sessions[0].result;active.attempts=[];expect(validateBackup(active,1000).issues).toEqual([])});
it('preserves ordering and matching snapshots and incomplete durable assignments',async()=>{for(const type of ['ordering','matching'] as const){const r=repository(),q=question({type,requiredSelections:3,correctOptionIds:['c','a','b'],...(type==='matching'?{matchPrompts:[{id:'one',text:'First'},{id:'two',text:'Second'},{id:'three',text:'Third'}]}:{})});await r.installPack(pack([q]),[]);const service=new SessionService(r,()=>now),s=await service.createSession({mode:'draft-preview',selectedQuestions:[q],durationMinutes:null,releasesReservedIds:[]});await service.saveDraftAnswer(s.id,q.id,{selectedOptionIds:['c','a'],confidence:'unsure',responseMs:2});const b=await backup(r);expect(validateBackup(b,1000).issues).toEqual([]);const target=repository();await restoreBackup(target,b,{replaceConfirmed:true,recoveryBackup:exportBackup(await target.getSnapshot())});expect((await target.getSnapshot()).sessions[0].answers[q.id].selectedOptionIds).toEqual(['c','a'])}});
it('supports optional thumb controls while accepting legacy v1 settings unchanged',async()=>{const r=repository();await r.saveSettings({...defaultSettings});const legacy=await backup(r);expect(validateBackup(legacy,1000).valid).toBe(true);const updated=structuredClone(legacy);updated.settings[0]={...updated.settings[0],thumbControls:true};expect(validateBackup(updated,1000).issues).toEqual([]);const target=repository();await restoreBackup(target,updated,{replaceConfirmed:true,recoveryBackup:exportBackup(await target.getSnapshot())});expect((await target.getSnapshot()).settings[0].thumbControls).toBe(true)});
it('continues rejecting deadlines on learning sessions',async()=>{const r=repository(),q=question();await r.installPack(pack([q]),[]);const service=new SessionService(r,()=>now);await service.createSession({mode:'draft-preview',selectedQuestions:[q],durationMinutes:null,releasesReservedIds:[]});const b=await backup(r);b.sessions[0].mode='learn';b.sessions[0].deadlineAt='2026-10-08T12:01:00Z';expect(validateBackup(b,1000).valid).toBe(false)});
