import {useCallback,useEffect,useState} from 'react';import {createAppServices,type AppServices} from './bootstrap';import {currentRoute,navigate} from './navigation';import blueprintData from '../../content/blueprints/az104-2026-04-17.json';import type {Blueprint} from '../content/types';import type {DatabaseSnapshot,Session,SessionMode,Attempt} from '../sessions/types';import {defaultSettings} from '../storage/repository';import {classifyQuestion} from '../content/trust';import {selectQuestions} from '../study/selection';import {Home} from '../features/home/Home';import {Practice} from '../features/practice/Practice';import {QuestionView} from '../features/practice/Question';import {FeedbackView} from '../features/practice/Feedback';import {Summary} from '../features/practice/Summary';import {SettingsView} from '../features/settings/Settings';import {calculateProgress} from '../study/progress';import {ProgressView} from '../features/progress/Progress';import {ReviewView} from '../features/review/Review';import {Annotations} from '../features/review/Annotations';import './app.css';
const blueprint=blueprintData as Blueprint;
const icons:Record<string,string>={home:'M3 10 12 3l9 7v10h-6v-6H9v6H3z',practice:'M5 3h14v18H5z M8 7h8 M8 11h8 M8 15h5',review:'M4 5v5h5 M4 10a8 8 0 1 1 2 8',progress:'M4 20h16 M7 16v-4 M12 16V7 M17 16V3',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2'};
export default function App(){const [services,setServices]=useState<AppServices|null>(null),[snapshot,setSnapshot]=useState<DatabaseSnapshot|null>(null),[route,setRoute]=useState(currentRoute()),[session,setSession]=useState<Session|null>(null),[attempt,setAttempt]=useState<Attempt|null>(null),[error,setError]=useState(''),[online,setOnline]=useState(navigator.onLine);
 const refresh=useCallback(async(s:AppServices)=>setSnapshot(await s.repository.getSnapshot()),[]);
 useEffect(()=>{let live=true;void createAppServices().then(async s=>{if(live){setServices(s);await refresh(s)}}).catch(e=>setError('Could not open browser storage: '+e.message));return()=>{live=false}},[refresh]);
 useEffect(()=>{const change=()=>setRoute(currentRoute()),network=()=>setOnline(navigator.onLine);window.addEventListener('hashchange',change);window.addEventListener('online',network);window.addEventListener('offline',network);return()=>{window.removeEventListener('hashchange',change);window.removeEventListener('online',network);window.removeEventListener('offline',network)}},[]);
 useEffect(()=>{if(!services)return;const id=route.startsWith('/session/')?route.split('/')[2]:null;if(id)void services.sessions.resumeSession(id,new Date()).then(async s=>{setSession(s);setAttempt(await services.repository.db.attempts.get(s.id+':'+s.questionSnapshots[s.currentIndex].id)??null)}).catch(e=>setError(e.message));else{setSession(null);setAttempt(null)}},[route,services]);
 const settings=snapshot?.settings[0]??defaultSettings;useEffect(()=>{document.documentElement.dataset.theme=settings.theme;document.documentElement.style.setProperty('--text-scale',String(settings.textScale))},[settings.theme,settings.textScale]);
 const questions=snapshot?.packs.flatMap(p=>p.questions)??[],eligible=questions.filter(q=>classifyQuestion(q,snapshot?.contentTrust.find(t=>t.questionId===q.id&&t.revision===q.revision)??null)==='eligible'),drafts=questions.filter(q=>q.status==='draft').length;
 async function start(mode:SessionMode,count:number,domain='',duration=30,reserved=false){if(!services||!snapshot)return;setError('');const chosen=selectQuestions({questions,trust:snapshot.contentTrust,reviewItems:snapshot.reviews,objectiveStats:Object.entries(calculateProgress(snapshot.attempts,eligible,new Date()).objectives).map(([objectiveId,m])=>({objectiveId,distinctAttempts:m.distinctAttempts,accuracy:m.accuracy??0,confidentWrongCount:m.confidentWrongCount})),previousSessionIds:snapshot.sessions.at(-1)?.questionSnapshots.map(q=>q.id)??[],attemptedIds:snapshot.attempts.filter(a=>a.mode!=='draft-preview').map(a=>a.questionId),requestedCount:count,mode,useReserved:reserved,domainId:domain||undefined,now:new Date(),random:Math.random,releasedIds:snapshot.releasedHoldouts.map(x=>x.questionId)});if(!chosen.questions.length)throw Error(mode==='draft-preview'?'No draft questions are installed yet.':'No reviewed questions match this session. Review draft content first.');if(chosen.questions.length<count&&!window.confirm(`Only ${chosen.questions.length} unique questions match. Start this shorter session?`))return;const s=await services.sessions.createSession({mode,selectedQuestions:chosen.questions,durationMinutes:mode==='timed'?duration:null,releasesReservedIds:chosen.releasesReservedIds});setSession(s);await refresh(services);navigate('/session/'+s.id)}
 async function next(){if(!services||!session)return;const s=await services.sessions.advanceSession(session.id);setSession(s);setAttempt(null);await refresh(services)}
 let view:React.ReactNode=<div className="loading">Opening your study workspace…</div>;
 if(services&&snapshot){const active=snapshot.sessions.find(s=>s.status==='active');if(route.startsWith('/session/')&&session){view=session.status==='submitted'?<Summary session={session}/>:<><div className="session-heading"><a href="#/home">← Pause & return home</a><span>{session.currentIndex+1} / {session.questionSnapshots.length}</span></div><progress value={session.currentIndex+1} max={session.questionSnapshots.length}/>{session.mode==='draft-preview'&&<p className="notice warning">Draft preview · unapproved questions · excluded from scored progress</p>}{session.correctionWarnings.length>0&&<p className="notice warning">Some saved questions have been corrected. This session preserves their earlier wording; affected answers do not count towards current proficiency.</p>}{attempt?<FeedbackView key={attempt.id} attempt={attempt} onNext={next} autoAdvance={settings.autoAdvance} annotations={<Annotations key={attempt.questionId} questionId={attempt.questionId} revision={attempt.questionRevision} initialNote={snapshot.notes.find(n=>n.questionId===attempt.questionId)?.text??''} bookmarked={snapshot.bookmarks.some(b=>b.questionId===attempt.questionId)} onSaveNote={async text=>{await services.repository.saveNote(attempt.questionId,attempt.questionRevision,text);await refresh(services)}} onBookmark={async enabled=>{await services.repository.setBookmark(attempt.questionId,attempt.questionRevision,enabled);await refresh(services)}}/>}/>:<QuestionView key={session.questionSnapshots[session.currentIndex].id} question={session.questionSnapshots[session.currentIndex]} optionOrder={session.optionOrders[session.questionSnapshots[session.currentIndex].id]} initial={session.answers[session.questionSnapshots[session.currentIndex].id]} onDraft={a=>services.sessions.saveDraftAnswer(session.id,session.questionSnapshots[session.currentIndex].id,a)} onSubmit={async(ids,c,ms)=>{const a=await services.sessions.submitLearnAnswer(session.id,session.questionSnapshots[session.currentIndex].id,ids,c,ms);setAttempt(a);await refresh(services)}}/>}</>}
 else if(route.startsWith('/practice'))view=<Practice blueprint={blueprint} initialDomain={new URLSearchParams(route.split('?')[1]).get('domain')??''} available={eligible.length} draftAvailable={questions.length} onStart={start}/>;
 else if(route==='/settings')view=<SettingsView settings={settings} onSave={async s=>{await services.repository.saveSettings(s);await refresh(services)}}/>;
 else if(route.startsWith('/review'))view=<ReviewView snapshot={snapshot} eligible={eligible} onContent={()=>navigate('/review/content')} onStart={async questions=>{const s=await services.sessions.createSession({mode:'learn',selectedQuestions:questions,durationMinutes:null,releasesReservedIds:[]});await refresh(services);navigate('/session/'+s.id)}}/>;
 else if(route==='/progress')view=<ProgressView blueprint={blueprint} progress={calculateProgress(snapshot.attempts,eligible,new Date())}/>;
 else view=<Home blueprint={blueprint} eligible={eligible.length} drafts={drafts} due={snapshot.reviews.filter(r=>Date.parse(r.dueAt)<=Date.now()).length} attemptCount={snapshot.attempts.filter(a=>a.mode!=='draft-preview').length} active={active} examDate={settings.examDate} onReview={()=>navigate('/review/content')} onStart={()=>{if(active)navigate('/session/'+active.id);else void start(eligible.length?'learn':'draft-preview',10).catch(e=>setError(e.message))}}/>;
 }
 return <div className="app-shell"><a className="skip-link" href="#main">Skip to content</a><header className="app-header"><a className="brand" href="#/home"><span className="brand-icon" aria-hidden="true">▦</span><span>Studyapp<small>AZ-104 revision</small></span></a><span className="connection"><i/>{online?'Personal workspace':'Offline'}</span></header><main id="main" className={route.startsWith('/session/')?'main-content session-content':'main-content'}>{error&&<p className="notice error" role="alert">{error}<button className="text-button" onClick={()=>setError('')}>Dismiss</button></p>}{view}</main>{!route.startsWith('/session/')&&<nav className="bottom-nav" aria-label="Main navigation">{['home','practice','review','progress','settings'].map(item=><a key={item} href={'#/'+item} className={route.startsWith('/'+item)?'active':''} aria-current={route.startsWith('/'+item)?'page':undefined}><svg viewBox="0 0 24 24" aria-hidden="true"><path d={icons[item]}/></svg><span>{item[0].toUpperCase()+item.slice(1)}</span></a>)}</nav>}<footer className="app-footer">Original practice · Microsoft Learn sources · Built for steady progress</footer></div>
}
