import legacyMappings from '../../content/coverage/legacy-subskills.json';
import {StudyPlan} from '../features/home/StudyPlan';
import {DeviceChecklist} from '../features/settings/DeviceChecklist';
import {applySourceReport} from '../content/freshness';
import {selectBalancedAssessment,selectCaseStudy} from '../study/assessment';
import {computeCoverage} from '../study/coverage';
import {CoverageView,type LearningResource} from '../features/progress/Coverage';
import resources from '../../content/learning-resources.json';
import {isTimedSession} from '../sessions/types';
import type {PracticeOptions} from '../features/practice/Practice';
import {Exam} from '../features/practice/Exam';
import {useRef} from 'react';import {liveQuery} from 'dexie';import {BackupPanel} from '../features/settings/BackupPanel';import {ContentReview} from '../features/review/ContentReview';import {approveQuestion} from '../content/review';import {registerPwa,type PwaController} from '../pwa/register';
import {useCallback,useEffect,useState} from 'react';import {createAppServices,type AppServices} from './bootstrap';import {currentRoute,navigate} from './navigation';import blueprintData from '../../content/blueprints/az104-2026-04-17.json';import type {Blueprint} from '../content/types';import type {DatabaseSnapshot,Session,SessionMode,Attempt} from '../sessions/types';import {defaultSettings} from '../storage/repository';import {classifyQuestion} from '../content/trust';import {selectQuestions} from '../study/selection';import {Home} from '../features/home/Home';import {Practice} from '../features/practice/Practice';import {QuestionView} from '../features/practice/Question';import {FeedbackView} from '../features/practice/Feedback';import {Summary} from '../features/practice/Summary';import {SettingsView} from '../features/settings/Settings';import {calculateProgress} from '../study/progress';import {ProgressView} from '../features/progress/Progress';import {ReviewView} from '../features/review/Review';import {Annotations} from '../features/review/Annotations';import './app.css';
const blueprint=blueprintData as Blueprint;
const icons:Record<string,string>={home:'M3 10 12 3l9 7v10h-6v-6H9v6H3z',practice:'M5 3h14v18H5z M8 7h8 M8 11h8 M8 15h5',review:'M4 5v5h5 M4 10a8 8 0 1 1 2 8',progress:'M4 20h16 M7 16v-4 M12 16V7 M17 16V3',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2'};
export default function App(){const [services,setServices]=useState<AppServices|null>(null),[snapshot,setSnapshot]=useState<DatabaseSnapshot|null>(null),[route,setRoute]=useState(currentRoute()),[session,setSession]=useState<Session|null>(null),[attempt,setAttempt]=useState<Attempt|null>(null),[error,setError]=useState(''),[online,setOnline]=useState(navigator.onLine);
 const routeRef=useRef(route);routeRef.current=route;const pendingWrites=useRef(new Set<Promise<void>>()),draftFailed=useRef(false);
 function trackDraft(p:Promise<void>){pendingWrites.current.add(p);void p.then(()=>{draftFailed.current=false},()=>{draftFailed.current=true}).finally(()=>pendingWrites.current.delete(p));return p}
 const pwa=useRef<PwaController|null>(null);const [updateAvailable,setUpdateAvailable]=useState(false);
 const refresh=useCallback(async(s:AppServices)=>setSnapshot(await s.repository.getSnapshot()),[]);
 useEffect(()=>{let live=true;void createAppServices().then(async s=>{if(live){setServices(s);await refresh(s)}}).catch(e=>setError('Could not open browser storage: '+e.message));return()=>{live=false}},[refresh]);
 useEffect(()=>{const change=async()=>{const next=currentRoute(),previous=routeRef.current;if(previous.startsWith('/session/')&&next!==previous){while(pendingWrites.current.size)await Promise.allSettled([...pendingWrites.current]);if(draftFailed.current){setError('Your last answer was not saved. Retry saving before leaving this session.');window.location.hash=previous;return}}setRoute(next)},network=()=>setOnline(navigator.onLine);const beforeUnload=(e:BeforeUnloadEvent)=>{if(pendingWrites.current.size||draftFailed.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',beforeUnload);window.addEventListener('hashchange',change);window.addEventListener('online',network);window.addEventListener('offline',network);return()=>{window.removeEventListener('beforeunload',beforeUnload);window.removeEventListener('hashchange',change);window.removeEventListener('online',network);window.removeEventListener('offline',network)}},[]);
 useEffect(()=>{if(!services)return;const id=route.startsWith('/session/')?route.split('/')[2]:null;if(id)void services.sessions.resumeSession(id,new Date()).then(async s=>{setSession(s);setAttempt(await services.repository.db.attempts.get(s.id+':'+s.questionSnapshots[s.currentIndex].id)??null)}).catch(e=>setError(e.message));else{setSession(null);setAttempt(null)}},[route,services]);
 useEffect(()=>{if(!services)return;const sub=liveQuery(()=>services.repository.getSnapshot()).subscribe({next:setSnapshot,error:e=>setError(String(e))});pwa.current=registerPwa({onUpdateAvailable:()=>setUpdateAvailable(true),onError:()=>setError('Offline installation could not be completed. You can keep studying while online.'),isAnySessionActive:async()=>await services.repository.db.sessions.where('status').equals('active').count()>0});return()=>{sub.unsubscribe();pwa.current?.dispose()}},[services]);
 useEffect(()=>{pwa.current?.setSessionActive(snapshot?.sessions.some(s=>s.status==='active')??false)},[snapshot]);
 const settings=snapshot?.settings[0]??defaultSettings;useEffect(()=>{document.documentElement.dataset.theme=settings.theme;document.documentElement.dataset.thumbControls=String(settings.thumbControls??false);document.documentElement.style.setProperty('--text-scale',String(settings.textScale))},[settings.theme,settings.textScale,settings.thumbControls]);
 const questions=snapshot?.packs.flatMap(p=>p.questions)??[],eligible=questions.filter(q=>classifyQuestion(q,snapshot?.contentTrust.find(t=>t.questionId===q.id&&t.revision===q.revision)??null)==='eligible'),drafts=questions.filter(q=>q.status==='draft').length;
 async function start(mode:SessionMode,count:number,domain='',duration=30,reserved=false,options?:PracticeOptions){if(!services||!snapshot)return;setError('');const input={questions:questions.filter(q=>!q.caseStudy&&(!options?.difficulty||q.difficulty===options.difficulty)),trust:snapshot.contentTrust,reviewItems:snapshot.reviews,objectiveStats:Object.entries(calculateProgress(snapshot.attempts,eligible,new Date()).objectives).map(([objectiveId,m])=>({objectiveId,distinctAttempts:m.distinctAttempts,accuracy:m.accuracy??0,confidentWrongCount:m.confidentWrongCount})),previousSessionIds:snapshot.sessions.at(-1)?.questionSnapshots.map(q=>q.id)??[],attemptedIds:snapshot.attempts.filter(a=>a.mode!=='draft-preview').map(a=>a.questionId),requestedCount:count,mode,useReserved:reserved,domainId:domain||undefined,objectiveId:options?.objectiveId,now:new Date(),random:Math.random,releasedIds:snapshot.releasedHoldouts.map(x=>x.questionId)};const caseQuestions=options?.caseStudyId?selectCaseStudy(questions,options.caseStudyId,{trust:snapshot.contentTrust,draft:mode==='draft-preview',useReserved:reserved,releasedIds:input.releasedIds}):null;const chosen=caseQuestions?{questions:caseQuestions,shortages:[],releasesReservedIds:caseQuestions.filter(q=>q.assessmentReserved&&!input.releasedIds.includes(q.id)).map(q=>q.id)}:(mode==='timed'||options?.timed?selectBalancedAssessment(input):selectQuestions(input));if(!chosen.questions.length)throw Error(options?.caseStudyId?'This whole case is unavailable. Review all members or include fresh reserved questions.':mode==='draft-preview'?'No draft questions are installed yet.':'No reviewed questions match this session. Review draft content first.');if(!caseQuestions&&(chosen.questions.length<count||chosen.shortages.length)&&!window.confirm(`Only ${chosen.questions.length} unique questions match. ${chosen.shortages.join('. ')}. Start this ${chosen.questions.length<count?'shorter ':''}session?`))return;const s=await services.sessions.createSession({mode:caseQuestions&&mode==='learn'?'timed':mode,selectedQuestions:chosen.questions,durationMinutes:mode==='timed'||options?.timed||caseQuestions?duration:null,releasesReservedIds:chosen.releasesReservedIds});setSession(s);await refresh(services);navigate('/session/'+s.id)}
 async function next(){if(!services||!session)return;const s=await services.sessions.advanceSession(session.id);setSession(s);setAttempt(null);await refresh(services)}
 let view:React.ReactNode=<div className="loading">Opening your study workspace…</div>;
 if(services&&snapshot){const active=snapshot.sessions.find(s=>s.status==='active');if(route.startsWith('/session/')&&session){view=session.status==='submitted'?<Summary session={session} attempts={snapshot.attempts.filter(a=>a.sessionId===session.id)}/>:<><div className="session-heading"><a href="#/home">← Pause & return home</a><span>{session.currentIndex+1} / {session.questionSnapshots.length}</span></div><progress value={session.currentIndex+1} max={session.questionSnapshots.length}/>{session.mode==='draft-preview'&&<p className="notice warning">Draft preview · unapproved questions · excluded from scored progress</p>}{session.correctionWarnings.length>0&&<p className="notice warning">Some saved questions have been corrected. This session preserves their earlier wording; affected answers do not count towards current proficiency.</p>}{isTimedSession(session)?<Exam session={session} repository={services.repository} service={services.sessions} onDraftTracked={trackDraft} onChanged={setSession} onFinished={async()=>{draftFailed.current=false;setSession(await services.sessions.resumeSession(session.id,new Date()));await refresh(services)}}/>:attempt?<FeedbackView key={attempt.id} attempt={attempt} onNext={next} autoAdvance={settings.autoAdvance} annotations={<Annotations key={attempt.questionId} questionId={attempt.questionId} revision={attempt.questionRevision} initialNote={snapshot.notes.find(n=>n.questionId===attempt.questionId)?.text??''} bookmarked={snapshot.bookmarks.some(b=>b.questionId===attempt.questionId)} onSaveNote={async text=>{await services.repository.saveNote(attempt.questionId,attempt.questionRevision,text);await refresh(services)}} onBookmark={async enabled=>{await services.repository.setBookmark(attempt.questionId,attempt.questionRevision,enabled);await refresh(services)}}/>}/>:<QuestionView key={session.questionSnapshots[session.currentIndex].id} question={session.questionSnapshots[session.currentIndex]} optionOrder={session.optionOrders[session.questionSnapshots[session.currentIndex].id]} initial={session.answers[session.questionSnapshots[session.currentIndex].id]} onSaveQueued={trackDraft} onDraft={a=>services.sessions.saveDraftAnswer(session.id,session.questionSnapshots[session.currentIndex].id,a)} onSubmit={async(ids,c,ms)=>{const a=await services.sessions.submitLearnAnswer(session.id,session.questionSnapshots[session.currentIndex].id,ids,c,ms);draftFailed.current=false;setAttempt(a);await refresh(services)}}/>}</>}
 else if(route.startsWith('/practice'))view=<Practice blueprint={blueprint} initialDomain={new URLSearchParams(route.split('?')[1]).get('domain')??''} initialObjective={new URLSearchParams(route.split('?')[1]).get('objective')??''} available={eligible.length} draftAvailable={questions.length} cases={[...new Map(questions.filter(q=>q.caseStudy).map(q=>[q.caseStudy!.id,{id:q.caseStudy!.id,title:q.caseStudy!.title,domainId:q.domainId,requiresReserve:questions.some(member=>member.caseStudy?.id===q.caseStudy!.id&&member.assessmentReserved&&!snapshot.releasedHoldouts.some(r=>r.questionId===member.id)),previewAvailable:selectCaseStudy(questions,q.caseStudy!.id,{trust:snapshot.contentTrust,draft:true,useReserved:true}).length>0,approvedAvailable:selectCaseStudy(questions,q.caseStudy!.id,{trust:snapshot.contentTrust,draft:false,useReserved:true}).length>0}])).values()]} onStart={start}/>;
 else if(route==='/settings')view=<SettingsView settings={settings} onSave={async s=>{await services.repository.saveSettings(s);await refresh(services)}}><BackupPanel repository={services.repository} onChanged={async()=>{await refresh(services)}}/><DeviceChecklist/></SettingsView>;
 else if(route==='/review/content')view=<ContentReview onApplySourceReport={async report=>{const result=await applySourceReport(services.repository,report,true);await refresh(services);return {quarantined:result.quarantined.length,unavailable:result.unavailable}}} questions={questions} trust={snapshot.contentTrust} onCorrection={async(q,reason)=>{await services.repository.saveNote(q.id,q.revision,'Content correction request: '+reason);await refresh(services)}} onApprove={async q=>{await approveQuestion(services.repository,q.id,q.revision,true);await refresh(services)}}/>;
 else if(route.startsWith('/review'))view=<ReviewView snapshot={snapshot} eligible={eligible} onContent={()=>navigate('/review/content')} onStart={async questions=>{const s=await services.sessions.createSession({mode:'learn',selectedQuestions:questions,durationMinutes:null,releasesReservedIds:[]});await refresh(services);navigate('/session/'+s.id)}}/>;
 else if(route==='/progress/coverage')view=<CoverageView rows={computeCoverage(blueprint,questions,snapshot.contentTrust,snapshot.attempts,legacyMappings)} resources={resources as LearningResource[]} onPractice={objectiveId=>{const d=blueprint.domains.find(d=>d.objectives.some(o=>o.id===objectiveId));navigate('/practice?domain='+d?.id+'&objective='+objectiveId)}}/>;
 else if(route==='/progress')view=<><ProgressView blueprint={blueprint} progress={calculateProgress(snapshot.attempts,eligible,new Date())}/><a className="button secondary" href="#/progress/coverage">Detailed skill coverage</a><section className="card"><h2>What to read next</h2>{blueprint.domains.flatMap(d=>d.objectives).map(o=>{const stat=calculateProgress(snapshot.attempts,eligible,new Date()).objectives[o.id];if(stat.accuracy!==null&&stat.accuracy>=.7&&!stat.confidentWrongCount)return null;const resource=(resources as LearningResource[]).find(r=>r.objectiveId===o.id);return resource?<p key={o.id}><strong>{o.title}</strong><br/><a href={resource.url} target="_blank" rel="noopener noreferrer">{resource.title}</a><small> · {stat.insufficientEvidence?'Build evidence with study and practice':'Revisit this weaker topic'}</small></p>:null})}</section></>;
 else view=<><Home blueprint={blueprint} eligible={eligible.length} drafts={drafts} due={snapshot.reviews.filter(r=>Date.parse(r.dueAt)<=Date.now()).length} attemptCount={snapshot.attempts.filter(a=>a.mode!=='draft-preview').length} active={active} examDate={settings.examDate} onReview={()=>navigate('/review/content')} onStart={()=>{if(active)navigate('/session/'+active.id);else void start(eligible.length?'learn':'draft-preview',10).catch(e=>setError(e.message))}}/><StudyPlan blueprint={blueprint} rows={computeCoverage(blueprint,questions,snapshot.contentTrust,snapshot.attempts,legacyMappings)} resources={resources as LearningResource[]} due={snapshot.reviews.filter(r=>Date.parse(r.dueAt)<=Date.now()).length}/></>;
 }
 return <div className="app-shell"><a className="skip-link" href="#main" onClick={e=>{e.preventDefault();document.getElementById('main')?.focus()}}>Skip to content</a><header className="app-header"><a className="brand" href="#/home"><span className="brand-icon" aria-hidden="true">▦</span><span>Studyapp<small>AZ-104 revision</small></span></a><span className="connection"><i/>{online?'Personal workspace':'Offline'}</span></header><main id="main" tabIndex={-1} className={route.startsWith('/session/')?'main-content session-content':'main-content'}>{updateAvailable&&<p className="notice">An app update is ready. Finish active sessions before updating.<button className="secondary" disabled={snapshot?.sessions.some(s=>s.status==='active')} onClick={()=>void pwa.current?.applyPendingUpdate(false)}>Update app</button></p>}{error&&<p className="notice error" role="alert">{error}<button className="text-button" onClick={()=>setError('')}>Dismiss</button></p>}{view}</main>{!route.startsWith('/session/')&&<nav className="bottom-nav" aria-label="Main navigation">{['home','practice','review','progress','settings'].map(item=><a key={item} href={'#/'+item} className={route.startsWith('/'+item)?'active':''} aria-current={route.startsWith('/'+item)?'page':undefined}><svg viewBox="0 0 24 24" aria-hidden="true"><path d={icons[item]}/></svg><span>{item[0].toUpperCase()+item.slice(1)}</span></a>)}</nav>}<footer className="app-footer">Original practice · Microsoft Learn sources · Built for steady progress</footer></div>
}
