import {describe,it,expect} from 'vitest';
import {question,pack} from '../fixtures';
import type {DatabaseSnapshot,Session,Attempt} from '../../src/sessions/types';
import {deriveHistory,normaliseFilters,historyCSV,historyJSON,csvCell} from '../../src/features/reports/model';
const q=question();
function session(id='s', overrides:Partial<Session>={}):Session{return {id,mode:'learn',questionSnapshots:[q],optionOrders:{q1:['a','b']},answers:{q1:{selectedOptionIds:['a'],confidence:'confident',responseMs:1500}},flags:[],currentIndex:0,startedAt:'2026-10-07T12:00:00Z',deadlineAt:null,status:'submitted',submittedAt:'2026-10-07T12:01:00Z',correctionWarnings:[],...overrides}}
function snapshot(sessions=[session()]):DatabaseSnapshot{return {sessions,packs:[pack()],attempts:[{id:'a1',sessionId:'s',questionId:'q1',questionRevision:1,questionSnapshot:q,selectedOptionIds:['a'],confidence:'confident',correct:true,responseMs:1500,submittedAt:'2026-10-07T12:01:00Z',mode:'learn'} as Attempt],contentTrust:[],sourceChecks:[],settings:[],reviews:[],bookmarks:[],notes:[],releasedHoldouts:[]}}
describe('session history',()=>{
 it('filters session dates modes and domains, with real answered denominators and measured time',()=>{const s=snapshot([session('s',{questionSnapshots:[q,question({id:'q2',domainId:'compute',type:'ordering'})]})]);const rows=deriveHistory(s,{domain:'identity'});expect(rows[0]).toMatchObject({answered:1,total:1,responseMs:1500,formats:{single:1,multiple:0,ordering:0,matching:0}});expect(deriveHistory(s,{from:'2026-10-08'})).toEqual([]);expect(deriveHistory(s,{mode:'timed'})).toEqual([])});
 it('counts one complete answer among five timed attempts and keeps skipped details',()=>{const questions=Array.from({length:5},(_,i)=>question({id:`q${i+1}`}));const s=snapshot([session('s',{mode:'timed',deadlineAt:'2026-10-07T12:30:00Z',questionSnapshots:questions,answers:{}})]);s.attempts=questions.map((questionSnapshot,i)=>({...s.attempts[0],id:`a${i}`,questionId:questionSnapshot.id,questionSnapshot,selectedOptionIds:i===0?['a']:[],responseMs:i===0?1500:4000,mode:'timed'}));const row=deriveHistory(s,{})[0];expect(row).toMatchObject({answered:1,total:5,responseMs:1500,formats:{single:1,multiple:0,ordering:0,matching:0}});expect(row.details).toHaveLength(5);expect(row.details[1].answer?.selectedOptionIds).toEqual([])});
 it('does not count empty or incomplete active saved drafts as answers or format exposure',()=>{const multiple=question({id:'q2',type:'multiple',requiredSelections:2});const s=snapshot([session('s',{status:'active',questionSnapshots:[q,multiple],answers:{q1:{selectedOptionIds:[],confidence:'unsure',responseMs:2000},q2:{selectedOptionIds:['a'],confidence:'unsure',responseMs:3000}}})]);s.attempts=[];expect(deriveHistory(s,{})[0]).toMatchObject({answered:0,total:2,responseMs:0,formats:{single:0,multiple:0,ordering:0,matching:0}})});
 it('keeps historical snapshots and marks stale and invalidated trust ineligible',()=>{const s=snapshot();s.packs=[pack([question({revision:2,prompt:'Replacement'})])];s.contentTrust=[{questionId:'q1',revision:1,humanReviewedAt:'2026-10-01',reviewer:'Person',sourceCheckedAt:'2026-10-01',invalidatedAt:'2026-10-08'}];const detail=deriveHistory(s,{})[0].details[0];expect(detail.question.prompt).toBe('Test prompt');expect(detail.stale).toBe(true);expect(detail.eligibility).toBe('invalidated')});
 it('withholds globally across revisions while an assessment is active, including exports and saved attempts',()=>{const s=snapshot([session(),session('active',{status:'active',feedbackAtEnd:true,questionSnapshots:[question({revision:2})]})]);const rows=deriveHistory(s,{});expect(rows.every(row=>row.details.length===0)).toBe(true);for(const output of [historyJSON(rows),historyCSV(rows)])for(const secret of ['Test prompt','Reason A','selectedOptionIds','correctOptionIds','Synthetic scenario'])expect(output).not.toContain(secret);expect(rows[0].responseMs).toBe(0)});
 it('does not expose fresh reserve snapshots and only exports filtered records',()=>{const s=snapshot([session('reserve',{questionSnapshots:[question({assessmentReserved:true,prompt:'Reserve secret'})],answers:{}})]);s.attempts=[];const rows=deriveHistory(s,{});expect(historyJSON(rows)).not.toContain('Reserve secret');expect(rows[0].details).toEqual([]);expect(historyCSV(deriveHistory(s,{mode:'timed'}))).not.toContain('reserve')});
 it('rejects invalid and reversed dates and unrecognised mode/domain shapes',()=>{expect(normaliseFilters({from:'2026-02-30',to:42,mode:'evil',domain:[]})).toEqual({from:'',to:'',mode:'',domain:''});expect(deriveHistory(snapshot(),{from:'2026-10-08',to:'2026-10-01'})).toEqual([])});
 it('distinguishes currently eligible attempts from draft preview even after review',()=>{const s=snapshot();s.packs=[pack([question({status:'reviewed'})])];s.contentTrust=[{questionId:'q1',revision:1,humanReviewedAt:'2026-10-01',reviewer:'Person',sourceCheckedAt:'2026-10-01',invalidatedAt:null}];expect(deriveHistory(s,{})[0].details[0].currentEligibleAttempt).toBe(true);s.sessions[0].mode='draft-preview';expect(deriveHistory(s,{})[0].details[0].currentEligibleAttempt).toBe(false)});
 it('defuses every spreadsheet formula prefix including control-prefixed cells',()=>{for(const value of ['=1','+1','-1','@SUM(A1)','\t=1','\r=1','\n=1','\u0000=1'])expect(csvCell(value).startsWith("\"'")).toBe(true)});
 it('escapes spreadsheet formulas and commas or quotes in exported fields',()=>{const rows=deriveHistory(snapshot([session(' =HYPERLINK("x")')]),{});expect(historyCSV(rows)).toContain('"\' =HYPERLINK(""x"")"');expect(JSON.parse(historyJSON(rows)).sessions).toHaveLength(1)});
});
