import {prepareBackup,readBackupFile} from '../../backup/compression';
import {useState} from 'react';
import type {StudyRepository} from '../../storage/repository';
import type {BackupV1} from '../../backup/types';
import {validateBackup} from '../../backup/validate';
import {restoreBackup,deletePersonalData} from '../../backup/restore';
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function BackupPanel({repository,onChanged}:{repository:StudyRepository;onChanged:()=>Promise<void>}){
 const [pending,setPending]=useState<{backup:BackupV1;recovery:Blob;compressedImport:boolean}|null>(null),[deleting,setDeleting]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[recoveryDownloaded,setRecoveryDownloaded]=useState(false);
 async function perform(action:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await action()}catch(e){setError(e instanceof Error?e.message:'Backup operation failed.')}finally{setBusy(false)}}
 return <section aria-label="Backup and local data"><h2>Backup and local data</h2><p>Your progress belongs to one browser profile. It does not automatically sync between devices. Clearing browser data can remove it. Export a backup to keep a copy; files are processed locally in your browser. Large histories are compressed automatically. JSON and gzip files are limited to 10 MiB; compressed files can contain up to 64 MiB of expanded history.</p>
 <button disabled={busy} onClick={()=>void perform(async()=>{const prepared=await prepareBackup(await repository.getSnapshot());download(prepared.blob,prepared.compressed?'az104-backup.json.gz':'az104-backup.json');setMessage(prepared.compressed?'Compressed backup prepared for download.':'Backup prepared for download.');})}>Export backup</button>
 <label>Import backup<input type="file" accept="application/json,application/gzip,.json,.gz" disabled={busy} onChange={event=>{const file=event.target.files?.[0];event.target.value='';setPending(null);setRecoveryDownloaded(false);if(!file)return;void perform(async()=>{const compressed=file.name.toLowerCase().endsWith('.gz')||file.type==='application/gzip';const read=await readBackupFile(file,compressed);let input:unknown;try{input=JSON.parse(read.text)}catch{throw Error('Could not read valid JSON from this backup.')}const validation=validateBackup(input,read.byteLength,compressed);if(!validation.valid||!validation.backup)throw Error(validation.issues.map(i=>`${i.path}: ${i.message}`).join('\n'));const recovery=await prepareBackup(await repository.getSnapshot());setDeleting(false);setPending({backup:validation.backup,recovery:recovery.blob,compressedImport:compressed})})}}/></label>
 {pending&&<div role="group" aria-label="Confirm backup replacement"><p>Restore replaces all current local data. Imported content must be reviewed again before normal study. Historical attempts remain readable. Download the recovery backup first so you can undo this replacement.</p><button disabled={busy} onClick={()=>void perform(async()=>{download(pending.recovery,pending.recovery.type==='application/gzip'?'az104-recovery.json.gz':'az104-recovery.json');setRecoveryDownloaded(true)})}>Download recovery backup</button><button disabled={busy||!recoveryDownloaded} onClick={()=>void perform(async()=>{await restoreBackup(repository,pending.backup,{replaceConfirmed:true,recoveryBackup:pending.recovery,compressedImport:pending.compressedImport});setPending(null);await onChanged();setMessage('Backup restored. Imported content is quarantined for review.');})}>Confirm replace</button><button disabled={busy} onClick={()=>setPending(null)}>Cancel</button></div>}
 <button disabled={busy} onClick={()=>{setPending(null);setDeleting(true)}}>Delete local data</button>
 {deleting&&<div role="group" aria-label="Confirm local data deletion"><p>Delete all progress, sessions, personal notes, bookmarks, settings and local content approvals? Bundled draft packs can be installed again.</p><button disabled={busy} onClick={()=>void perform(async()=>{await deletePersonalData(repository,true);setDeleting(false);await onChanged();setMessage('Local data deleted.');})}>Confirm delete</button><button disabled={busy} onClick={()=>setDeleting(false)}>Cancel</button></div>}
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</section>
}
