import {prepareBackup,readBackupFile} from '../../backup/compression';
import {useEffect,useState} from 'react';
import type {StudyRepository} from '../../storage/repository';
import type {BackupV1} from '../../backup/types';
import {validateBackup} from '../../backup/validate';
import {restoreBackup,deletePersonalData} from '../../backup/restore';
import {inspectBackup,backupReminder,personalWork} from '../../backup/inspection';
import {readWorkspace,writeWorkspace} from '../../storage/workspace';
import type {DatabaseSnapshot} from '../../sessions/types';
import {normaliseComfortBackup,normaliseComfortPreferences} from '../comfort/preferences';
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function BackupPanel({repository,onChanged,snapshot}:{repository:StudyRepository;onChanged:()=>Promise<void>;snapshot?:DatabaseSnapshot}){
 const [pending,setPending]=useState<{backup:BackupV1;recovery:Blob;compressedImport:boolean}|null>(null),[deleting,setDeleting]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[recoveryDownloaded,setRecoveryDownloaded]=useState(false);
 const [lastExport,setLastExport]=useState<string|null>(null),[exportFingerprint,setExportFingerprint]=useState<string|null>(null),[reminderDays,setReminderDays]=useState(7);
 useEffect(()=>{let live=true;void Promise.all([readWorkspace<unknown>(repository,'comfort:backup',{}),readWorkspace<unknown>(repository,'comfort:preferences',{})]).then(([value,preferences])=>{if(live){const backup=normaliseComfortBackup(value);setLastExport(backup.lastExportAt);setExportFingerprint(backup.workFingerprint);setReminderDays(normaliseComfortPreferences(preferences).reminderDays)}}).catch(()=>{if(live)setError('Backup reminder history could not be read.')});return()=>{live=false}},[repository,snapshot]);
 const reminder=backupReminder(lastExport,reminderDays,new Date(),snapshot?personalWork(snapshot):undefined,exportFingerprint),preview=pending?inspectBackup(pending.backup):null;
 async function perform(action:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await action()}catch(e){setError(e instanceof Error?e.message:'Backup operation failed.')}finally{setBusy(false)}}
 return <section aria-label="Backup and local data"><h2>Backup and local data</h2><p>Your progress belongs to one browser profile. It does not automatically sync between devices. Clearing browser data can remove it. Export a backup to keep a copy; files are processed locally in your browser. Large histories are compressed automatically. JSON and gzip files are limited to 10 MiB; compressed files can contain up to 64 MiB of expanded history.</p>
 {reminder&&<p className="notice">{reminder}</p>}{lastExport&&<p className="fine-print">Last export initiated: {lastExport.slice(0,10)}. This records an export request, not proof that a file was saved.</p>}
 <button disabled={busy} onClick={()=>void perform(async()=>{const captured=await repository.getSnapshot(),date=new Date().toISOString(),work=personalWork(captured),metadata={lastExportAt:date,workFingerprint:work.fingerprint};const prepared=await prepareBackup({...captured,workspace:[...(captured.workspace??[]).filter(row=>row.id!=='comfort:backup'),{id:'comfort:backup',version:1,value:metadata,updatedAt:date}]});download(prepared.blob,prepared.compressed?'az104-backup.json.gz':'az104-backup.json');await writeWorkspace(repository,'comfort:backup',metadata);setLastExport(date);setExportFingerprint(work.fingerprint);setMessage((prepared.compressed?'Compressed backup prepared for download.':'Backup prepared for download.')+' Check that the file reached your device’s files before relying on it.');})}>Export backup</button>
 <label>Import backup<input type="file" accept="application/json,application/gzip,.json,.gz" disabled={busy} onChange={event=>{const file=event.target.files?.[0];event.target.value='';setPending(null);setRecoveryDownloaded(false);if(!file)return;void perform(async()=>{const compressed=file.name.toLowerCase().endsWith('.gz')||file.type==='application/gzip';const read=await readBackupFile(file,compressed);let input:unknown;try{input=JSON.parse(read.text)}catch{throw Error('Could not read valid JSON from this backup.')}const validation=validateBackup(input,read.byteLength,compressed);if(!validation.valid||!validation.backup)throw Error(validation.issues.map(i=>`${i.path}: ${i.message}`).join('\n'));const recovery=await prepareBackup(await repository.getSnapshot());setDeleting(false);setPending({backup:validation.backup,recovery:recovery.blob,compressedImport:compressed})})}}/></label>
 {preview&&<section aria-label="Backup inspection"><h3>Backup inspection</h3><p>Schema version {preview.schemaVersion} · exported {preview.exportedAt.slice(0,10)}</p><p>{preview.packs} packs · {preview.questions} questions · {preview.sessions} sessions ({preview.activeSessions} active) · {preview.attempts} attempts · {preview.notes} notes · {preview.bookmarks} bookmarks · {preview.reviews} review items · {preview.workspace} personal workspace records</p>{preview.warnings.map(warning=><p key={warning}>{warning}</p>)}<p>Inspection validates this file without replacing local data.</p></section>}
 {pending&&<div role="group" aria-label="Confirm backup replacement"><p>Restore replaces all current local data. Imported content must be reviewed again before normal study. Historical attempts remain readable. Download the recovery backup first so you can undo this replacement.</p><button disabled={busy} onClick={()=>void perform(async()=>{download(pending.recovery,pending.recovery.type==='application/gzip'?'az104-recovery.json.gz':'az104-recovery.json');setRecoveryDownloaded(true)})}>Download recovery backup</button><button disabled={busy||!recoveryDownloaded} onClick={()=>void perform(async()=>{await restoreBackup(repository,pending.backup,{replaceConfirmed:true,recoveryBackup:pending.recovery,compressedImport:pending.compressedImport});setPending(null);const restored=normaliseComfortBackup(await readWorkspace<unknown>(repository,'comfort:backup',{}));setLastExport(restored.lastExportAt);setExportFingerprint(restored.workFingerprint);await onChanged();setMessage('Backup restored. Imported content is quarantined for review.');})}>Confirm replace</button><button disabled={busy} onClick={()=>setPending(null)}>Cancel</button></div>}
 <button disabled={busy} onClick={()=>{setPending(null);setDeleting(true)}}>Delete local data</button>
 {deleting&&<div role="group" aria-label="Confirm local data deletion"><p>Delete all progress, sessions, personal notes, bookmarks, settings and local content approvals? Bundled draft packs can be installed again.</p><button disabled={busy} onClick={()=>void perform(async()=>{await deletePersonalData(repository,true);setDeleting(false);await onChanged();setMessage('Local data deleted.');})}>Confirm delete</button><button disabled={busy} onClick={()=>setDeleting(false)}>Cancel</button></div>}
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</section>
}
