import {useState} from 'react';
import './device-checklist.css';
const storageKey='az104-physical-device-checklist-v1';
const checks=[{id:'install',text:'I installed Studyapp on my actual phone and opened it from the home screen.'},{id:'offline',text:'I turned off Wi-Fi and mobile data, reopened Studyapp, and answered a practice question offline.'},{id:'storage',text:'I closed and reopened the installed app and confirmed that my saved answer and preferences remained.'},{id:'backup',text:'I exported a backup to my phone’s files, restored it, and confirmed my saved progress.'},{id:'accessibility',text:'I checked enlarged text, touch controls and my phone’s screen reader on a real study session.'}] as const;
interface SavedChecks {checked:Record<string,string>}
function readChecks():SavedChecks{try{const value=JSON.parse(localStorage.getItem(storageKey)??'null') as SavedChecks|null;return value&&typeof value.checked==='object'&&value.checked!==null?{checked:Object.fromEntries(checks.flatMap(check=>typeof value.checked[check.id]==='string'?[[check.id,value.checked[check.id]]]:[]))}:{checked:{}}}catch{return {checked:{}}}}
export function DeviceChecklist(){const [saved,setSaved]=useState(readChecks),[error,setError]=useState('');function save(next:SavedChecks){try{localStorage.setItem(storageKey,JSON.stringify(next));setSaved(next);setError('')}catch{setError('Device checks could not be saved. Browser storage may be unavailable.')}}const completed=checks.filter(check=>!!saved.checked[check.id]).length;
 return <section className="card device-checklist" aria-labelledby="device-checklist-title"><h2 id="device-checklist-title">Your real-phone checks</h2><p>Automated Chromium and WebKit checks use browser emulation. They cannot confirm installation, storage or accessibility on your actual phone. Mark each item only after you perform it yourself.</p><p role="status">{completed===0?'No physical-device checks recorded.':`${completed} of ${checks.length} physical-device checks recorded by you.`}</p><fieldset><legend>Checks you performed on your actual device</legend>{checks.map(check=><label key={check.id}><input type="checkbox" checked={!!saved.checked[check.id]} onChange={event=>{const checked={...saved.checked};if(event.target.checked)checked[check.id]=new Date().toISOString();else delete checked[check.id];save({checked})}}/><span>{check.text}{saved.checked[check.id]&&<small>Recorded {saved.checked[check.id].slice(0,10)}</small>}</span></label>)}</fieldset>{error&&<p role="alert">{error}</p>}<button type="button" className="secondary" onClick={()=>save({checked:{}})} disabled={!completed}>Reset device checks</button><p className="fine-print">This checklist is stored only in this browser and is separate from your progress backup. Keep your backup before clearing browser data.</p></section>;
}
