import {useEffect,useRef,useState} from 'react';
import type {StudyRepository} from '../../storage/repository';
import type {DatabaseSnapshot} from '../../sessions/types';
import {workspaceValue,writeWorkspace} from '../../storage/workspace';
import {deviceChecks,emptyDeviceReport,recordDeviceCheck,normaliseDeviceReport,type DeviceReport,type DeviceResult} from '../comfort/device-report';
import './device-checklist.css';
import '../comfort/comfort.css';
const key='device:report',localKey='az104-device-report-v2';
function localReport():DeviceReport{try{const current=JSON.parse(localStorage.getItem(localKey)??'null');if(current&&typeof current==='object'&&current.checks)return normaliseDeviceReport(current);const legacy=JSON.parse(localStorage.getItem('az104-physical-device-checklist-v1')??'null');let report=emptyDeviceReport();for(const c of deviceChecks){const date=legacy?.checked?.[c.id];if(typeof date==='string'&&Number.isFinite(Date.parse(date)))report=recordDeviceCheck(report,c.id,'passed',date,'Migrated user assertion from the earlier checklist.')}return report}catch{return emptyDeviceReport()}}
export function DeviceChecklist({repository,snapshot}:{repository?:StudyRepository;snapshot?:DatabaseSnapshot}={}){
 const [saved,setSaved]=useState<DeviceReport>(()=>normaliseDeviceReport(snapshot?workspaceValue(snapshot,key,localReport()):localReport())),[error,setError]=useState('');const pending=useRef(Promise.resolve()),pendingCount=useRef(0),localWrite=useRef<string|null>(null);const [writeEpoch,setWriteEpoch]=useState(0);const stored=snapshot?.workspace?.find(row=>row.id===key)?.value;
 useEffect(()=>{if(!snapshot||pendingCount.current)return;const next=normaliseDeviceReport(stored??localReport()),serialized=JSON.stringify(next);if(localWrite.current){if(serialized!==localWrite.current)return;localWrite.current=null;}setSaved(previous=>serialized===JSON.stringify(previous)?previous:next)},[stored,snapshot,writeEpoch]);
 useEffect(()=>{if(!repository||!snapshot||stored)return;const legacy=localReport();if(Object.keys(legacy.checks).length||legacy.model||legacy.os||legacy.browser||legacy.testedOn)void writeWorkspace(repository,key,legacy as unknown as Record<string,unknown>).then(()=>{localStorage.removeItem(localKey);localStorage.removeItem('az104-physical-device-checklist-v1')}).catch(()=>setError('Earlier device checks could not be copied into your backup.'))},[repository,stored,snapshot]);
 function save(next:DeviceReport){setSaved(next);setError('');if(repository){localWrite.current=JSON.stringify(normaliseDeviceReport(next));pendingCount.current++;pending.current=pending.current.catch(()=>{}).then(()=>writeWorkspace(repository,key,next as unknown as Record<string,unknown>));void pending.current.catch(()=>setError('Device checks could not be saved. Retry your last change.')).finally(()=>{pendingCount.current--;setWriteEpoch(epoch=>epoch+1)})}else try{localStorage.setItem(localKey,JSON.stringify(next))}catch{setError('Device checks could not be saved. Browser storage may be unavailable.')}}
 const passed=deviceChecks.filter(check=>saved.checks[check.id]?.status==='passed').length,failed=deviceChecks.filter(check=>saved.checks[check.id]?.status==='failed').length;
 return <section className="card device-checklist" aria-labelledby="device-checklist-title"><h2 id="device-checklist-title">Your real-phone checks</h2><p>Automated Chromium and WebKit checks use browser emulation. They cannot confirm installation, storage or accessibility on your actual phone. Record results only after you perform each check yourself. Metadata and results below are user assertions.</p><p role="status">{passed} of {deviceChecks.length} physical-device checks passed, recorded by you. {failed} failed; {deviceChecks.length-passed-failed} not tested.</p><fieldset><legend>Your test device</legend>{([['model','Device model'],['os','OS and version'],['browser','Browser and version'],['testedOn','Date tested']] as const).map(([field,label])=><label key={field}>{label}<input type={field==='testedOn'?'date':'text'} maxLength={200} value={saved[field]} onChange={e=>save({...saved,[field]:e.target.value})}/></label>)}</fieldset><fieldset><legend>Checks you performed on your actual device</legend>{deviceChecks.map(check=><div key={check.id}><p>{check.text}</p><label>{check.title} result<select value={saved.checks[check.id]?.status??'not-tested'} onChange={e=>save(recordDeviceCheck(saved,check.id,e.target.value as DeviceResult,new Date().toISOString(),saved.checks[check.id]?.notes??''))}><option value="not-tested">Not tested</option><option value="passed">Passed — I performed this check</option><option value="failed">Failed — I performed this check</option></select></label>{saved.checks[check.id]&&<><label>{check.title} notes<textarea maxLength={2000} value={saved.checks[check.id].notes} onChange={e=>save({...saved,checks:{...saved.checks,[check.id]:{...saved.checks[check.id],notes:e.target.value}}})}/></label><small>Recorded {saved.checks[check.id].recordedAt.slice(0,10)} by you.</small></>}</div>)}</fieldset>{error&&<p role="alert">{error}</p>}<button type="button" className="secondary" onClick={()=>save(emptyDeviceReport())} disabled={!Object.keys(saved.checks).length&&!saved.model&&!saved.os&&!saved.browser&&!saved.testedOn}>Reset device checks</button><p className="fine-print">{repository?'This personal report is included in your progress backup.':'This checklist is stored in this browser.'} A report never supplies content approval or automated proof of physical-device acceptance.</p></section>
}
