import {useEffect,useState} from 'react';
import type {StudyRepository} from '../../storage/repository';
import type {DatabaseSnapshot} from '../../sessions/types';
import {writeWorkspace} from '../../storage/workspace';
import {assessmentProtectedIds} from '../evidence/review';
import audit from '../../../content/audits/full-bank-review.json';
import {evidenceHealth,exportEvidenceGaps,normaliseHealthFilters} from './health';
function restoredFilters(snapshot:DatabaseSnapshot){const rows=Array.isArray(snapshot.workspace)?snapshot.workspace:[];const row=rows.find(row=>row&&typeof row==='object'&&row.id==='evidence:health');return normaliseHealthFilters(row?.value)}
export function EvidenceHealth({repository,snapshot}:{repository:StudyRepository;snapshot:DatabaseSnapshot}){
 const [filters,setFilters]=useState(()=>restoredFilters(snapshot)),[message,setMessage]=useState('');
 useEffect(()=>setFilters(restoredFilters(snapshot)),[snapshot]);
 const protectedIds=assessmentProtectedIds(snapshot),questions=snapshot.packs.flatMap(p=>p.questions).filter(q=>!protectedIds.has(q.id));
 const rows=evidenceHealth(questions,audit.questions,audit.quoteSections),filtered=rows.filter(r=>(filters.domain==='all'||r.domain===filters.domain)&&(filters.objective==='all'||r.objective===filters.objective)&&(!filters.onlyGaps||r.gaps.length>0));
 const gaps=rows.reduce((n,r)=>n+r.gaps.length,0),options=rows.reduce((n,r)=>n+r.optionCount,0);
 async function save(){try{await writeWorkspace(repository,'evidence:health',{...filters});setMessage('Evidence filters saved on this browser.')}catch{setMessage('Evidence filters could not be saved. Your current selection remains available.')}}
 function download(){const url=URL.createObjectURL(new Blob([exportEvidenceGaps(filtered)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='az104-evidence-gaps.json';a.click();URL.revokeObjectURL(url)}
 return <div><div className="page-title"><span className="eyebrow">Revision-specific quotation coverage</span><h1>Evidence health</h1><p>{rows.length} visible revisions · {options-gaps}/{options} options have bound exact quotations · {gaps} quotation gaps.</p><p>All supplied questions remain draft and human-review-pending. An exact quotation or verified retrieval hash does not establish factual correctness or grant approval.</p></div>
 {protectedIds.size>0&&<p className="notice">Active assessment questions are withheld from evidence health and exports.</p>}
 <section className="card"><h2>Unresolved factual review and quotation gaps</h2><p>{rows.length} revisions still require human factual review, including revisions with complete quotation coverage. Closed excerpt gaps are separate from unresolved semantic concerns in the evidence workbench.</p><p>Missing audit means there is no recorded review for that revision. Stale audit means the available audit belongs to another revision. Unsupported bindings are rejected when a quote, option, revision, official URL or integrity metadata does not match.</p><label>Evidence domain<select value={filters.domain} onChange={e=>setFilters({...filters,domain:e.target.value})}><option value="all">All domains</option>{[...new Set(rows.map(r=>r.domain))].sort().map(d=><option key={d}>{d}</option>)}</select></label><label>Evidence objective<select value={filters.objective} onChange={e=>setFilters({...filters,objective:e.target.value})}><option value="all">All objectives</option>{[...new Set(rows.map(r=>r.objective))].sort().map(o=><option key={o}>{o}</option>)}</select></label><label><input type="checkbox" checked={filters.onlyGaps} onChange={e=>setFilters({...filters,onlyGaps:e.target.checked})}/> Only quotation gaps</label><button className="secondary" onClick={()=>void save()}>Save evidence filters</button><button className="secondary" onClick={download}>Export nonauthoritative evidence-gap report</button><p role="status">{message}</p></section>
 <section className="card"><h2>Review by domain</h2><ul>{[...new Set(rows.map(r=>r.domain))].sort().map(domain=>{const group=rows.filter(r=>r.domain===domain);return <li key={domain}>{domain}: {group.length} human-review-pending revisions; {group.reduce((n,r)=>n+r.gaps.length,0)} quotation gaps</li>})}</ul><h2>Review by objective</h2><ul>{[...new Set(filtered.map(r=>r.objective))].sort().map(objective=>{const group=filtered.filter(r=>r.objective===objective);return <li key={objective}>{objective}: {group.length} human-review-pending revisions; {group.reduce((n,r)=>n+r.gaps.length,0)} quotation gaps</li>})}</ul></section>
 <section className="card"><h2>Revision evidence details</h2>{rows.length===0?<p>No visible installed questions. Install a pack, or finish the active assessment to inspect withheld evidence.</p>:filtered.length===0?<p>No revisions match these filters. Complete quotation coverage still leaves factual review pending.</p>:filtered.map(row=><details key={`${row.questionId}:${row.revision}`}><summary>{row.questionId} · revision {row.revision} · {row.status} · human-review-pending</summary><p>{row.coveredOptions}/{row.optionCount} options with supported quotation bindings. {row.domain} / {row.objective}</p>{row.gaps.length===0?<p>No exact quotation gaps detected. Review source entailment, negative claims and assumptions before approval.</p>:row.gaps.map(gap=><div key={gap.optionId}><p>Option {gap.optionId}: {gap.reason}</p>{gap.links.length?<ul>{gap.links.map(url=><li key={url}><a href={url} target="_blank" rel="noreferrer">Read official Microsoft Learn source</a></li>)}</ul>:<p>No usable official reading link recorded; retrieve an official source before review.</p>}</div>)}</details>)}</section></div>
}
