import type {Question} from '../../content/types';
export interface HealthFilters{domain:string;objective:string;onlyGaps:boolean}
export interface HealthRow{questionId:string;revision:number;domain:string;objective:string;status:'missing-audit'|'stale-audit'|'covered'|'quote-gaps';optionCount:number;coveredOptions:number;gaps:{optionId:string;reason:string;links:string[]}[];humanReviewPending:true}
const record=(value:unknown):Record<string,unknown>|null=>value!==null&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:null;
export function normaliseHealthFilters(value:unknown):HealthFilters{const r=record(value);const text=(v:unknown)=>typeof v==='string'&&v.length<=150&&/^[a-zA-Z0-9._-]+$/.test(v)?v:'all';return {domain:text(r?.domain),objective:text(r?.objective),onlyGaps:r?.onlyGaps===true}}
export function officialUrl(value:unknown):value is string{if(typeof value!=='string')return false;try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='learn.microsoft.com'&&!u.username&&!u.password}catch{return false}}
export function validQuoteBinding(q:Question,optionId:string,value:unknown,sections:Record<string,string>={}):boolean{const e=record(value);if(!e)return false;const text=typeof e.sectionHash==='string'&&Object.hasOwn(sections,e.sectionHash)?sections[e.sectionHash]:null;return e.questionId===q.id&&e.questionRevision===q.revision&&e.optionId===optionId&&q.options.some(o=>o.id===optionId&&o.text===e.optionText&&o.explanation===e.optionClaim)&&officialUrl(e.url)&&e.htmlHashVerified===true&&typeof e.contentHash==='string'&&/^[a-f0-9]{64}$/.test(e.contentHash)&&typeof e.sectionHash==='string'&&/^[a-f0-9]{64}$/.test(e.sectionHash)&&typeof e.excerpt==='string'&&e.excerpt.length>20&&typeof text==='string'&&(!('sectionText' in e)||e.sectionText===text)&&text.includes(e.excerpt)&&e.bindingStatus!=='unsupported-exact-quote'}
export function evidenceHealth(questions:Question[],audits:unknown,sections:Record<string,string>={}):HealthRow[]{const all=Array.isArray(audits)?audits.map(record).filter(r=>r!==null):[];return questions.map(q=>{const matching=all.filter(a=>a.questionId===q.id),audit=matching.find(a=>a.revision===q.revision),options=Array.isArray(audit?.optionAudits)?audit.optionAudits.map(record).filter(r=>r!==null):[];const gaps=q.options.flatMap(o=>{const option=options.find(a=>a.optionId===o.id),quotes=Array.isArray(option?.evidence)?option.evidence:[];if(quotes.some(e=>validQuoteBinding(q,o.id,e,sections)))return [];return [{optionId:o.id,reason:!audit?(matching.length?'Audit belongs to a different question revision.':'This revision has no audit.'):!quotes.length?'No exact official excerpt recorded.':'Recorded quotations have unsupported revision, option or provenance bindings.',links:[...new Set([...quotes.map(e=>record(e)?.url),...q.references.filter(r=>o.referenceIds.includes(r.id)).map(r=>r.url)].filter(officialUrl))]}]});return {questionId:q.id,revision:q.revision,domain:q.domainId,objective:q.objectiveId,status:!audit?(matching.length?'stale-audit':'missing-audit'):gaps.length?'quote-gaps':'covered',optionCount:q.options.length,coveredOptions:q.options.length-gaps.length,gaps,humanReviewPending:true}})}
export function exportEvidenceGaps(rows:HealthRow[]):string{return JSON.stringify({schemaVersion:1,kind:'nonauthoritative-evidence-gap-report',exportedAt:new Date().toISOString(),authoritative:false,humanApprovalGranted:false,notice:'Quotation coverage is not factual correctness. Supplied drafts still require human factual review. Active assessment questions are withheld.',questions:rows},null,2)}
