import {useState} from 'react';
import type {DatabaseSnapshot} from '../../sessions/types';
import type {StudyRepository} from '../../storage/repository';
import {workspaceValue,writeWorkspace} from '../../storage/workspace';
import {deriveAnalytics,reserveSummary,compareAssessments,assessmentDepthGaps} from '../../study/analytics';
import {DEFAULT_SELECTION_WEIGHTS,normaliseSelectionWeights,type SelectionWeights} from '../../study/selection-explanation';
import './analytics.css';
const percentage=(value:number|null)=>value===null?'No scored evidence':`${Math.round(value*100)}%`;
const mistakeCategories={'knowledge-gap':'Knowledge gap','missed-condition':'Missed condition','confused-service':'Confused service',guessed:'Guessed',other:'Other'};
type MistakeCategory=keyof typeof mistakeCategories;
interface JournalEntry {reason:string;nextStep:string;resolved:boolean;category:MistakeCategory}
interface Journal {entries:Record<string,JournalEntry>}
function journalValue(value:unknown):Journal {if(!value||typeof value!=='object'||!('entries' in value)||!value.entries||typeof value.entries!=='object'||Array.isArray(value.entries))return {entries:{}};const entries=Object.fromEntries(Object.entries(value.entries).filter(([,entry])=>entry&&typeof entry==='object'&&typeof entry.reason==='string'&&typeof entry.nextStep==='string'&&typeof entry.resolved==='boolean').map(([id,entry])=>[id,{reason:entry.reason.slice(0,4000),nextStep:entry.nextStep.slice(0,4000),resolved:entry.resolved,category:typeof entry.category==='string'&&Object.hasOwn(mistakeCategories,entry.category)?entry.category as MistakeCategory:'other' as const}]));return {entries};}
export function Analytics({repository,snapshot}:{repository:StudyRepository;snapshot:DatabaseSnapshot}){
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[compareFrom,setCompareFrom]=useState(''),[compareTo,setCompareTo]=useState(''),[weights,setWeights]=useState<SelectionWeights>(()=>normaliseSelectionWeights(workspaceValue(snapshot,'analytics:selection',DEFAULT_SELECTION_WEIGHTS))),[journal,setJournal]=useState<Journal>(()=>journalValue(workspaceValue(snapshot,'analytics:journal',{entries:{}}))),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const range={from:from||undefined,to:to||undefined},data=deriveAnalytics(snapshot,range),comparison=deriveAnalytics(snapshot,{from:compareFrom||undefined,to:compareTo||undefined}),reserve=reserveSummary(snapshot),comparables=compareAssessments(snapshot,range),gaps=assessmentDepthGaps(snapshot),normal=normaliseSelectionWeights(weights),invalid=!!from&&!!to&&from>to;
 async function saveSelection(){setBusy(true);setMessage('');try{await writeWorkspace(repository,'analytics:selection',{...normal});setWeights(normal);setMessage('Practice priorities saved. They apply to new learning sessions.')}catch(e){setMessage(e instanceof Error?e.message:'Could not save priorities.')}finally{setBusy(false)}}
 async function saveJournal(){setBusy(true);setMessage('');try{await writeWorkspace(repository,'analytics:journal',{entries:journal.entries});setMessage('Mistake journal saved locally.')}catch(e){setMessage(e instanceof Error?e.message:'Could not save journal.')}finally{setBusy(false)}}
 function updateJournal(key:string,changes:Partial<JournalEntry>){setJournal(old=>({entries:{...old.entries,[key]:{...(old.entries[key]??{reason:'',nextStep:'',resolved:false,category:'other' as const}),...changes}}}))}
 return <div className="analytics-view"><div className="page-title"><span className="eyebrow">Evidence from your own practice</span><h1>Understand your revision.</h1><p>Exposure, first answers, repeats and confidence each tell a different part of your progress.</p></div>
 <section className="card"><h2>Date range</h2><div className="analytics-inputs"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label><button onClick={()=>{setFrom('');setTo('')}}>All dates</button></div>{invalid&&<p role="alert">Choose an end date on or after the start date.</p>}<p>{data.eligibleCount} current available questions · {data.excludedAttempts} legacy preview, obsolete or ineligible attempts excluded from proficiency. Historical exposure remains visible.</p><div className="stats-grid">{[['First answer',data.first],['Repeat answers',data.repeat],['Latest per question',data.latest]].map(([label,value])=>{const metric=value as typeof data.first;return <div className="stat" key={label as string}><span>{percentage(metric.accuracy)}</span><small>{label as string} · {metric.count} {metric.count===1?'answer':'answers'}{metric.count<5?' · limited evidence':''}</small></div>})}</div><p className="fine-print">First and repeat status uses the full eligible history, even when the first answer predates this date range. Repeats do not increase distinct coverage. Practice scores do not predict an exam result.</p></section>
 <section className="card"><h2>Compare date ranges</h2><div className="analytics-inputs"><label>Comparison from<input type="date" value={compareFrom} onChange={e=>setCompareFrom(e.target.value)}/></label><label>Comparison through<input type="date" value={compareTo} min={compareFrom} onChange={e=>setCompareTo(e.target.value)}/></label></div><div className="exhibit-scroll"><table><caption>Practice evidence in two periods</caption><thead><tr><th scope="col">Measure</th><th scope="col">Selected dates</th><th scope="col">Comparison dates</th></tr></thead><tbody>{(['first','repeat','latest'] as const).map(key=><tr key={key}><th scope="row">{key==='latest'?'Latest per question':key==='first'?'First answers':'Repeat answers'}</th><td>{percentage(data[key].accuracy)} · {data[key].count}</td><td>{percentage(comparison[key].accuracy)} · {comparison[key].count}</td></tr>)}<tr><th scope="row">Confident mistakes / eligible answers</th>{[data,comparison].map((period,index)=>{const denominator=period.first.count+period.repeat.count;return <td key={index}>{period.confidence.confident.wrong} / {denominator} · {percentage(denominator?period.confidence.confident.wrong/denominator:null)}</td>})}</tr></tbody></table></div><p>Changes can reflect different questions, difficulty or sample sizes. These periods are descriptive, with no claim of equivalent tests.</p><details><summary>Daily practice history</summary>{data.days.length?data.days.map(day=><p key={day.date}>{day.date}: {day.count} answers · {percentage(day.accuracy)}</p>):<p>No eligible answers in these dates yet.</p>}</details></section>
 <section className="card"><h2>Confidence and response time</h2><p>Confident mistakes highlight assumptions to check. Unknown confidence is kept separate.</p><div className="exhibit-scroll"><table><caption>Confidence on scored answers</caption><thead><tr><th scope="col">Confidence</th><th scope="col">Answers</th><th scope="col">Accuracy</th><th scope="col">Wrong</th></tr></thead><tbody>{Object.entries(data.confidence).map(([level,metric])=><tr key={level}><th scope="row">{level}</th><td>{metric.count}</td><td>{percentage(metric.accuracy)}</td><td>{metric.wrong}</td></tr>)}</tbody></table></div><h3>Confident mistake trend</h3><p>Eligible scored answers include every current practice answer in the selected dates, including repeats. Legacy preview sessions and obsolete revisions are excluded. The rate is confident mistakes divided by all eligible scored answers; it describes practice, not exam readiness.</p>{data.days.length?<div className="exhibit-scroll"><table><caption>Confident mistakes by date</caption><thead><tr><th scope="col">Date</th><th scope="col">Confident mistakes</th><th scope="col">Confident answers</th><th scope="col">Eligible scored answers</th><th scope="col">Mistakes / eligible answers</th></tr></thead><tbody>{data.days.map(day=><tr key={day.date}><th scope="row">{day.date}</th><td>{day.confidentWrong}</td><td>{day.confidentAnswers}</td><td>{day.count}</td><td>{percentage(day.confidentWrongRate)}</td></tr>)}</tbody></table></div>:<p>No eligible scored answers in these dates.</p>}<h3>Measured active response time</h3>{data.latency.length?<div className="exhibit-scroll"><table><caption>Measured response time by domain, difficulty and answer format</caption><thead><tr><th scope="col">Domain</th><th scope="col">Difficulty</th><th scope="col">Format</th><th scope="col">Measured answers</th><th scope="col">Median seconds</th></tr></thead><tbody>{data.latency.map(row=><tr key={`${row.domainId}|${row.difficulty}|${row.format}`}><th scope="row">{row.domainId}</th><td>{row.difficulty}</td><td>{row.format}</td><td>{row.count}</td><td>{Math.round(row.medianMs!/1000)}</td></tr>)}</tbody></table></div>:<p>No measured responses yet.</p>}<p className="fine-print">Unmeasured and zero durations are excluded. Speed alone does not demonstrate understanding.</p></section>
 <section className="card"><h2>Transparent practice priorities</h2><p>Choose how a new learning session balances weak objectives, due revision, unseen questions and reinforcement. Overlapping pools share unique questions; a small question bank can change the actual mix.</p><div className="analytics-inputs">{(Object.keys(DEFAULT_SELECTION_WEIGHTS) as (keyof SelectionWeights)[]).map(key=><label key={key}>{key}<input type="range" min="0" max="100" value={weights[key]} aria-label={`${key} priority`} onChange={e=>setWeights({...weights,[key]:Number(e.target.value)})}/><span>{Math.round(normal[key])}% after normalisation</span></label>)}</div><div className="button-row"><button disabled={busy} className="primary" onClick={()=>void saveSelection()}>Save practice priorities</button><button onClick={()=>setWeights({...DEFAULT_SELECTION_WEIGHTS})}>Default 40 / 25 / 20 / 15</button></div></section>
 <section className="card"><h2>Mistake journal</h2><p>Write your own reason and next step. Personal notes do not change source review or proficiency.</p>{data.mistakes.length?<>{data.mistakes.filter((mistake,index,list)=>list.findIndex(x=>x.questionId===mistake.questionId&&x.revision===mistake.revision)===index).map(mistake=>{const key=`${mistake.questionId}@${mistake.revision}`,entry=journal.entries[key]??{reason:'',nextStep:'',resolved:false,category:'other' as const};return <details key={key}><summary>{mistake.prompt} · {mistake.confidence} · {mistake.submittedAt.slice(0,10)}</summary><label>Mistake category<select value={entry.category} onChange={e=>updateJournal(key,{category:e.target.value as MistakeCategory})}>{Object.entries(mistakeCategories).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>My reasoning or mistaken assumption<textarea maxLength={4000} value={entry.reason} onChange={e=>updateJournal(key,{reason:e.target.value})}/></label><label>My next revision step<textarea maxLength={4000} value={entry.nextStep} onChange={e=>updateJournal(key,{nextStep:e.target.value})}/></label><label><input type="checkbox" checked={entry.resolved} onChange={e=>updateJournal(key,{resolved:e.target.checked})}/> I have revisited this mistake</label><a href={mistake.practiceHref}>Practise this question</a></details>})}<button disabled={busy} onClick={()=>void saveJournal()}>Save mistake journal</button></>:<p>No current practice mistakes in these dates.</p>}</section>
 <section className="card"><h2>Exposure and direct subskill practice</h2><details><summary>Question exposure ({data.exposure.filter(q=>q.seenCount).length} seen)</summary>{data.exposure.filter(q=>q.seenCount).map(q=><p key={q.questionId}>{q.questionId}: {q.seenCount} answered attempts · first {q.firstSeenAt?.slice(0,10)} · latest {q.lastSeenAt?.slice(0,10)} · {q.available?'available for practice':'currently unavailable'}</p>)}<p>Exposure records answered attempts, including drafts and older revisions. Simply opening a question does not create an exposure record.</p></details>{data.subskills.map(skill=><p key={skill.id}><a href={skill.practiceHref}>{skill.id}</a>: {skill.studied}/{skill.available} distinct studied · {percentage(skill.accuracy)} · {skill.advancedAvailable} advanced available questions</p>)}</section>
 <section className="card"><h2>Fresh reserve and release history</h2><p>{reserve.installed} installed reserve questions · {reserve.available} available · {reserve.unseen} never answered · {reserve.unreleased} still reserved.</p><p>Draft exposure also uses freshness. Reserve questions enter practice only after explicit opt-in. Older release records have no known date.</p><details><summary>Release events ({reserve.events.length})</summary>{reserve.events.map(event=><p key={event.questionId}>{event.questionId}: {event.releasedAt??'Release date not recorded'}{event.sessionId?` · session ${event.sessionId}`:''}</p>)}</details></section>
 <section className="card"><h2>Similar assessment comparisons</h2><p>Grouped by timed/self-paced format, duration, count, domain, objective, difficulty and answer formats. Draft or stale assessments are excluded. Identical configuration does not imply equal question difficulty.</p>{comparables.length?comparables.map(group=><details key={group.configuration}><summary>{group.sessions.length} comparable {group.sessions[0].deadlineAt?'timed':'self-paced'} assessments · {group.sessions[0].questionSnapshots.length} questions</summary>{group.sessions.map(session=>{const score=group.scores.find(score=>score.sessionId===session.id)!;return <p key={session.id}>{session.submittedAt?.slice(0,10)}: {percentage(score.accuracy)} · {score.count} answers</p>})}</details>):<p>Complete two assessments with the same configuration to compare them.</p>}</section>
 <section className="card"><h2>Assessment depth gaps</h2><p>Subskills with fewer than two current available advanced questions are listed below. This is a content-depth threshold, not an exam-readiness measure. Only available current revisions count towards depth.</p><details><summary>{gaps.length} subskills need more practice depth</summary>{gaps.map(gap=><p key={gap.id}><a href={gap.practiceHref}>{gap.title}</a>: {gap.available} available · {gap.advanced} advanced</p>)}</details></section>{message&&<p className="notice" role="status">{message}</p>}</div>;
}
