import {it,expect} from 'vitest';
import {question,pack} from '../fixtures';
import type {Attempt,DatabaseSnapshot,Session} from '../../src/sessions/types';
import {deriveAnalytics,reserveSummary,assessmentDistribution,compareAssessments} from '../../src/study/analytics';
import {DEFAULT_SELECTION_WEIGHTS,normaliseSelectionWeights,explainSelection,catalogueSelectionPriorities} from '../../src/study/selection-explanation';
import {selectQuestions,type SelectionInput} from '../../src/study/selection';
function fixture(){const q=question({status:'reviewed',difficulty:'advanced',subObjectiveIds:['rbac.roles'],assessmentReserved:true});const trust={questionId:q.id,revision:1,sourceCheckedAt:'2026-10-01',humanReviewedAt:'2026-10-01',reviewer:'test',invalidatedAt:null};const snapshot:DatabaseSnapshot={settings:[],packs:[pack([q])],sourceChecks:[],contentTrust:[trust],sessions:[],attempts:[],reviews:[],bookmarks:[],notes:[],releasedHoldouts:[]};return {q,snapshot}}
function attempt(id:string,correct:boolean,date:string,overrides:Partial<Attempt>={}):Attempt{return {id,sessionId:id,questionId:'q1',questionRevision:1,questionSnapshot:question(),selectedOptionIds:[correct?'a':'b'],confidence:'confident',correct,responseMs:1000,submittedAt:date,mode:'learn',...overrides}}
it('keeps exposure separate from first and repeat proficiency, excluding drafts and obsolete revisions',()=>{const {snapshot}=fixture();snapshot.attempts=[attempt('a',false,'2026-10-01T10:00:00Z'),attempt('b',true,'2026-10-02T10:00:00Z'),attempt('old',true,'2026-09-01T10:00:00Z',{questionRevision:0}),attempt('draft',true,'2026-10-03T10:00:00Z',{mode:'draft-preview'})];const result=deriveAnalytics(snapshot);expect(result.exposure[0].seenCount).toBe(4);expect(result.first).toMatchObject({count:1,accuracy:0});expect(result.repeat).toMatchObject({count:1,accuracy:1});expect(result.latest).toMatchObject({count:1,accuracy:1});expect(result.confidence.confident).toMatchObject({count:2,wrong:1,accuracy:.5});expect(result.excludedAttempts).toBe(2)});
it('classifies repeats across the range boundary and filters invalidated content',()=>{const {snapshot}=fixture();snapshot.attempts=[attempt('a',false,'2026-10-01T10:00:00Z'),attempt('b',true,'2026-10-02T10:00:00Z')];expect(deriveAnalytics(snapshot,{from:'2026-10-02',to:'2026-10-02'}).repeat.count).toBe(1);expect(deriveAnalytics(snapshot,{from:'2026-10-02',to:'2026-10-02'}).first.count).toBe(0);snapshot.contentTrust[0].invalidatedAt='2026-10-03';expect(deriveAnalytics(snapshot).latest.count).toBe(0)});
it('groups measured response time by current domain/difficulty and exposes mistakes with a practice link',()=>{const {snapshot}=fixture();snapshot.attempts=[attempt('a',false,'2026-10-01T10:00:00Z',{responseMs:1000}),attempt('b',true,'2026-10-02T10:00:00Z',{responseMs:9000}),attempt('c',false,'2026-10-03T10:00:00Z',{responseMs:0})];const result=deriveAnalytics(snapshot);expect(result.latency[0]).toMatchObject({domainId:'identity',difficulty:'advanced',count:2,medianMs:5000});expect(result.mistakes[0]).toMatchObject({attemptId:'c',practiceHref:'#/practice?question=q1'});expect(result.subskills[0].advancedAvailable).toBe(1)});
it('reports unseen reserve and preserves unknown release dates from old backups',()=>{const {snapshot}=fixture();expect(reserveSummary(snapshot)).toMatchObject({installed:1,approved:1,unseen:1,unreleased:1});snapshot.releasedHoldouts=[{questionId:'q1'}];const reserve=reserveSummary(snapshot);expect(reserve.events[0].releasedAt).toBeNull();snapshot.attempts=[attempt('draft',false,'2026-10-01',{mode:'draft-preview'})];expect(reserveSummary(snapshot).unseen).toBe(0)});
it('compares only current approved similar assessment configurations and reports actual formats',()=>{const {q,snapshot}=fixture();const s:Session={id:'s',mode:'learn',feedbackAtEnd:true,questionSnapshots:[q],optionOrders:{},answers:{},flags:[],currentIndex:0,startedAt:'2026-10-01',deadlineAt:null,status:'submitted',submittedAt:'2026-10-01',correctionWarnings:[],result:{sessionId:'s',submittedAt:'2026-10-01',correct:1,total:1,attemptIds:['a'],domainResults:[{domainId:'identity',correct:1,total:1}]}};snapshot.sessions=[s,{...s,id:'s2',startedAt:'2026-10-02',submittedAt:'2026-10-02',result:{...s.result!,sessionId:'s2',correct:0}},{...s,id:'timed',deadlineAt:'2026-10-01T01:00:00Z',mode:'timed'}];snapshot.attempts=[attempt('a',true,'2026-10-01',{sessionId:'s'}),attempt('b',false,'2026-10-02',{sessionId:'s2'})];expect(compareAssessments(snapshot)[0].sessions.map(x=>x.id)).toEqual(['s','s2']);expect(assessmentDistribution(s).formats).toEqual({single:1,multiple:0,ordering:0,matching:0});snapshot.contentTrust[0].invalidatedAt='2026-10-03';expect(compareAssessments(snapshot)).toEqual([])});
it('normalises adjustable priorities and explains selected pools and shortages without changing selection',()=>{const {q,snapshot}=fixture();expect(DEFAULT_SELECTION_WEIGHTS).toEqual({weak:40,due:25,unseen:20,reinforcement:15});expect(normaliseSelectionWeights({weak:2,due:1,unseen:1,reinforcement:0})).toEqual({weak:50,due:25,unseen:25,reinforcement:0});expect(normaliseSelectionWeights({weak:0,due:0,unseen:0,reinforcement:0})).toEqual(DEFAULT_SELECTION_WEIGHTS);const input:SelectionInput={questions:[q],trust:snapshot.contentTrust,reviewItems:[],objectiveStats:[],previousSessionIds:[],attemptedIds:[],requestedCount:5,mode:'learn',useReserved:true,now:new Date(),random:()=>0};const result=selectQuestions(input);expect(explainSelection(input,result).questions[0].reasons).toContain('unseen');expect(explainSelection(input,result).shortages).toEqual(result.shortages)});
it('uses the newest installed revision before approval and does not fall back to approved older content',()=>{const {q,snapshot}=fixture();snapshot.packs.push({...pack([question({...q,revision:2,status:'draft'})]),id:'replacement'});snapshot.attempts=[attempt('old',true,'2026-10-01')];expect(deriveAnalytics(snapshot).eligibleCount).toBe(0);expect(deriveAnalytics(snapshot).latest.count).toBe(0)});
it('uses the established immutable legacy subskill mapping for approved original questions',()=>{const {snapshot}=fixture();const q=question({id:'az104-networking-01',domainId:'networking',objectiveId:'network-security',status:'reviewed',difficulty:'advanced'});snapshot.packs=[pack([q])];snapshot.contentTrust=[{...snapshot.contentTrust[0],questionId:q.id}];const result=deriveAnalytics(snapshot);expect(result.subskills[0]).toMatchObject({id:'network-security.2',advancedAvailable:1});});

it('passes all four normalised priorities to the catalogue through the unseen remainder ratio',()=>{expect(catalogueSelectionPriorities({weak:40,due:25,unseen:30,reinforcement:5})).toEqual({weakPercent:40,duePercent:25,unseenRatio:6/7});expect(catalogueSelectionPriorities({weak:100,due:0,unseen:0,reinforcement:0})).toEqual({weakPercent:100,duePercent:0,unseenRatio:4/7});});
it('separates response latency by format within the same domain and difficulty',()=>{const {q,snapshot}=fixture();const multiple=question({...q,id:'q2',type:'multiple',requiredSelections:2,correctOptionIds:['a','b']});snapshot.packs=[pack([q,multiple])];snapshot.contentTrust.push({...snapshot.contentTrust[0],questionId:multiple.id});snapshot.attempts=[attempt('single',true,'2026-10-01',{responseMs:1000}),attempt('multiple',true,'2026-10-02',{questionId:'q2',questionSnapshot:multiple,selectedOptionIds:['a','b'],responseMs:9000})];expect(deriveAnalytics(snapshot).latency).toEqual([{domainId:'identity',difficulty:'advanced',format:'single',count:1,medianMs:1000},{domainId:'identity',difficulty:'advanced',format:'multiple',count:1,medianMs:9000}]);});
it('counts confident mistakes in date buckets with all eligible scored answers as the denominator',()=>{const {snapshot}=fixture();snapshot.attempts=[attempt('wrong',false,'2026-10-01T10:00:00Z'),attempt('unsure',false,'2026-10-01T11:00:00Z',{confidence:'unsure'}),attempt('right',true,'2026-10-01T12:00:00Z'),attempt('draft',false,'2026-10-01T13:00:00Z',{mode:'draft-preview'}),attempt('next',true,'2026-10-02T10:00:00Z')];expect(deriveAnalytics(snapshot).days).toEqual([{date:'2026-10-01',count:3,accuracy:1/3,confidentWrong:1,confidentAnswers:2,confidentWrongRate:1/3},{date:'2026-10-02',count:1,accuracy:1,confidentWrong:0,confidentAnswers:1,confidentWrongRate:0}]);const previous=deriveAnalytics(snapshot,{from:'2026-10-01',to:'2026-10-01'}),next=deriveAnalytics(snapshot,{from:'2026-10-02',to:'2026-10-02'});expect(previous.confidence.confident.wrong).toBe(1);expect(next.confidence.confident.wrong).toBe(0)});
