import {it,expect,afterEach} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {Analytics} from '../../src/features/analytics/Analytics';
import {StudyDatabase} from '../../src/storage/database';
import {StudyRepository} from '../../src/storage/repository';
import {question,pack} from '../fixtures';
const dbs:StudyDatabase[]=[];afterEach(async()=>{for(const db of dbs.splice(0))await db.delete()});
async function setup(){const db=new StudyDatabase(crypto.randomUUID());dbs.push(db);const repository=new StudyRepository(db),q=question({status:'reviewed'});await repository.installPack(pack([q]),[]);await db.contentTrust.put({questionId:q.id,revision:1,sourceCheckedAt:'2026-10-08',humanReviewedAt:'2026-10-08',reviewer:'test',invalidatedAt:null});await db.attempts.put({id:'a',sessionId:'s',questionId:q.id,questionRevision:1,questionSnapshot:q,selectedOptionIds:['b'],confidence:'confident',correct:false,responseMs:1000,submittedAt:'2026-10-08',mode:'learn'});return {db,repository,snapshot:await repository.getSnapshot()}}
it('stores normalised practice priorities and personal mistake reasoning in independent workspace records',async()=>{const {db,repository,snapshot}=await setup();render(<Analytics repository={repository} snapshot={snapshot}/>);fireEvent.change(screen.getByRole('slider',{name:'weak priority'}),{target:{value:'100'}});fireEvent.click(screen.getByRole('button',{name:'Save practice priorities'}));await waitFor(async()=>{const value=(await db.workspace.get('analytics:selection'))?.value;expect(value?.weak).toBe(62.5)});fireEvent.click(screen.getByText('Test prompt · confident · 2026-10-08'));fireEvent.change(screen.getByLabelText('My reasoning or mistaken assumption'),{target:{value:'I assumed permissions inherited.'}});fireEvent.click(screen.getByRole('button',{name:'Save mistake journal'}));await waitFor(async()=>expect((await db.workspace.get('analytics:journal'))?.value).toMatchObject({entries:{'q1@1':{reason:'I assumed permissions inherited.'}}}));expect(await db.contentTrust.count()).toBe(1)});
it('tolerates an imported personal workspace record with an unknown journal shape',async()=>{const {repository,snapshot}=await setup();snapshot.workspace=[{id:'analytics:journal',version:1,value:{unrecognised:'old data'},updatedAt:'2026-10-08'}];render(<Analytics repository={repository} snapshot={snapshot}/>);expect(screen.getByRole('heading',{name:'Mistake journal'})).toBeInTheDocument();expect(screen.getByLabelText('My next revision step')).toHaveValue('')});
it('loads legacy journal text with Other category and saves an explicit mistake category',async()=>{const {db,repository,snapshot}=await setup();snapshot.workspace=[{id:'analytics:journal',version:1,value:{entries:{'q1@1':{reason:'Old explanation',nextStep:'Read the condition',resolved:false}}},updatedAt:'2026-10-08'}];render(<Analytics repository={repository} snapshot={snapshot}/>);expect(screen.getByLabelText('Mistake category')).toHaveValue('other');expect(screen.getByLabelText('My reasoning or mistaken assumption')).toHaveValue('Old explanation');fireEvent.change(screen.getByLabelText('Mistake category'),{target:{value:'missed-condition'}});fireEvent.click(screen.getByRole('button',{name:'Save mistake journal'}));await waitFor(async()=>expect((await db.workspace.get('analytics:journal'))?.value).toMatchObject({entries:{'q1@1':{reason:'Old explanation',category:'missed-condition'}}}))});
it('shows a dated confidence mistake trend with an explicit eligible denominator',async()=>{const {repository,snapshot}=await setup();render(<Analytics repository={repository} snapshot={snapshot}/>);expect(screen.getByRole('table',{name:'Confident mistakes by date'})).toBeInTheDocument();expect(screen.getByRole('columnheader',{name:'Eligible scored answers'})).toBeInTheDocument();expect(screen.getByRole('row',{name:'2026-10-08 1 1 1 100%'})).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Comparison from'),{target:{value:'2026-10-07'}});fireEvent.change(screen.getByLabelText('Comparison through'),{target:{value:'2026-10-07'}});expect(screen.getByRole('row',{name:/Confident mistakes \/ eligible answers/})).toHaveTextContent('1 / 1 · 100%0 / 0 · No scored evidence')});
