import {it,expect,afterEach} from 'vitest';
import {StudyDatabase} from '../../src/storage/database';
import {StudyRepository} from '../../src/storage/repository';
import {SessionService} from '../../src/sessions/service';
import {question,pack} from '../fixtures';
const dbs:StudyDatabase[]=[];afterEach(async()=>{for(const db of dbs.splice(0))await db.delete()});
async function setup(draft=false){const db=new StudyDatabase(crypto.randomUUID());dbs.push(db);const repo=new StudyRepository(db),now=new Date('2026-10-08T12:00:00Z'),service=new SessionService(repo,()=>now);const q=question({status:draft?'draft':'reviewed',caseStudy:{id:'case1',title:'Case',overview:'Shared facts'}});await repo.installPack(pack([q]),[]);if(!draft)await repo.setContentTrust({questionId:q.id,revision:1},{questionId:q.id,revision:1,sourceCheckedAt:now.toISOString(),humanReviewedAt:now.toISOString(),reviewer:'test',invalidatedAt:null});const s=await service.createSession({mode:draft?'draft-preview':'learn',feedbackAtEnd:true,durationMinutes:null,releasesReservedIds:[],selectedQuestions:[q]});return {db,repo,service,q,s,now}}
it('keeps self-paced case answers unscored until explicit finalisation, even after a long resume',async()=>{const {service,s,repo,q,now}=await setup();expect(s.deadlineAt).toBeNull();expect(s.feedbackAtEnd).toBe(true);await service.saveDraftAnswer(s.id,q.id,{selectedOptionIds:['a'],confidence:'confident',responseMs:42});await expect(service.submitLearnAnswer(s.id,q.id,['a'],'confident',42)).rejects.toThrow(/learning answer/);await service.advanceSession(s.id);expect((await service.resumeSession(s.id,new Date('2027-01-01'))).status).toBe('active');expect((await repo.getSnapshot()).attempts).toHaveLength(0);const result=await service.finaliseAssessmentSession(s.id,now);expect(result.correct).toBe(1);expect(await service.finaliseAssessmentSession(s.id,new Date('2027-01-01'))).toEqual(result);expect((await repo.getSnapshot()).reviews).toHaveLength(1)});
it('scores self-paced draft snapshots without writing reviewed progress',async()=>{const {service,s,repo,now}=await setup(true);await service.finaliseAssessmentSession(s.id,now);expect((await repo.getSnapshot()).attempts[0]).toMatchObject({mode:'draft-preview',correct:false});expect((await repo.getSnapshot()).reviews).toHaveLength(0)});
it('rejects finalising regular learning and missing/closed advancement with a useful error',async()=>{const {service,q}=await setup();const learn=await service.createSession({mode:'learn',durationMinutes:null,releasesReservedIds:[],selectedQuestions:[q]});await expect(service.finaliseAssessmentSession(learn.id,new Date())).rejects.toThrow(/assessment/);await expect(service.advanceSession('missing')).rejects.toThrow(/not found/)});
it('rolls back self-paced assessment when the attempt write fails',async()=>{const {db,service,s,repo,now}=await setup();const before=await repo.getSnapshot();db.attempts.hook('creating',()=>{throw Error('quota')});await expect(service.finaliseAssessmentSession(s.id,now)).rejects.toThrow('quota');expect(await repo.getSnapshot()).toEqual(before)});
it('records new reserve release dates and preserves prior events across reuse',async()=>{const {service,q,repo,now}=await setup();q.assessmentReserved=true;const first=await service.createSession({mode:'learn',durationMinutes:null,releasesReservedIds:[q.id],selectedQuestions:[q]});expect((await repo.getSnapshot()).releasedHoldouts[0]).toMatchObject({questionId:q.id,releasedAt:now.toISOString(),sessionId:first.id});await service.createSession({mode:'learn',durationMinutes:null,releasesReservedIds:[q.id],selectedQuestions:[q]});expect((await repo.getSnapshot()).releasedHoldouts[0].sessionId).toBe(first.id)});
