import type {StudyRepository} from '../storage/repository';import type {Session,SessionAnswer,StartSessionInput,Attempt,SessionResult} from './types';import {AppError} from './types';import {scoreAnswer,canSubmit} from '../study/scoring';import {scheduleReview,type Confidence} from '../study/review';import {classifyQuestion} from '../content/trust';
export class SessionService{
 repo:StudyRepository;clock:()=>Date;random:()=>number;
 constructor(repo:StudyRepository,clock=()=>new Date(),random=Math.random){this.repo=repo;this.clock=clock;this.random=random}
 async createSession(i:StartSessionInput):Promise<Session>{
  if(!i.selectedQuestions.length||new Set(i.selectedQuestions.map(q=>q.id)).size!==i.selectedQuestions.length)throw new AppError('empty','Choose a session with unique available questions');
  if(i.mode==='timed'&&(!i.durationMinutes||i.durationMinutes<1||i.durationMinutes>240))throw new AppError('duration','Choose a duration from 1 to 240 minutes');
  const now=this.clock();const s:Session={id:crypto.randomUUID(),mode:i.mode,questionSnapshots:structuredClone(i.selectedQuestions),optionOrders:{},answers:{},flags:[],currentIndex:0,startedAt:now.toISOString(),deadlineAt:i.mode==='timed'?new Date(now.getTime()+i.durationMinutes!*60000).toISOString():null,status:'active',submittedAt:null,correctionWarnings:[]};
  await this.repo.db.transaction('rw',this.repo.db.sessions,this.repo.db.contentTrust,this.repo.db.releasedHoldouts,async()=>{
   for(const q of i.selectedQuestions){const t=await this.repo.db.contentTrust.get([q.id,q.revision]);if(i.mode!=='draft-preview'&&classifyQuestion(q,t??null)!=='eligible')throw new AppError('unreviewed','This question needs content review');const ids=q.options.map(o=>o.id);for(let n=ids.length-1;n>0;n--){const j=Math.min(n,Math.floor(this.random()*(n+1)));[ids[n],ids[j]]=[ids[j],ids[n]]}s.optionOrders[q.id]=ids;}
   await this.repo.db.sessions.add(s);if(i.releasesReservedIds.length)await this.repo.db.releasedHoldouts.bulkPut(i.releasesReservedIds.map(questionId=>({questionId})));
  });return s;
 }
 async saveDraftAnswer(id:string,qid:string,answer:SessionAnswer):Promise<void>{await this.repo.db.transaction('rw',this.repo.db.sessions,async()=>{const s=await this.repo.db.sessions.get(id);if(!s||s.status!=='active'||(s.deadlineAt&&Date.parse(s.deadlineAt)<=this.clock().getTime()))throw new AppError('closed','This session has finished');const q=s.questionSnapshots.find(q=>q.id===qid);if(!q||new Set(answer.selectedOptionIds).size!==answer.selectedOptionIds.length||answer.selectedOptionIds.some(id=>!q.options.some(o=>o.id===id)))throw new AppError('answer','Invalid answer selection');s.answers[qid]=answer;await this.repo.db.sessions.put(s)})}
 async submitLearnAnswer(id:string,qid:string,ids:string[],confidence:Confidence,responseMs:number):Promise<Attempt>{try{return await this.repo.db.transaction('rw',this.repo.db.sessions,this.repo.db.attempts,this.repo.db.reviews,async()=>{
  const existing=await this.repo.db.attempts.get(id+':'+qid);if(existing)return existing;
  const s=await this.repo.db.sessions.get(id);if(!s||s.status!=='active'||s.mode==='timed')throw new AppError('closed','Cannot submit a learning answer here');const q=s.questionSnapshots.find(q=>q.id===qid);if(!q||!canSubmit(q,ids))throw new AppError('answer','Select the stated number of answers');const now=this.clock();const attempt:Attempt={id:id+':'+qid,sessionId:id,questionId:qid,questionRevision:q.revision,questionSnapshot:q,selectedOptionIds:ids,confidence,correct:scoreAnswer(q,ids),responseMs,submittedAt:now.toISOString(),mode:s.mode};
  await this.repo.db.attempts.add(attempt);s.answers[qid]={selectedOptionIds:ids,confidence,responseMs};await this.repo.db.sessions.put(s);
  if(s.mode!=='draft-preview'&&!s.correctionWarnings.some(x=>x.questionId===qid)){const previous=await this.repo.db.reviews.get(qid);await this.repo.db.reviews.put(scheduleReview(previous??null,{questionId:qid,revision:q.revision,correct:attempt.correct,confidence,occurredAt:now.toISOString(),isDueAttempt:!previous||Date.parse(previous.dueAt)<=now.getTime()},now))}return attempt;
 })}catch(e){if(e instanceof AppError)throw e;throw new AppError('storage','Answer not saved. Check browser storage and retry.') }}
 async advanceSession(id:string):Promise<Session>{return this.repo.db.transaction('rw',this.repo.db.sessions,this.repo.db.attempts,async()=>{const s=(await this.repo.db.sessions.get(id))!;if(s.mode!=='timed'){const q=s.questionSnapshots[s.currentIndex];if(!await this.repo.db.attempts.get(id+':'+q.id))throw new AppError('answer','Submit this answer first');if(s.currentIndex===s.questionSnapshots.length-1){s.status='submitted';s.submittedAt=this.clock().toISOString();s.result=this.result(s,await this.repo.db.attempts.where('sessionId').equals(id).toArray(),s.submittedAt)}else s.currentIndex++}await this.repo.db.sessions.put(s);return s})}
 result(s:Session,attempts:Attempt[],date:string):SessionResult{const domains=[...new Set(s.questionSnapshots.map(q=>q.domainId))];return {sessionId:s.id,submittedAt:date,correct:attempts.filter(a=>a.correct).length,total:s.questionSnapshots.length,attemptIds:attempts.map(a=>a.id),domainResults:domains.map(domainId=>({domainId,correct:attempts.filter(a=>a.questionSnapshot.domainId===domainId&&a.correct).length,total:s.questionSnapshots.filter(q=>q.domainId===domainId).length}))}}
 async finaliseTimedSession(id:string,now:Date):Promise<SessionResult>{return this.repo.db.transaction('rw',this.repo.db.sessions,this.repo.db.attempts,this.repo.db.reviews,async()=>{const s=await this.repo.db.sessions.get(id);if(!s||s.mode!=='timed')throw new AppError('mode','Not a timed session');if(s.result)return s.result;const attempts:Attempt[]=[];for(const q of s.questionSnapshots){const answer=s.answers[q.id]??{selectedOptionIds:[],confidence:'unknown' as const,responseMs:0};const a:Attempt={id:id+':'+q.id,sessionId:id,questionId:q.id,questionRevision:q.revision,questionSnapshot:q,...answer,correct:scoreAnswer(q,answer.selectedOptionIds),submittedAt:now.toISOString(),mode:'timed'};attempts.push(a);if(!s.correctionWarnings.some(x=>x.questionId===q.id)){const p=await this.repo.db.reviews.get(q.id);await this.repo.db.reviews.put(scheduleReview(p??null,{questionId:q.id,revision:q.revision,correct:a.correct,confidence:a.confidence,occurredAt:a.submittedAt,isDueAttempt:!p||Date.parse(p.dueAt)<=now.getTime()},now))}}await this.repo.db.attempts.bulkPut(attempts);s.status='submitted';s.submittedAt=now.toISOString();s.result=this.result(s,attempts,s.submittedAt);await this.repo.db.sessions.put(s);return s.result})}
 async resumeSession(id:string,now:Date):Promise<Session>{let s=await this.repo.db.sessions.get(id);if(!s)throw new AppError('missing','Session not found');if(s.mode==='timed'&&s.status==='active'&&s.deadlineAt&&Date.parse(s.deadlineAt)<=now.getTime()){await this.finaliseTimedSession(id,now);s=(await this.repo.db.sessions.get(id))!}return s}
}
