/** Rebuild a non-authoritative review index from retained official HTML/text.
 * Evidence excerpts are lexical candidates, never automatic factual approval.
 * Re-run after installing new packs: node scripts/audit-bank.mjs
 */
import {readFileSync,readdirSync,existsSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
const bank=readdirSync('content/packs').filter(f=>f.endsWith('.json')).sort().flatMap(f=>JSON.parse(readFileSync(`content/packs/${f}`,'utf8')).questions);
const ledger=readdirSync('content/sources').filter(f=>f.endsWith('.json')).flatMap(f=>{const data=JSON.parse(readFileSync(`content/sources/${f}`,'utf8'));return Array.isArray(data)?data:data.entries??[]});
const historicalRevisions=existsSync('content/audits/full-bank-review.json')?(JSON.parse(readFileSync('content/audits/full-bank-review.json','utf8')).historicalRevisions??[]):[];
const semanticRecords=Object.assign({},...['semantic-review.json','semantic-compute.json','semantic-networking.json'].map(name=>JSON.parse(readFileSync(`src/features/evidence/${name}`,'utf8'))));
const computeHistory=existsSync('content/audits/compute-semantic-corrections.json')?JSON.parse(readFileSync('content/audits/compute-semantic-corrections.json','utf8')):null;
for(const correction of computeHistory?.corrections??[])if(!historicalRevisions.some(r=>r.questionId===correction.questionId&&r.revision===correction.before.revision))historicalRevisions.push({questionId:correction.questionId,revision:correction.before.revision,packId:computeHistory.packId,packVersion:computeHistory.beforePackVersion,questionSnapshot:correction.before,reason:correction.reason});
const sources=[];
for(const domain of ['identity','storage','compute','networking','monitoring','resource']){
 const dir=`/tmp/studyapp-${domain}-sources`;if(!existsSync(dir))continue;
 const metadata=[];
 for(const name of readdirSync(dir).filter(f=>f==='index.json'||f==='manifest.json'||f==='metadata.json'||f.endsWith('.meta.json'))){const data=JSON.parse(readFileSync(`${dir}/${name}`,'utf8'));metadata.push(...(Array.isArray(data)?data:data.url?[data]:Object.entries(data).map(([key,value])=>({key,...value}))))}
 for(const filename of readdirSync(dir).filter(f=>f.endsWith('.html'))){
  const raw=readFileSync(`${dir}/${filename}`),html=raw.toString(),key=filename.replace('.html',''),url=html.match(/<link[^>]+rel="canonical"[^>]+href="([^"]+)"/)?.[1]??html.match(/<link[^>]+href="([^"]+)"[^>]+rel="canonical"/)?.[1];
  if(!url||new URL(url).hostname!=='learn.microsoft.com')continue;
  const meta=metadata.find(m=>(m.canonicalUrl??m.url)===url)||metadata.find(m=>m.key===key||m.referenceId===key||m.referenceId===`storage-plus-${key}`);
  const checked=meta?.checkedAt??ledger.find(m=>m.canonicalUrl===url)?.checkedAt;
  if(!checked)continue;
  const contentHash=createHash('sha256').update(raw).digest('hex'),expectedHash=meta?.contentHash??meta?.hash;
  if(expectedHash&&contentHash!==expectedHash)continue;
  const textfile=`${dir}/${key}.txt`, text=existsSync(textfile)?readFileSync(textfile,'utf8').replace(/\s+/g,' ').trim():html.replace(/<script[\s\S]*?<\/script>/g,'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
  sources.push({url,checkedAt:checked,contentHash,htmlHashVerified:true,hashVerification:expectedHash?'matches retained retrieval metadata':'computed from retained HTML; retrieval date from official source ledger',artifact:resolve(dir,filename),text,sentences:text.match(/[^.!?]+(?:[.!?]|$)/g)?.filter(s=>s.length>40&&s.length<1800)??[text]});
 }
}
const extraPacket=existsSync('content/audits/networking-extra-evidence.json')?JSON.parse(readFileSync('content/audits/networking-extra-evidence.json','utf8')):null;
for(const entry of extraPacket?.evidence??[]){if(sources.some(s=>s.url===entry.canonicalUrl))continue;const raw=readFileSync(entry.htmlPath),textRaw=readFileSync(entry.textPath);if(createHash('sha256').update(raw).digest('hex')!==entry.htmlSha256||createHash('sha256').update(textRaw).digest('hex')!==entry.textSha256)throw Error('Extra official source integrity mismatch');const text=textRaw.toString();if(text.slice(entry.quoteStartOffset,entry.quoteEndOffset)!==entry.quote)throw Error('Official excerpt mismatch');sources.push({url:entry.canonicalUrl,checkedAt:entry.checkedAt,contentHash:entry.htmlSha256,htmlHashVerified:true,hashVerification:'matches retained exact-quotation retrieval packet',artifact:entry.htmlPath,text,sentences:text.match(/[^.!?]+(?:[.!?]|$)/g)?.filter(s=>s.length>40&&s.length<1800)??[text]})}
const stop=new Set('the and that this with from into only when must your have has does not are for but can its use using will all then each their been should other which where there after before more than also they these those source documented documentation azure microsoft learn'.split(' '));
function terms(s){return [...new Set(s.toLowerCase().match(/[a-z][a-z0-9-]{2,}/g)??[])].filter(t=>!stop.has(t))}
function excerpt(claim,source){const words=terms(claim);const ranked=source.sentences.map(text=>({text:text.trim(),matches:words.filter(t=>text.toLowerCase().includes(t))})).sort((a,b)=>b.matches.length-a.matches.length);const best=ranked[0];if(!best||best.matches.length<2)return null;return {url:source.url,checkedAt:source.checkedAt,contentHash:source.contentHash,htmlHashVerified:source.htmlHashVerified,hashVerification:source.hashVerification,artifact:source.artifact,excerpt:best.text.slice(0,1200),matchedTerms:best.matches,interpretation:'Candidate official excerpt found by lexical overlap. Reviewer must check entailment and negation; this does not establish that the option is correct.'}}
function normalizeUrl(value){const url=new URL(value);url.hash='';url.searchParams.delete('preserve-view');return url.href.replace(/\/$/,'')}
function evidenceFor(q,option){return option.referenceIds.flatMap(id=>{const r=q.references.find(r=>r.id===id);if(!r)return [];const source=sources.find(s=>normalizeUrl(s.url)===normalizeUrl(r.url));if(!source)return [];const e=excerpt(`${option.text} ${option.explanation}`,source);return e?[{referenceId:id,section:r.section,...e}]:[]})}
const correctionSpecs={
 'az104-storage-plus-36':[
  {field:'match:p2',newText:'Online tier optimized for infrequent access with a documented minimum retention duration of 30 days for explicitly tiered blobs.',reason:'The original at-least-30-days wording also permits retention exceeding the Cold minimum. Match the documented tier-specific minimum rather than broad eligibility.',url:'https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview',needle:'Data in the cool tier should be stored for a minimum of 30 days.'},
  {field:'match:p3',newText:'Online tier optimized for rare access with fast retrieval and a documented minimum retention duration of 90 days for explicitly tiered blobs.',reason:'Cool blobs can also be retained for 90 days; a lower-bound retention statement does not uniquely identify Cold. Naming the documented minimum makes the pairing distinguishable.',url:'https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview',needle:'Data in the cold tier should be stored for a minimum of 90 days.'}
 ],
 'az104-monitoring-plus-08':[
  {field:'prompt',newText:'Choose TWO DCR capabilities that define the filtering-and-delivery pipeline: removing noisy input and sending the retained data to its chosen destination.',reason:'Choosing a destination does not itself filter logs. The original goal describes filtering alone while demanding two answers. The official DCR description separately identifies transformations and destinations; the revised goal makes both relevant.',url:'https://learn.microsoft.com/en-us/azure/azure-monitor/data-collection/data-collection-rule-overview',needle:"Transformations to apply to the data before it's stored."}
 ]
};
function concreteCorrections(q){const original=historicalRevisions.find(r=>r.questionId===q.id&&r.revision===1)?.questionSnapshot??q;return (correctionSpecs[q.id]??[]).flatMap(spec=>{const source=sources.find(s=>s.url===spec.url);const index=source?.text.indexOf(spec.needle)??-1;if(!source||index<0)return [];return [{field:spec.field,oldText:spec.field==='prompt'?original.prompt:original.matchPrompts?.find(p=>`match:${p.id}`===spec.field)?.text,newText:spec.newText,reason:spec.reason,baseRevision:original.revision,proposedRevision:original.revision+1,humanApproved:false,installedAsDraft:q.revision>original.revision,status:q.revision>original.revision?'Installed as a new draft revision; human review outstanding':'AI-assisted proposed correction; human review required',evidence:[{url:source.url,checkedAt:source.checkedAt,contentHash:source.contentHash,htmlHashVerified:true,excerpt:source.text.slice(Math.max(0,index-150),index+spec.needle.length+200)}]}]})}
const questions=bank.map(q=>{
 const optionAudits=q.options.map(o=>{const evidence=evidenceFor(q,o);return {optionId:o.id,text:o.text,claim:o.explanation,designatedCorrect:q.correctOptionIds.includes(o.id),method:'AI-assisted evidence indexing; semantic review outstanding',disposition:evidence.length?'candidate-evidence-located':'evidence-gap',evidence,uncertainty:evidence.length?'Check whether the excerpt supports this explanation and excludes competing answers under the scenario assumptions.':'No sufficiently relevant retained official excerpt found; retrieve the exact section before approval.'}});
 const semanticInput=semanticRecords[q.id],semanticReview=semanticInput?.reviewedRevision===q.revision?{...semanticInput,humanApprovalGranted:false,reviewedComponents:['scenario','prompt','every-option-and-explanation','summary','assumptions-and-prerequisites',...(q.exhibits?.length?['exhibits']:[]),...(q.type==='ordering'?['mandatory-dependencies-and-alternative-orders']:[]),...(q.type==='matching'?['each-pair-and-competing-mappings']:[]),...(q.caseStudy?['persistent-and-linked-case-facts']:[])],optionConcerns:semanticInput.optionConcerns??[],uncertainties:[...(semanticInput.uncertainties??[]),...optionAudits.filter(o=>!o.evidence.length).map(o=>`Option ${o.optionId}: exact retained per-option excerpt is missing; semantic rejection must be checked against the official section before human approval.`)],evidenceUrls:q.references.map(r=>r.url),optionReviews:optionAudits.map(o=>({optionId:o.optionId,verdict:o.evidence.length?'consistent-with-question-specific-semantic-rationale':'exact-source-support-unresolved',reviewedClaim:o.claim,questionRole:q.type==='ordering'?'sequence-step':q.type==='matching'?'matching-answer':o.designatedCorrect?'keyed-answer':'distractor',conclusion:o.evidence.length?'AI semantic rationale recorded below; verify exact excerpt entailment during human review':'AI rationale recorded; an exact per-option retained excerpt is still missing',reasoning:semanticInput.conclusion,evidence:o.evidence.map((e,index)=>({referenceId:e.referenceId,url:e.url,contentHash:e.contentHash,optionEvidenceIndex:index}))}))}:null;
 const proposedCorrections=concreteCorrections(q);const flags=proposedCorrections.map(p=>`Concrete proposed correction: ${p.reason}`);
 if(optionAudits.some(o=>!o.evidence.length))flags.push('One or more options lack a relevant retained excerpt.');
 if(/\b(always|never|automatically|only|guarantee)\b/i.test(`${q.prompt} ${q.options.map(o=>o.explanation).join(' ')}`))flags.push('Absolute or exclusivity wording requires an exception and prerequisite check.');
 if(!/assum|supported|sku|tier|licens|region|prerequisit|already|configured/i.test(q.scenario))flags.push('Scenario has no explicit availability/prerequisite qualifier; inspect whether one affects the answer.');
 const assumptions=q.scenario.match(/[^.!?]*(?:assum|supported|sku|tier|licens|region|prerequisit|already|configured)[^.!?]*[.!?]?/gi)??[];
 const invalidAnswer=q.correctOptionIds.some(id=>!q.options.some(o=>o.id===id))||q.correctOptionIds.length!==q.requiredSelections;
 if(invalidAnswer)flags.push('Answer IDs or selection count are inconsistent.');
 const sequenceAudit=q.type==='ordering'?{method:'AI-assisted dependency review support',steps:q.correctOptionIds.map((id,index)=>({position:index+1,optionId:id,step:q.options.find(o=>o.id===id)?.text,evidence:optionAudits.find(o=>o.optionId===id)?.evidence??[],dependencyCheck:'Human confirmation pending: distinguish mandatory predecessor constraints from a merely documented walkthrough order; see the AI semantic conclusion for this sequence.'})),structurallyComplete:new Set(q.correctOptionIds).size===q.options.length,alternativeOrders:'AI alternative-order review is recorded in the question-specific semantic conclusion. Human confirmation of independent steps and prerequisites remains pending.'}:null;
 const matchingAudit=q.type==='matching'?{method:'AI-assisted pairing review support',pairs:(q.matchPrompts??[]).map((p,index)=>({promptId:p.id,prompt:p.text,optionId:q.correctOptionIds[index],answer:q.options.find(o=>o.id===q.correctOptionIds[index])?.text,evidence:optionAudits.find(o=>o.optionId===q.correctOptionIds[index])?.evidence??[],uncertainty:'Human confirmation pending for this pairing and competing mappings; the AI semantic conclusion evaluates the complete mapping.'})),structurallyComplete:q.matchPrompts?.length===q.correctOptionIds.length}:null;
 const linked=q.caseStudy?bank.filter(other=>other.caseStudy?.id===q.caseStudy.id):[];
 const caseAudit=q.caseStudy?{caseId:q.caseStudy.id,overview:q.caseStudy.overview,linkedQuestionIds:linked.map(other=>other.id),consistentStoredOverview:linked.every(other=>other.caseStudy.overview===q.caseStudy.overview),crossQuestionReview:'AI case-fact review is recorded in the question-specific semantic conclusion. Human confirmation against persistent facts and earlier changes remains pending; identical stored overviews alone do not establish consistency.'}:null;
 if(caseAudit&&!caseAudit.consistentStoredOverview)flags.push('Linked case overviews differ.');
 return {questionId:q.id,revision:q.revision,domainId:q.domainId,objectiveId:q.objectiveId,type:q.type,disposition:'needs-review',method:'AI-assisted; no human factual approval',proposedCorrections,semanticReview,optionAudits,assumptionAudit:{explicitScenarioQualifiers:assumptions,reviewRequired:'Check configuration, scope, licensing/SKU, regional availability and service limitations against the official sections.'},ambiguityAudit:{correctOptionIds:q.correctOptionIds,requiredSelections:q.requiredSelections,structuralAnswerValid:!invalidAnswer,alternativeAnswerCheck:'Open: check every distractor and competing answer under all stated conditions.'},sequenceAudit,matchingAudit,caseAudit,flags,uncertainties:['Human answer and explanation review outstanding.','Source excerpts and AI semantic judgments remain separate from human factual approval.',...(semanticReview?.uncertainties??[]),...(semanticReview?.optionConcerns??[]),...flags]};
});
const report={schemaVersion:1,auditedAt:new Date().toISOString(),auditMethod:'AI-assisted semantic review of every current question against retained official Microsoft Learn text, with separately labelled source-excerpt indexing and structural checks. Per-question conclusions, every option, assumptions, summary, alternative order/mapping and linked-case facts are recorded. Human factual approval remains outstanding.',humanReviewCompleted:false,sourceDocuments:sources.length,summary:{questions:bank.length,aiSemanticReviewed:questions.filter(q=>q.semanticReview).length,semanticConcerns:questions.filter(q=>q.semanticReview&&(q.semanticReview.uncertainties.length||q.semanticReview.optionConcerns.length)).length,options:questions.reduce((n,q)=>n+q.optionAudits.length,0),candidateEvidenceOptions:questions.reduce((n,q)=>n+q.optionAudits.filter(o=>o.evidence.length).length,0),evidenceGaps:questions.reduce((n,q)=>n+q.optionAudits.filter(o=>!o.evidence.length).length,0),ordering:questions.filter(q=>q.sequenceAudit).length,matching:questions.filter(q=>q.matchingAudit).length,caseQuestions:questions.filter(q=>q.caseAudit).length,humanApproved:0},historicalRevisions,questions};
writeFileSync('content/audits/full-bank-review.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report.summary));
