import {expect,it,vi} from 'vitest';
import Dexie from 'dexie';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {Journey} from '../../src/features/journey/Journey';
import {StudyDatabase} from '../../src/storage/database';
import {StudyRepository} from '../../src/storage/repository';
it('saves personal goals durably and keeps edits with clear failure and retry',async()=>{const repository=new StudyRepository(new StudyDatabase('journey-'+crypto.randomUUID()));try{render(<Journey repository={repository} snapshot={await repository.getSnapshot()}/>);fireEvent.change(screen.getByLabelText('Personal goal'),{target:{value:'Read identity topics'}});const put=vi.spyOn(repository.db.workspace,'put').mockRejectedValueOnce(new Error('disk'));fireEvent.click(screen.getByRole('button',{name:'Save plan'}));await screen.findByRole('alert');expect(screen.getByLabelText('Personal goal')).toHaveValue('Read identity topics');fireEvent.click(screen.getByRole('button',{name:'Save plan'}));await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent('Saved on this device'));expect((await repository.db.workspace.get('journey:plan'))?.value.goal).toBe('Read identity topics');put.mockRestore()}finally{await repository.db.delete()}});
it('adds an objective task, completes with timestamp, pauses and resumes without history loss',async()=>{const repository=new StudyRepository(new StudyDatabase('journey-lifecycle-'+crypto.randomUUID()));try{render(<Journey repository={repository} snapshot={await repository.getSnapshot()}/>);fireEvent.change(screen.getByLabelText('Task title'),{target:{value:'Identity reading'}});fireEvent.change(screen.getByLabelText('AZ-104 objective'),{target:{value:'entra'}});fireEvent.click(screen.getByRole('button',{name:'Add task and save'}));await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent('Saved on this device'));fireEvent.click(screen.getByRole('button',{name:'Mark Identity reading complete'}));await waitFor(async()=>expect(((await repository.db.workspace.get('journey:plan'))?.value.tasks as {completedAt:string}[])[0].completedAt).toMatch(/^\d{4}-/));fireEvent.click(screen.getByRole('button',{name:'Pause plan'}));await screen.findByRole('button',{name:'Resume plan'});await waitFor(()=>expect(screen.getByRole('button',{name:'Resume plan'})).not.toBeDisabled());fireEvent.click(screen.getByRole('button',{name:'Resume plan'}));await waitFor(async()=>{const v=(await repository.db.workspace.get('journey:plan'))?.value;expect(v?.paused).toBe(false);expect(v?.pauseHistory).toHaveLength(2);expect(v?.tasks).toHaveLength(1);expect((v?.tasks as {objectiveId:string}[])[0].objectiveId).toBe('entra')})}finally{await repository.db.delete()}});
it('retains edits typed while a previous save is pending',async()=>{const repository=new StudyRepository(new StudyDatabase('journey-pending-'+crypto.randomUUID()));try{render(<Journey repository={repository} snapshot={await repository.getSnapshot()}/>);let finish!:()=>void;const put=vi.spyOn(repository.db.workspace,'put').mockImplementationOnce(()=>new Dexie.Promise<string>(resolve=>{finish=()=>resolve('journey:plan')}));fireEvent.change(screen.getByLabelText('Personal goal'),{target:{value:'First'}});fireEvent.click(screen.getByRole('button',{name:'Save plan'}));fireEvent.change(screen.getByLabelText('Personal goal'),{target:{value:'Later edit'}});finish();await waitFor(()=>expect(screen.getByRole('button',{name:'Save plan'})).not.toBeDisabled());expect(screen.getByLabelText('Personal goal')).toHaveValue('Later edit');expect(screen.getByRole('status')).toHaveTextContent('Unsaved edits');put.mockRestore()}finally{await repository.db.delete()}});
