import {afterEach,expect,it} from 'vitest';
import {StudyDatabase} from '../../src/storage/database';
import {StudyRepository} from '../../src/storage/repository';
import {SessionService} from '../../src/sessions/service';
import {defaultPracticePreset,preflightPractice} from '../../src/study/catalogue';
import {selectBalancedAssessment,selectCaseStudy} from '../../src/study/assessment';
import {calculateProgress} from '../../src/study/progress';
import {deriveAnalytics} from '../../src/study/analytics';
import {deriveHistory} from '../../src/features/reports/model';
import {computeCoverage} from '../../src/study/coverage';
import {blueprint,pack,question} from '../fixtures';
const databases:StudyDatabase[]=[];
afterEach(async()=>{for(const db of databases.splice(0))await db.delete()});
async function fresh(){const db=new StudyDatabase('select-and-go-'+crypto.randomUUID());databases.push(db);const repo=new StudyRepository(db);const questions=Array.from({length:10},(_,i)=>question({id:'q'+i,subObjectiveIds:['rbac.1']}));await repo.installPack(pack(questions),[]);return {repo,questions,service:new SessionService(repo)}}
it('fresh install can select ten Learn questions with no human approval',async()=>{const {repo}=await fresh();const snapshot=await repo.getSnapshot();const result=preflightPractice(snapshot,defaultPracticePreset());expect(result.questions).toHaveLength(10);expect(result.excluded.unapproved).toBe(0);expect(snapshot.contentTrust.every(t=>!t.humanReviewedAt)).toBe(true)});
it.each(['learn','timed'] as const)('starts %s directly and preserves truthful draft metadata',async mode=>{const {repo,questions,service}=await fresh();const session=await service.createSession({mode,selectedQuestions:questions,durationMinutes:mode==='timed'?5:null,releasesReservedIds:[]});expect(session.mode).toBe(mode);expect(session.questionSnapshots).toHaveLength(10);expect(session.questionSnapshots.every(q=>q.status==='draft')).toBe(true);expect((await repo.getSnapshot()).contentTrust.every(t=>!t.humanReviewedAt)).toBe(true)});
it('answers in ordinary Learn count towards progress, coverage, analytics and history without review',async()=>{const {repo,questions,service}=await fresh();const s=await service.createSession({mode:'learn',selectedQuestions:questions,durationMinutes:null,releasesReservedIds:[]});await service.submitLearnAnswer(s.id,questions[0].id,['a'],'confident',1000);const snapshot=await repo.getSnapshot();expect(snapshot.reviews).toHaveLength(1);expect(calculateProgress(snapshot.attempts,questions,new Date()).totalDistinct).toBe(1);expect(deriveAnalytics(snapshot).distinctStudied).toBe(1);expect(computeCoverage(blueprint,questions,snapshot.contentTrust,snapshot.attempts)[0]).toMatchObject({approved:0,studied:1,accuracy:1});expect(deriveHistory(snapshot,{})[0].details[0].currentEligibleAttempt).toBe(true)});
it('timed selection and whole cases use unapproved installed questions',async()=>{const {repo,questions}=await fresh();const snapshot=await repo.getSnapshot();const result=selectBalancedAssessment({questions,trust:snapshot.contentTrust,reviewItems:[],objectiveStats:[],previousSessionIds:[],attemptedIds:[],requestedCount:5,mode:'timed',useReserved:false,now:new Date(),random:()=>.5});expect(result.questions).toHaveLength(5);const cases=questions.slice(0,3).map(q=>({...q,caseStudy:{id:'case',title:'Case',overview:'Context'}}));expect(selectCaseStudy(cases,'case',{trust:[],draft:false,useReserved:false})).toHaveLength(3)});
it.each(['learn','timed','draft-preview'] as const)('still blocks quarantined and retired content in %s at the transaction boundary',async mode=>{const {repo,questions,service}=await fresh();await repo.db.contentTrust.put({questionId:questions[0].id,revision:1,sourceCheckedAt:new Date().toISOString(),humanReviewedAt:null,reviewer:null,invalidatedAt:new Date().toISOString()});await expect(service.createSession({mode,selectedQuestions:[questions[0]],durationMinutes:mode==='timed'?5:null,releasesReservedIds:[]})).rejects.toThrow(/unavailable|quarantin|invalidat/i);await expect(service.createSession({mode,selectedQuestions:[{...questions[1],status:'retired'}],durationMinutes:mode==='timed'?5:null,releasesReservedIds:[]})).rejects.toThrow(/unavailable|retired/i);expect(await repo.db.sessions.count()).toBe(0)});
