import {it,expect,afterEach} from 'vitest';import {StudyDatabase} from '../../src/storage/database';import {SessionService} from '../../src/sessions/service';import {StudyRepository} from '../../src/storage/repository';import {question,pack} from '../fixtures';
const dbs:StudyDatabase[]=[];afterEach(async()=>{for(const db of dbs.splice(0))await db.delete()});
async function setup(){const db=new StudyDatabase('test-'+crypto.randomUUID());dbs.push(db);const repo=new StudyRepository(db),clock=()=>new Date('2026-10-08T12:00:00Z'),service=new SessionService(repo,clock,()=>.5);const q=question({status:'reviewed',review:{reviewer:'Reviewer',reviewedAt:clock().toISOString(),method:'human'}});await repo.installPack(pack([q]),[]);await repo.setContentTrust({questionId:q.id,revision:1},{questionId:q.id,revision:1,sourceCheckedAt:clock().toISOString(),humanReviewedAt:clock().toISOString(),reviewer:'Reviewer',invalidatedAt:null});return {db,repo,service,q,clock}}
it('answer_and_review_commit_together',async()=>{const {repo,service,q}=await setup();const s=await service.createSession({mode:'learn',selectedQuestions:[q],durationMinutes:null,releasesReservedIds:[]});await service.submitLearnAnswer(s.id,q.id,['a'],'confident',2000);const snap=await repo.getSnapshot();expect(snap.attempts).toHaveLength(1);expect(snap.reviews[0].stage).toBe(1)});
it('two_tab_same_attempt_is_once',async()=>{const {repo,service,q,clock}=await setup();const s=await service.createSession({mode:'learn',selectedQuestions:[q],durationMinutes:null,releasesReservedIds:[]});await Promise.all([service.submitLearnAnswer(s.id,q.id,['a'],'confident',1),new SessionService(repo,clock,()=>.5).submitLearnAnswer(s.id,q.id,['a'],'confident',1)]);expect((await repo.getSnapshot()).attempts).toHaveLength(1);expect((await repo.getSnapshot()).reviews[0].stage).toBe(1)});
it('failed_transaction_preserves_answer_and_progress',async()=>{const {db,repo,service,q}=await setup();const s=await service.createSession({mode:'learn',selectedQuestions:[q],durationMinutes:null,releasesReservedIds:[]});const before=await repo.getSnapshot();db.attempts.hook('creating',()=>{throw Error('QuotaExceededError')});await expect(service.submitLearnAnswer(s.id,q.id,['a'],'confident',1)).rejects.toThrow();expect(await repo.getSnapshot()).toEqual(before)});
it('reload_restores_snapshot_and_option_order',async()=>{const {repo,service,q,clock}=await setup();const s=await service.createSession({mode:'learn',selectedQuestions:[q],durationMinutes:null,releasesReservedIds:[]});await service.saveDraftAnswer(s.id,q.id,{selectedOptionIds:['b'],confidence:'unsure',responseMs:2});const resumed=await new SessionService(repo,clock,()=>0).resumeSession(s.id,clock());expect(resumed.optionOrders).toEqual(s.optionOrders);expect(resumed.answers[q.id].selectedOptionIds).toEqual(['b'])});
it('expired_resume_finalises_once and unanswered_scores_wrong',async()=>{const {repo,service,q}=await setup();const s=await service.createSession({mode:'timed',selectedQuestions:[q],durationMinutes:1,releasesReservedIds:[]});const later=new Date('2026-10-08T12:02:00Z');await service.resumeSession(s.id,later);await service.resumeSession(s.id,later);const snapshot=await repo.getSnapshot();expect(snapshot.attempts).toHaveLength(1);expect(snapshot.attempts[0].correct).toBe(false);expect(snapshot.sessions[0].status).toBe('submitted')});
it('material_correction_preserves_old_snapshot_and_resets_current_review',async()=>{const {repo,service,q}=await setup();const s=await service.createSession({mode:'learn',selectedQuestions:[q],durationMinutes:null,releasesReservedIds:[]});await service.submitLearnAnswer(s.id,q.id,['a'],'confident',1);await repo.installPack(pack([question({revision:2,correctOptionIds:['b']})]),[]);const snapshot=await repo.getSnapshot();expect(snapshot.attempts[0].questionSnapshot.correctOptionIds).toEqual(['a']);expect(snapshot.reviews).toHaveLength(0);expect(snapshot.sessions[0].correctionWarnings).toHaveLength(1)});
it('draft_preview_has_no_scored_review',async()=>{const {repo,service}=await setup();const q=question();const s=await service.createSession({mode:'draft-preview',selectedQuestions:[q],durationMinutes:null,releasesReservedIds:[]});await service.submitLearnAnswer(s.id,q.id,['a'],'confident',1);expect((await repo.getSnapshot()).reviews).toHaveLength(0)});
