import {afterEach,expect,it} from 'vitest';
import {StudyDatabase} from '../../src/storage/database';
import {StudyRepository} from '../../src/storage/repository';
import {SessionService} from '../../src/sessions/service';
import {question} from '../fixtures';
const databases:StudyDatabase[]=[];
const now=new Date('2026-10-08T12:00:00Z');
function setup(){const db=new StudyDatabase(`timed-draft-${crypto.randomUUID()}`);databases.push(db);const repo=new StudyRepository(db);return {db,repo,service:new SessionService(repo,()=>now)}}
afterEach(async()=>{for(const db of databases.splice(0))await db.delete()});
it('sets a draft-preview deadline and prevents learning submission before finalisation',async()=>{const {service,repo}=setup(),q=question();const s=await service.createSession({mode:'draft-preview',selectedQuestions:[q],durationMinutes:10,releasesReservedIds:[]});expect(s.deadlineAt).toBe('2026-10-08T12:10:00.000Z');await expect(service.submitLearnAnswer(s.id,q.id,['a'],'confident',1)).rejects.toThrow(/learning answer/i);expect((await repo.getSnapshot()).attempts).toHaveLength(0)});
it('finalises timed draft answers once, retaining preview mode without changing reviews',async()=>{const {service,repo}=setup(),q=question();await repo.db.reviews.put({questionId:q.id,revision:1,stage:2,dueAt:'2026-10-09T12:00:00Z',misconception:false});const reviews=await repo.db.reviews.toArray();const s=await service.createSession({mode:'draft-preview',selectedQuestions:[q],durationMinutes:10,releasesReservedIds:[]});await service.saveDraftAnswer(s.id,q.id,{selectedOptionIds:['a'],confidence:'confident',responseMs:500});const result=await service.finaliseTimedSession(s.id,now);expect(result.correct).toBe(1);expect(await service.finaliseTimedSession(s.id,now)).toEqual(result);const snap=await repo.getSnapshot();expect(snap.attempts).toHaveLength(1);expect(snap.attempts[0].mode).toBe('draft-preview');expect(snap.reviews).toEqual(reviews)});
it('expires and resumes an unanswered timed preview with no reviewed progress',async()=>{const {service,repo}=setup(),q=question();const s=await service.createSession({mode:'draft-preview',selectedQuestions:[q],durationMinutes:1,releasesReservedIds:[]});const later=new Date('2026-10-08T12:02:00Z');const resumed=await service.resumeSession(s.id,later);expect(resumed.status).toBe('submitted');await service.resumeSession(s.id,later);const snap=await repo.getSnapshot();expect(snap.attempts).toHaveLength(1);expect(snap.attempts[0]).toMatchObject({mode:'draft-preview',correct:false,selectedOptionIds:[]});expect(snap.reviews).toHaveLength(0)});
it('rejects new draft writes when a preview deadline has elapsed',async()=>{const {service,repo}=setup(),q=question();const s=await service.createSession({mode:'draft-preview',selectedQuestions:[q],durationMinutes:1,releasesReservedIds:[]});const late=new SessionService(repo,()=>new Date('2026-10-08T12:02:00Z'));await expect(late.saveDraftAnswer(s.id,q.id,{selectedOptionIds:['a'],confidence:'confident',responseMs:1})).rejects.toThrow(/finished/i)});
it.each([0,-1,241,Number.NaN,Number.POSITIVE_INFINITY])('rejects invalid timed preview duration %s',async duration=>{const {service}=setup();await expect(service.createSession({mode:'draft-preview',selectedQuestions:[question()],durationMinutes:duration,releasesReservedIds:[]})).rejects.toThrow(/duration/i)});
it('keeps untimed draft learning available and rejects over-counted draft answers',async()=>{const {service}=setup(),q=question();const s=await service.createSession({mode:'draft-preview',selectedQuestions:[q],durationMinutes:null,releasesReservedIds:[]});expect(s.deadlineAt).toBeNull();await expect(service.saveDraftAnswer(s.id,q.id,{selectedOptionIds:['a','b'],confidence:'unknown',responseMs:0})).rejects.toThrow(/answer/i);const a=await service.submitLearnAnswer(s.id,q.id,['a'],'confident',10);expect(a.mode).toBe('draft-preview')});
it('preserves incomplete matching assignment order across reload',async()=>{const {service,repo}=setup(),q=question({type:'matching',requiredSelections:3,correctOptionIds:['c','a','b'],matchPrompts:[{id:'p1',text:'One'},{id:'p2',text:'Two'},{id:'p3',text:'Three'}]});const s=await service.createSession({mode:'draft-preview',selectedQuestions:[q],durationMinutes:10,releasesReservedIds:[]});await service.saveDraftAnswer(s.id,q.id,{selectedOptionIds:['c','a'],confidence:'unsure',responseMs:1});expect((await new SessionService(repo,()=>now).resumeSession(s.id,now)).answers[q.id].selectedOptionIds).toEqual(['c','a']);await expect(service.saveDraftAnswer(s.id,q.id,{selectedOptionIds:['a','a'],confidence:'unknown',responseMs:1})).rejects.toThrow(/answer/i)});
it('rolls back timed draft finalisation when writing attempts fails',async()=>{const {service,repo,db}=setup(),q=question();const s=await service.createSession({mode:'draft-preview',selectedQuestions:[q],durationMinutes:10,releasesReservedIds:[]});await service.saveDraftAnswer(s.id,q.id,{selectedOptionIds:['a'],confidence:'confident',responseMs:20});const before=await repo.getSnapshot();const fail=()=>{throw Error('storage unavailable')};db.attempts.hook('creating',fail);await expect(service.finaliseTimedSession(s.id,now)).rejects.toThrow(/storage unavailable/);expect(await repo.getSnapshot()).toEqual(before);db.attempts.hook('creating').unsubscribe(fail);expect((await service.finaliseTimedSession(s.id,now)).correct).toBe(1)});
it('does not advance a timed preview through learning submissions',async()=>{const {service,repo}=setup();const s=await service.createSession({mode:'draft-preview',selectedQuestions:[question(),question({id:'q2'})],durationMinutes:10,releasesReservedIds:[]});const unchanged=await service.advanceSession(s.id);expect(unchanged.currentIndex).toBe(0);expect(unchanged.status).toBe('active');expect((await repo.getSnapshot()).attempts).toHaveLength(0)});
