import {useState} from 'react';
import type {StudyRepository} from '../../storage/repository';
import type {DatabaseSnapshot} from '../../sessions/types';
import {workspaceValue,writeWorkspace} from '../../storage/workspace';
import {parseSourceReport,applySourceReport,type SourceReport} from '../../content/freshness';
import {blueprintImpact,type BlueprintDiff} from '../../content/blueprint-diff';
import {sectionImpact} from '../../content/section-diff';
import currentBlueprint from '../../../content/blueprints/history/az104-2026-10-08.observation.json';
import {sourceRows,parseEvidenceReport,resolutionValue,normaliseResolutions,type Resolution,type EvidenceReport,type BlueprintReport} from './model';
import './sources.css';
const KEY='evidence:source-resolutions';
export function SourceDashboard({repository,snapshot}:{repository:StudyRepository;snapshot:DatabaseSnapshot}){
 const [localSnapshot,setLocalSnapshot]=useState<DatabaseSnapshot|null>(null),[selected,setSelected]=useState(''),[filter,setFilter]=useState('all'),[query,setQuery]=useState('');
 const [report,setReport]=useState<EvidenceReport|null>(null),[sourceReport,setSourceReport]=useState<SourceReport|null>(null),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [resolutions,setResolutions]=useState<Record<string,Resolution>>(()=>normaliseResolutions(workspaceValue(snapshot,KEY,{}))),[findingState,setFindingState]=useState<Resolution['state']>('open'),[reason,setReason]=useState('');
 const view=localSnapshot??snapshot,rows=sourceRows(view).map(row=>{const observed=report?.kind==='sections'?report.entries.find(e=>e.referenceId===row.referenceId):null;return observed?{...row,state:observed.status==='changed'?'changed' as const:observed.status==='unavailable'?'unavailable' as const:row.state,requiresCorrection:observed.status==='changed'}:row}),questions=[...view.packs.flatMap(p=>p.questions),...view.sessions.flatMap(s=>s.questionSnapshots)],visible=rows.filter(r=>(filter==='all'||filter==='stale'&&r.stale||filter==='changed'&&r.requiresCorrection||filter==='unavailable'&&r.state==='unavailable')&&(`${r.referenceId} ${r.url}`.toLowerCase().includes(query.toLowerCase()))),row=visible.find(r=>r.referenceId===selected)??visible[0];
 const section=report?.kind==='sections'?report.entries.find(e=>e.referenceId===row?.referenceId):null,blueprint=report?.kind==='blueprint'?report:currentBlueprint as BlueprintReport;
 const resolutionKey=row?`${row.referenceId}:${section?.contentHash??row.hash??'missing'}`:'',existing=resolutions[resolutionKey];
 const impact=row&&section?sectionImpact(row.referenceId,section.changes,questions,row.url):[];
 const choose=(id:string)=>{const next=rows.find(r=>r.referenceId===id),hash=report?.kind==='sections'?report.entries.find(e=>e.referenceId===id)?.contentHash:null,note=resolutions[`${id}:${hash??next?.hash??'missing'}`];setSelected(id);setFindingState(note?.state??'open');setReason(note?.reason??'');setError('');setMessage('')};
 const load=async(file:File)=>{setError('');setMessage('');setConfirm(false);setReport(null);setSourceReport(null);if(file.size>8_000_000)throw Error('Report exceeds 8 MB');const text=await file.text(),value=JSON.parse(text);if(value.kind)setReport(parseEvidenceReport(text));else setSourceReport(parseSourceReport(text));setFindingState('open');setReason('')};
 const exportReport=()=>{const payload={version:1,generatedAt:new Date().toISOString(),scope:'Personal source observations and resolution notes; no approval authority.',sourceChecks:view.sourceChecks,blueprint,sectionReport:report?.kind==='sections'?report:null,sourceReport,resolutions},url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='az104-source-review.json';link.click();URL.revokeObjectURL(url)};
 return <div className="source-dashboard"><div className="page-title"><span className="eyebrow">Official sources and explicit uncertainty</span><h1>Source evidence</h1><p>Retrieval never proves an answer is correct. A hash change needs section review; a temporary outage preserves the existing factual review.</p></div>
 <section className="card"><h2>Evidence health</h2><p>{rows.length} sources · {rows.filter(r=>r.stale).length} due for a 30-day check · {rows.filter(r=>r.requiresCorrection).length} flagged changes · {rows.filter(r=>r.state==='unavailable').length} temporary outages.</p><p className="notice">Changes, stale citations, draft explanations, missing baselines, and vague section mappings remain uncertain until you inspect official evidence. Resolution notes record your reasoning; approval happens separately in <a href="#/review">Content review</a>.</p>
 <div className="source-controls"><label>Search sources<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Reference ID or official URL"/></label><label>Source filter<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All sources</option><option value="stale">Check due</option><option value="changed">Changed</option><option value="unavailable">Unavailable</option></select></label></div>
 <label>Source<select value={row?.referenceId??''} onChange={e=>choose(e.target.value)}>{visible.map(r=><option key={r.referenceId} value={r.referenceId}>{r.referenceId} · {r.state}{r.stale?' · check due':''}</option>)}</select></label>{!visible.length&&<p>No sources match these filters.</p>}
 {row&&visible.length>0&&<><h3>{row.referenceId}</h3><a href={row.url} target="_blank" rel="noreferrer">Open official source</a><dl><dt>Last retrieval</dt><dd>{row.checkedAt??'No retrieval baseline'}{row.ageDays!==null?` · ${row.ageDays} days ago`:''}</dd><dt>URL check</dt><dd>{row.state}</dd><dt>Content SHA-256</dt><dd className="source-hash">{row.hash??'Missing hash baseline; compare before assuming unchanged.'}</dd><dt>Linked approved revisions</dt><dd>{row.reviewedCount}</dd></dl><h3>Affected question revisions</h3>{row.affected.length?<ul>{row.affected.map(id=><li key={id}><a href={`#/library?query=${encodeURIComponent(id.split('@')[0])}`}>{id}</a></li>)}</ul>:<p>No question cites this source.</p>}
 {section&&<><h3>Section evidence comparison: {section.status}</h3><p>Observed {section.checkedAt}. Observation SHA-256: <span className="source-hash">{section.contentHash??'unavailable'}</span>.</p>{section.status==='unavailable'&&<p>Retrieval failed. Baseline and factual approval are preserved. Retry retrieval before drawing a conclusion.</p>}{section.status==='baseline-missing'&&<p>No preserved section baseline exists; this observation cannot prove the wording is unchanged.</p>}{section.changes.map((change,i)=><details key={`${change.sectionId}-${i}`}><summary>{change.title} · {change.kind}</summary><div className="source-comparison"><div><h4>Preserved baseline</h4><p>{change.before??'New section'}</p></div><div><h4>Retrieved observation</h4><p>{change.after??'Section removed or renamed'}</p></div></div></details>)}{impact.length>0&&<><h4>Answer and explanation impact</h4><ul>{impact.map(i=><li key={`${i.questionId}@${i.revision}`}>{i.questionId}@{i.revision}: {i.optionIds.length?`options ${i.optionIds.join(', ')}`:'question citation'}{i.summary?', summary explanation':''}. {i.sectionMatch?'Cited section matches.':'Broad or ambiguous citation; inspect the full official article.'}</li>)}</ul></>}</>}
 <label>Finding state<select value={findingState} onChange={e=>setFindingState(e.target.value as Resolution['state'])}><option value="open">Open</option><option value="investigating">Investigating</option><option value="resolved">Resolved with reasoning</option></select></label><label>Resolution reasoning<textarea value={reason} maxLength={10000} onChange={e=>setReason(e.target.value)} placeholder="Record the evidence, explanation impact, uncertainty and any separate correction decision."/></label>{existing&&<p>Saved finding: {existing.state}. {existing.reason}</p>}<button className="secondary" disabled={busy} onClick={()=>{setBusy(true);setError('');void Promise.resolve().then(()=>{const note=resolutionValue(findingState,reason),next={...resolutions,[resolutionKey]:note};return writeWorkspace(repository,KEY,next).then(()=>{setResolutions(next);setMessage('Resolution note saved. Factual approval is unchanged.')})}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}>Save resolution note</button></>}
 </section>
 <section className="card"><h2>Versioned AZ-104 blueprint</h2><p>Preserved baseline: {blueprint.baselineId}. Retrieved {blueprint.generatedAt}. Published effective date: {blueprint.candidate?.effectiveDate??'Unavailable'}.</p><p>Detection: {blueprint.status}. Existing blueprint mappings, questions and session snapshots remain unchanged.</p>{blueprint.error&&<p>{blueprint.error}</p>}{blueprint.changes.map((c,i)=><details key={i}><summary>{c.kind} · {c.objectiveId??c.domainId??'Entire blueprint'}</summary><p>{c.reason}</p><div className="source-comparison"><pre>{JSON.stringify(c.before,null,2)}</pre><pre>{JSON.stringify(c.after,null,2)}</pre></div></details>)}{blueprint.status==='changed'&&<p>Potentially affected revisions: {blueprintImpact(blueprint as BlueprintDiff,questions).join(', ')||'No existing mapping matches; review additions manually.'}</p>}<a href={blueprint.source} target="_blank" rel="noreferrer">Open the official current study guide</a><p className="fine-print">Version detection compares measured skills and weights. It never silently remaps objectives or approves changed wording.</p></section>
 <section className="card"><h2>Retrieved report review</h2><p>Scheduled retrieval produces report artifacts. Import blueprint, section or original source-check JSON to inspect observations offline. Nothing applies automatically.</p><label>Retrieved report JSON<input type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];if(file)void load(file).catch(err=>setError(err.message))}}/></label>{report&&<p>Loaded {report.kind} report from {report.generatedAt}. {report.kind==='sections'?`${report.entries.filter(e=>e.status==='changed').length} changed sources; ${report.entries.filter(e=>e.status==='unavailable').length} outages.`:`${report.changes.length} blueprint differences.`}</p>}
 {sourceReport&&<><p>{sourceReport.entries.filter(e=>e.status==='changed').length} changed · {sourceReport.entries.filter(e=>e.status==='unavailable').length} unavailable · {sourceReport.entries.filter(e=>e.status==='baseline-missing').length} missing baselines.</p><ul>{sourceReport.entries.filter(e=>e.status!=='unchanged').map(e=><li key={e.referenceId}>{e.referenceId}: {e.status}. {e.observed.evidenceSummary}</li>)}</ul><label className="check-setting"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>I reviewed the report. Pause linked approved revisions for factual changes; preserve review during outages.</label><button className="secondary" disabled={!confirm||busy} onClick={()=>{setBusy(true);setError('');void applySourceReport(repository,sourceReport,true).then(async result=>{setLocalSnapshot(await repository.getSnapshot());setMessage(`${result.quarantined.length} revisions paused; ${result.unavailable} temporary outages. No factual approval was granted.`);setConfirm(false);setSourceReport(null)}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}>Apply reviewed source report</button></>}
 <button className="secondary" onClick={exportReport}>Export source review notes</button><p className="fine-print">Section/blueprint reports are review aids. A whole-page HTML hash can change because of page layout. Inspect changed claims before deciding whether a question correction is needed.</p></section>{error&&<p role="alert">{error}</p>}<p role="status">{message}</p></div>
}
