import {useState} from 'react';
import type {Blueprint,Question} from '../../content/types';
import type {SessionMode} from '../../sessions/types';
export interface PracticeOptions{timed:boolean;objectiveId?:string;difficulty?:Question['difficulty'];caseStudyId?:string}
export interface PracticeCase{id:string;title:string;domainId:string;requiresReserve?:boolean;previewAvailable?:boolean;approvedAvailable?:boolean}
export function Practice({blueprint,initialDomain='',initialObjective='',available,draftAvailable,cases=[],onStart}:{blueprint:Blueprint;initialDomain?:string;initialObjective?:string;available:number;draftAvailable:number;cases?:PracticeCase[];onStart:(mode:SessionMode,count:number,domain:string,duration:number,useReserved:boolean,options?:PracticeOptions)=>Promise<void>}){
 const [mode,setMode]=useState<SessionMode>('learn'),[count,setCount]=useState(10),[domain,setDomain]=useState(initialDomain),[objective,setObjective]=useState(initialObjective),[duration,setDuration]=useState(30),[reserved,setReserved]=useState(false),[draftTimed,setDraftTimed]=useState(false),[format,setFormat]=useState('standard'),[caseId,setCaseId]=useState(''),[difficulty,setDifficulty]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const timed=mode==='timed'||draftTimed||format==='case-study',availableCases=cases.filter(c=>!domain||c.domainId===domain);const usable=(c:PracticeCase)=>(mode==='draft-preview'?c.previewAvailable??true:c.approvedAvailable??true)&&(!c.requiresReserve||reserved);const usableCases=availableCases.filter(usable),selectedCase=usableCases.find(c=>c.id===caseId)??usableCases[0];
 return <><div className="page-title"><span className="eyebrow">Build understanding</span><h1>Make practice<br/><em>work for you.</em></h1><p>Choose a short session or take your time with a topic.</p></div><section className="card"><h2>Your next session</h2><div className="mode-grid">{([['learn','Learn','Feedback after every answer'],['timed','Timed practice','Feedback when you finish'],['draft-preview','Draft preview','Explore unapproved questions']] as const).map(([m,label,desc])=><button className={'mode-card '+(mode===m?'active':'')} key={m} onClick={()=>{setMode(m);setCount(m==='timed'?20:10);setDraftTimed(false);if(m==='timed')setDuration(30)}}><strong>{label}</strong><small>{desc}</small></button>)}</div>
 <label className="field">Study area<select value={domain} onChange={e=>{setDomain(e.target.value);setObjective('')}}><option value="">All domains</option>{blueprint.domains.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label>
 <label className="field">Objective<select value={objective} onChange={e=>setObjective(e.target.value)}><option value="">All objectives</option>{blueprint.domains.filter(d=>!domain||d.id===domain).flatMap(d=>d.objectives).map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label>
 <label className="field">Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="">All levels</option><option value="foundation">Foundation</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced scenarios</option></select></label>
 <label className="field">Practice format<select value={format} onChange={e=>setFormat(e.target.value)}><option value="standard">Mixed questions</option><option value="case-study">Linked case study</option></select></label>
 {format==='case-study'?<><label className="field">Case study<select value={selectedCase?.id??''} onChange={e=>setCaseId(e.target.value)}>{availableCases.map(c=><option key={c.id} value={c.id} disabled={!usable(c)}>{c.title}</option>)}</select></label><p className="muted">{!selectedCase&&"No case is available with these settings. Use draft preview for unapproved content or opt into reserved questions. "}The entire case is selected together. Explanations appear after final submission. Difficulty and objective filters apply to mixed sessions.</p></>:<fieldset className="session-length"><legend>Questions</legend>{(timed?[20,40]:[5,10,20]).map(n=><label key={n} className={count===n?'active':''}><input type="radio" name="session-length" checked={count===n} onChange={()=>{setCount(n);if(timed)setDuration(n===40?60:30)}}/>{n}</label>)}</fieldset>}
 {mode==='draft-preview'&&format!=='case-study'&&<label className="check-setting"><input type="checkbox" checked={draftTimed} onChange={e=>{setDraftTimed(e.target.checked);setCount(e.target.checked?20:10)}}/>Use a practice timer with feedback at the end</label>}
 {timed&&<label className="field">Practice duration (minutes)<input type="number" min="1" max="240" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label>}
 <label className="check-setting"><input type="checkbox" checked={reserved} onChange={e=>setReserved(e.target.checked)}/>Include fresh reserved assessment questions</label><p className="muted">Using reserved questions releases them into future practice. These are original practice formats aligned with the published skills, not a prediction of Microsoft’s exam questions.</p>
 <p className="notice">{mode==='draft-preview'?draftAvailable:available} questions installed before topic and reserve filtering. Linked cases are selected separately. Sessions shorten when there are fewer unique questions.</p>{mode==='draft-preview'&&<p className="notice warning">Draft preview: unapproved content. Answers are saved separately and do not count towards your progress.</p>}{error&&<p role="alert" className="error">{error}</p>}<button className="primary full" disabled={busy||(format==='case-study'&&!selectedCase)} onClick={async()=>{setBusy(true);setError('');try{await onStart(mode,count,domain,duration,reserved,{timed,objectiveId:objective||undefined,difficulty:(difficulty||undefined) as Question['difficulty']|undefined,caseStudyId:format==='case-study'?selectedCase?.id:undefined})}catch(e){setError(e instanceof Error?e.message:'Could not start')}finally{setBusy(false)}}}>{busy?'Preparing…':'Start session →'}</button></section></>;
}
