import type {DatabaseSnapshot} from '../../sessions/types';
import {allocations} from '../../study/selection';
import {defaultPracticePreset,preflightPractice,type PracticePreset} from '../../study/catalogue';
import {useState} from 'react';
import type {Blueprint,Question} from '../../content/types';
import type {SessionMode} from '../../sessions/types';
export interface PracticeOptions{timed:boolean;objectiveId?:string;difficulty?:Question['difficulty'];caseStudyId?:string;subskillId?:string;unseenOnly?:boolean;weakPercent?:number;duePercent?:number;unseenRatio?:number;feedbackAtEnd?:boolean;questionId?:string}
export interface PracticeCase{id:string;title:string;domainId:string;requiresReserve?:boolean;previewAvailable?:boolean;approvedAvailable?:boolean}
export function Practice({blueprint,initialDomain='',initialObjective='',available,cases=[],snapshot,initialPreset,initialCaseId='',initialDurationMinutes=30,initialTimed=false,onStart}:{blueprint:Blueprint;initialDomain?:string;initialObjective?:string;available:number;draftAvailable?:number;cases?:PracticeCase[];snapshot?:DatabaseSnapshot;initialPreset?:PracticePreset;initialCaseId?:string;initialDurationMinutes?:number;initialTimed?:boolean;onStart:(mode:SessionMode,count:number,domain:string,duration:number,useReserved:boolean,options?:PracticeOptions)=>Promise<void>}){
 const [mode,setMode]=useState<SessionMode>(initialTimed?'timed':initialPreset?.mode==='timed'?'timed':'learn'),[count,setCount]=useState(initialPreset?.count??10),[domain,setDomain]=useState(initialPreset?.domain??initialDomain),[objective,setObjective]=useState(initialPreset?.objective??initialObjective),[duration,setDuration]=useState(Math.max(1,Math.min(240,Math.round(initialDurationMinutes)||30))),[reserved,setReserved]=useState(initialPreset?.useReserved??false),[format,setFormat]=useState(initialCaseId?'case-study':'standard'),[caseId,setCaseId]=useState(initialCaseId),[difficulty,setDifficulty]=useState<string>(initialPreset?.difficulty??''),[subskill,setSubskill]=useState(initialPreset?.subskill??''),[unseen,setUnseen]=useState(initialPreset?.unseenOnly??false),[weak,setWeak]=useState(initialPreset?.weakPercent??40),[due,setDue]=useState(initialPreset?.duePercent??25),[caseTimed,setCaseTimed]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const timed=mode==='timed'||(format==='case-study'&&caseTimed),availableCases=cases.filter(c=>!domain||c.domainId===domain);const usable=(c:PracticeCase)=>(c.previewAvailable??true)&&(!c.requiresReserve||reserved);const usableCases=availableCases.filter(usable),selectedCase=usableCases.find(c=>c.id===caseId)??usableCases[0];
 const preset={...defaultPracticePreset(),mode,count,domain,objective,subskill,difficulty:difficulty as PracticePreset['difficulty'],useReserved:reserved,unseenOnly:unseen,weakPercent:weak,duePercent:due,unseenRatio:initialPreset?.unseenRatio};const preflight=snapshot?preflightPractice({...snapshot,packs:snapshot.packs.map(p=>({...p,questions:p.questions.filter(q=>!q.caseStudy)}))},preset,new Date(),{timed}):null;
 return <><div className="page-title"><span className="eyebrow">Build understanding</span><h1>Make practice<br/><em>work for you.</em></h1><p>Choose a short session or take your time with a topic.</p></div><section className="card"><h2>Your next session</h2><div className="mode-grid">{([['learn','Learn','Feedback after every answer'],['timed','Timed practice','Feedback when you finish']] as const).map(([m,label,desc])=><button className={'mode-card '+(mode===m?'active':'')} key={m} onClick={()=>{setMode(m);setCount(m==='timed'?20:initialPreset?.count??10);if(m==='timed')setDuration(30)}}><strong>{label}</strong><small>{desc}</small></button>)}</div>
 <label className="field">Study area<select value={domain} onChange={e=>{setDomain(e.target.value);setObjective('');setSubskill('')}}><option value="">All domains</option>{blueprint.domains.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label>
 <label className="field">Objective<select value={objective} onChange={e=>{setObjective(e.target.value);setSubskill('')}}><option value="">All objectives</option>{blueprint.domains.filter(d=>!domain||d.id===domain).flatMap(d=>d.objectives).map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label>
 <label className="field">Specific skill<select value={subskill} onChange={e=>setSubskill(e.target.value)}><option value="">All matching skills</option>{blueprint.domains.filter(d=>!domain||d.id===domain).flatMap(d=>d.objectives).filter(o=>!objective||o.id===objective).flatMap(o=>o.subObjectives.map((title,i)=><option key={o.id+'.'+(i+1)} value={o.id+'.'+(i+1)}>{title}</option>))}</select></label>
 <label className="field">Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="">All levels</option><option value="foundation">Foundation</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced scenarios</option></select></label>
 <label className="field">Practice format<select value={format} onChange={e=>setFormat(e.target.value)}><option value="standard">Mixed questions</option><option value="case-study">Linked case study</option></select></label>
 {format==='case-study'?<>{mode!=='timed'&&<label className="check-setting"><input type="checkbox" checked={caseTimed} onChange={e=>setCaseTimed(e.target.checked)}/>Time this case (otherwise self-paced)</label>}<label className="field">Case study<select value={selectedCase?.id??''} onChange={e=>setCaseId(e.target.value)}>{availableCases.map(c=><option key={c.id} value={c.id} disabled={!usable(c)}>{c.title}</option>)}</select></label><p className="muted">{!selectedCase&&"No case is available with these settings. Choose another study area or include reserved questions. "}The entire case is selected together. Explanations appear after final submission. Difficulty and objective filters apply to mixed sessions.</p></>:<fieldset className="session-length"><legend>Questions</legend>{(timed?[5,20,40]:[5,10,20]).map(n=><label key={n} className={count===n?'active':''}><input type="radio" name="session-length" checked={count===n} onChange={()=>{setCount(n);if(timed)setDuration(n===5?5:n===40?60:30)}}/>{n}</label>)}</fieldset>}
 {timed&&<label className="field">Practice duration (minutes)<input type="number" min="1" max="240" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label>}
 <details className="practice-options"><summary>More options</summary><label className="check-setting"><input type="checkbox" checked={reserved} onChange={e=>setReserved(e.target.checked)}/>Include fresh reserved assessment questions</label><p className="muted">Using reserved questions releases them into future practice. These are original practice formats aligned with the published skills, not a prediction of Microsoft’s exam questions.</p>
 {format==='standard'&&<><label className="check-setting"><input type="checkbox" checked={unseen} onChange={e=>setUnseen(e.target.checked)}/>New questions only — never attempted at this revision</label><label className="field">Weak topics: {weak}%<input type="range" min="0" max="100" value={weak} onChange={e=>{const v=Number(e.target.value);setWeak(v);setDue(Math.min(due,100-v))}}/></label><label className="field">Due reviews: {due}%<input type="range" min="0" max={100-weak} value={due} onChange={e=>setDue(Number(e.target.value))}/></label><p className="muted">The remaining mix balances unseen questions and reinforcement. Mixed timed assessments use blueprint domain targets.</p>{preflight&&<section aria-label="Session preview"><h3>Before you start</h3><p className="muted">Questions and selected-format counts are a preview. The session can choose different matching questions; availability and exclusions use the same rules.</p>{timed&&<div className="exhibit-scroll"><table><caption>Planned assessment distribution</caption><thead><tr><th>Domain</th><th>Published range</th><th>Target</th><th>Available selection</th></tr></thead><tbody>{blueprint.domains.filter(d=>!domain||d.id===domain).map((d,i)=>{const ds=blueprint.domains.filter(d=>!domain||d.id===domain),weights=ds.map(d=>(d.weight[0]+d.weight[1])/2),total=weights.reduce((a,b)=>a+b,0),targets=allocations(count,weights.map(w=>w/total));return <tr key={d.id}><th scope="row">{d.title}</th><td>{d.weight.join("–")}%</td><td>{targets[i]}</td><td>{preflight.questions.filter(q=>q.domainId===d.id).length}</td></tr>})}</tbody></table><p>Targets follow the public skills guide. Limited question pools can change the actual distribution.</p></div>}<p>{preflight.availableCount} eligible matches · {preflight.selectedCount} selected</p><p>{Object.entries(preflight.selectedFormatCounts).map(([format,n])=>`${n} ${format}`).join(' · ')}</p>{preflight.shortages.map(reason=><p className="notice" key={reason}>{reason}</p>)}<details><summary>Why these questions?</summary>{preflight.explanation.map(text=><p key={text}>{text}</p>)}{preflight.questions.map(q=><p key={q.id}>{q.id}: {snapshot?.reviews.some(r=>r.questionId===q.id&&r.misconception)?'misconception review':snapshot?.reviews.some(r=>r.questionId===q.id&&Date.parse(r.dueAt)<=Date.now())?'due review':snapshot?.attempts.some(a=>a.questionId===q.id&&a.questionRevision===q.revision)?'reinforcement':'unseen revision'}</p>)}</details></section>}</>}
 {snapshot&&<section aria-label="Sources before practice"><h3>Source health before practice</h3>{(()=>{const relevant=snapshot.packs.flatMap(p=>p.questions).filter(q=>(!domain||q.domainId===domain)&&(!objective||q.objectiveId===objective)),ids=new Set(relevant.flatMap(q=>q.references.map(r=>r.id))),problem=snapshot.sourceChecks.filter(c=>ids.has(c.referenceId)&&(c.result!=='checked'||Date.now()-Date.parse(c.checkedAt)>=30*86400000));return <><p>{problem.length?`${problem.length} source records in this study area need attention. Changed evidence is quarantined from practice; overdue or unavailable evidence needs checking.`:'Installed source records for this study area have no recorded change, outage or overdue check.'}</p><a className="button secondary" href="#/sources">Inspect Microsoft Learn source health</a></>})()}</section>}
 </details><p className="muted">{format==='standard'&&preflight?`${preflight.selectedCount} questions ready${preflight.selectedCount<count?` (requested ${count}; try broader filters for more)`:''}.`:`${available} questions available for practice.`}</p>{error&&<p role="alert" className="error">{error}</p>}<button className="primary full" disabled={busy||(format==='case-study'?!selectedCase:preflight?.selectedCount===0)} onClick={async()=>{setBusy(true);setError('');try{await onStart(mode,count,domain,duration,reserved,{timed,feedbackAtEnd:format==='case-study',subskillId:subskill||undefined,unseenOnly:unseen,weakPercent:weak,duePercent:due,unseenRatio:initialPreset?.unseenRatio,objectiveId:objective||undefined,difficulty:(difficulty||undefined) as Question['difficulty']|undefined,caseStudyId:format==='case-study'?selectedCase?.id:undefined})}catch(e){setError(e instanceof Error?e.message:'Could not start')}finally{setBusy(false)}}}>{busy?'Preparing…':'Start session →'}</button></section></>;
}
