import {useEffect,useRef,useState} from 'react';import type {Question} from '../../content/types';import type {Confidence} from '../../study/review';import {canSubmit} from '../../study/scoring';import type {SessionAnswer} from '../../sessions/types';
export function QuestionView({question:q,optionOrder,initial,onSubmit,onDraft,onSaveQueued,submitLabel='Submit answer'}:{question:Question;optionOrder?:string[];initial?:SessionAnswer;onSubmit:(ids:string[],confidence:Confidence,responseMs:number)=>Promise<unknown>;onDraft?:(answer:SessionAnswer)=>Promise<void>;onSaveQueued?:(write:Promise<void>)=>unknown;submitLabel?:string}){
 const [ids,setIds]=useState(initial?.selectedOptionIds??[]),[confidence,setConfidence]=useState<Confidence>(initial?.confidence??'unknown'),[busy,setBusy]=useState(false),[error,setError]=useState('');const heading=useRef<HTMLHeadingElement>(null);useEffect(()=>{heading.current?.focus()},[q.id]);const elapsed=useRef(initial?.responseMs??0),last=useRef(performance.now()),queue=useRef(Promise.resolve());
 useEffect(()=>{function visibility(){const now=performance.now();if(document.hidden){elapsed.current+=now-last.current;last.current=0}else last.current=now}document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility)},[]);
 const ms=()=>Math.round(elapsed.current+(last.current?performance.now()-last.current:0));
 function draft(next:string[],c:Confidence){if(onDraft){const write=queue.current.then(()=>onDraft({selectedOptionIds:next,confidence:c,responseMs:ms()}));onSaveQueued?.(write);queue.current=write.catch(e=>setError(e.message))}}
 async function submit(){setBusy(true);setError('');try{await queue.current;await onSubmit(ids,confidence,ms())}catch(e){setError(e instanceof Error?e.message:'Answer not saved. Retry.')}finally{setBusy(false)}}
 const options=(optionOrder??q.options.map(o=>o.id)).map(id=>q.options.find(o=>o.id===id)!);
 return <section className="question-panel"><span className="eyebrow">{q.type==='multiple'?`Choose ${q.requiredSelections}`:'Choose one answer'} · {q.difficulty}</span><p className="scenario">{q.scenario}</p><h2 ref={heading} tabIndex={-1}>{q.prompt}</h2><fieldset disabled={busy} className="answers"><legend className="sr-only">Answer choices</legend>{options.map((o,n)=><label key={o.id} className={'answer '+(ids.includes(o.id)?'selected':'')}><input type={q.type==='single'?'radio':'checkbox'} name="answer" checked={ids.includes(o.id)} onChange={()=>{const next=q.type==='single'?[o.id]:ids.includes(o.id)?ids.filter(id=>id!==o.id):[...ids,o.id];setIds(next);draft(next,confidence)}}/><span className="answer-letter" aria-hidden="true">{String.fromCharCode(65+n)}</span><span>{o.text}</span></label>)}</fieldset><fieldset disabled={busy} className="confidence"><legend>How sure are you? <small>Optional</small></legend>{(['confident','unsure','guessed'] as const).map(c=><label key={c} className={confidence===c?'active':''}><input type="radio" name="confidence" checked={confidence===c} onChange={()=>{setConfidence(c);draft(ids,c)}}/>{c[0].toUpperCase()+c.slice(1)}</label>)}</fieldset>{error&&<p className="notice error" role="alert">{error}</p>}<button className="primary full" disabled={!canSubmit(q,ids)||busy} onClick={()=>void submit()}>{busy?'Saving…':error?'Retry save':submitLabel}</button></section>
}
