import {QuestionContext} from './Exhibits';import {useEffect,useRef,useState} from 'react';import type {Question} from '../../content/types';import type {Confidence} from '../../study/review';import {canSubmit} from '../../study/scoring';import type {SessionAnswer} from '../../sessions/types';
export function QuestionView({question:q,optionOrder,initial,onSubmit,onDraft,onSaveQueued,submitLabel='Submit answer'}:{question:Question;optionOrder?:string[];initial?:SessionAnswer;onSubmit:(ids:string[],confidence:Confidence,responseMs:number)=>Promise<unknown>;onDraft?:(answer:SessionAnswer)=>Promise<void>;onSaveQueued?:(write:Promise<void>)=>unknown;submitLabel?:string}){
 const [ids,setIds]=useState(initial?.selectedOptionIds??[]),[confidence,setConfidence]=useState<Confidence>(initial?.confidence??'unknown'),[busy,setBusy]=useState(false),[error,setError]=useState('');const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);const heading=useRef<HTMLHeadingElement>(null);useEffect(()=>{heading.current?.focus()},[q.id]);const elapsed=useRef(initial?.responseMs??0),last=useRef(performance.now()),queue=useRef(Promise.resolve());
 useEffect(()=>{function visibility(){const now=performance.now();if(document.hidden){elapsed.current+=now-last.current;last.current=0}else last.current=now}document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility)},[]);
 const ms=()=>Math.round(elapsed.current+(last.current?performance.now()-last.current:0));
 function draft(next:string[],c:Confidence){if(onDraft){const write=queue.current.then(()=>onDraft({selectedOptionIds:next,confidence:c,responseMs:ms()}));onSaveQueued?.(write);queue.current=write.catch(e=>{if(mounted.current)setError(e.message)})}}
 async function submit(){setBusy(true);setError('');try{await queue.current;await onSubmit(ids,confidence,ms())}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Answer not saved. Retry.')}finally{if(mounted.current)setBusy(false)}}
 const options=(optionOrder??q.options.map(o=>o.id)).map(id=>q.options.find(o=>o.id===id)!);
 const [stepOrder,setStepOrder]=useState(()=>{const saved=initial?.selectedOptionIds??[];return [...saved,...options.map(o=>o.id).filter(id=>!saved.includes(id))]});
 const [announcement,setAnnouncement]=useState('');
 function choose(next:string[]){setIds(next);draft(next,confidence)}
 function moveStep(index:number,delta:number){const next=[...stepOrder],target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setStepOrder(next);choose(next);setAnnouncement(`Step moved to position ${target+1}.`)}
 function match(index:number,value:string){if(!value){choose(ids.slice(0,index));return}if(ids.some((id,i)=>id===value&&i!==index))return;const next=[...ids];next[index]=value;choose(next)}
 const instruction=q.type==='ordering'?`Order all ${q.options.length} steps`:q.type==='matching'?`Match all ${q.requiredSelections} items`:q.type==='multiple'?`Choose ${q.requiredSelections}`:'Choose one answer';
 return <section className="question-panel"><span className="eyebrow">{instruction} · {q.difficulty}</span><QuestionContext question={q}/><p className="scenario">{q.scenario}</p><h2 ref={heading} tabIndex={-1}>{q.prompt}</h2><fieldset disabled={busy} className="answers"><legend className="sr-only">Answer choices</legend>{q.type==='ordering'?<><p className="format-help">Move steps up or down, then submit your sequence. To keep the displayed sequence, choose Use this order.</p><ol className="ordered-steps" aria-label="Step order">{stepOrder.map((id,index)=>{const option=q.options.find(o=>o.id===id)!;return <li className="ordered-step" key={id}><span className="ordered-step-text">{index+1}. {option.text}</span><span className="order-controls"><button type="button" className="secondary" aria-label={`Move ${option.text} up`} disabled={index===0} onClick={()=>moveStep(index,-1)}>↑ <span className="sr-only">Up</span></button><button type="button" className="secondary" aria-label={`Move ${option.text} down`} disabled={index===stepOrder.length-1} onClick={()=>moveStep(index,1)}>↓ <span className="sr-only">Down</span></button></span></li>})}</ol><p role="status" aria-live="polite">{announcement}</p><button type="button" className="secondary" onClick={()=>choose([...stepOrder])}>Use this order</button></>:q.type==='matching'?<><p className="format-help">Match prompts from top to bottom. Use each answer once. Clearing an earlier match also clears the matches after it.</p>{q.matchPrompts?.map((prompt,index)=><label className="matching-prompt" key={prompt.id}>{prompt.text}<select value={ids[index]??''} disabled={index>ids.length} onChange={event=>match(index,event.target.value)}><option value="">Select an answer</option>{options.map(option=><option key={option.id} value={option.id} disabled={ids.includes(option.id)&&ids[index]!==option.id}>{option.text}</option>)}</select></label>)}</>:options.map((o,n)=><label key={o.id} className={'answer '+(ids.includes(o.id)?'selected':'')}><input type={q.type==='single'?'radio':'checkbox'} name="answer" checked={ids.includes(o.id)} onChange={()=>choose(q.type==='single'?[o.id]:ids.includes(o.id)?ids.filter(id=>id!==o.id):[...ids,o.id])}/><span className="answer-letter" aria-hidden="true">{String.fromCharCode(65+n)}</span><span>{o.text}</span></label>)}</fieldset><fieldset disabled={busy} className="confidence"><legend>How sure are you? <small>Optional</small></legend>{(['confident','unsure','guessed'] as const).map(c=><label key={c} className={confidence===c?'active':''}><input type="radio" name="confidence" checked={confidence===c} onChange={()=>{setConfidence(c);draft(ids,c)}}/>{c[0].toUpperCase()+c.slice(1)}</label>)}</fieldset>{error&&<p className="notice error" role="alert">{error}</p>}<button className="primary full" disabled={!canSubmit(q,ids)||busy} onClick={()=>void submit()}>{busy?'Saving…':error?'Retry save':submitLabel}</button></section>
}
