import {useState} from 'react';
import type {DatabaseSnapshot} from '../../sessions/types';
import type {StudyRepository} from '../../storage/repository';
import {deriveHistory,historyCSV,historyJSON,normaliseFilters,type HistoryFilters} from './model';
import './reports.css';
export function Reports({snapshot}:{repository:StudyRepository;snapshot:DatabaseSnapshot}){
 const [filters,setFilters]=useState<HistoryFilters>(()=>normaliseFilters({}));const [message,setMessage]=useState('');
 const rows=deriveHistory(snapshot,filters),invalid=!!filters.from&&!!filters.to&&filters.from>filters.to;
 const domains=[...new Set(snapshot.sessions.flatMap(s=>s.questionSnapshots.map(q=>q.domainId)))].sort();
 function change(key:keyof HistoryFilters,value:string){setFilters(old=>normaliseFilters({...old,[key]:value}))}
 function download(format:'json'|'csv'){try{const blob=new Blob([format==='json'?historyJSON(rows):historyCSV(rows)],{type:format==='json'?'application/json':'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`az104-personal-history.${format}`;a.click();URL.revokeObjectURL(url);setMessage(`Filtered ${format.toUpperCase()} downloaded.`)}catch{setMessage('Download unavailable in this browser. Try a browser that supports local file downloads.')}}
 return <div className="reports-view"><div className="page-title"><span className="eyebrow">Your saved practice</span><h1>Session history</h1><p>Personal practice records and measured response time do not predict exam readiness.</p></div>
 <section className="card"><h2>Filter history</h2><div className="reports-filters"><label>From date<input type="date" value={filters.from} onChange={e=>change('from',e.target.value)}/></label><label>Through date<input type="date" value={filters.to} onChange={e=>change('to',e.target.value)}/></label><label>Study mode<select value={filters.mode} onChange={e=>change('mode',e.target.value)}><option value="">All modes</option><option value="learn">Learning</option><option value="timed">Timed</option><option value="draft-preview">Draft preview</option></select></label><label>Domain<select value={filters.domain} onChange={e=>change('domain',e.target.value)}><option value="">All domains</option>{domains.map(d=><option key={d}>{d}</option>)}</select></label></div><button onClick={()=>setFilters(normaliseFilters({}))}>Clear filters</button>{invalid&&<p role="alert">Choose an end date on or after the start date.</p>}<p>Dates use the session start date in UTC. A domain filter counts only that domain's questions and answers.</p></section>
 <section className="card"><h2>Filtered personal totals</h2><p>{rows.length} sessions · {rows.reduce((n,r)=>n+r.answered,0)} answered / {rows.reduce((n,r)=>n+r.total,0)} questions</p><p>{(rows.reduce((n,r)=>n+r.responseMs,0)/60000).toFixed(1)} measured response minutes. Missing and zero measurements are excluded; this is recorded answer time, not elapsed study time.</p><p>Answered format exposure: {(['single','multiple','ordering','matching'] as const).map(type=>`${type} ${rows.reduce((n,r)=>n+r.formats[type],0)}`).join(' · ')}.</p><p>Active assessment content, saved answers, historical attempts and measured answer time are withheld across all revisions of its questions. Fresh unreleased reserve content is also withheld. Counts include withheld questions; format exposure and measured time exclude them.</p><div className="button-row"><button disabled={invalid} onClick={()=>download('json')}>Export filtered JSON</button><button disabled={invalid} onClick={()=>download('csv')}>Export filtered CSV</button></div><p>JSON includes visible historical details. CSV contains session summaries and protects spreadsheet formula cells.</p>{message&&<p role="status">{message}</p>}</section>
 <section className="card"><h2>Saved sessions</h2>{rows.length?rows.map(row=><details key={row.id}><summary>{row.startedAt.slice(0,10)} · {row.mode} · {row.status} · {row.answered} / {row.total} answered</summary><p>Session {row.id} · started {row.startedAt} · submitted {row.submittedAt??'Not submitted'}</p>{row.withheld>0&&<p>{row.withheld} question details withheld.</p>}{row.details.map(detail=><article className="report-question" key={`${detail.question.id}@${detail.question.revision}`}><h3>{detail.question.prompt}</h3><p>{detail.question.id} · saved revision {detail.question.revision} · {detail.question.domainId} · {detail.question.type}</p><p>{detail.stale?'Stale revision — historical snapshot only.':'Current question revision.'} Saved content: {detail.eligibility}. {detail.currentEligibleAttempt?'Currently eligible attempt.':'Excluded from current proficiency.'}</p><p>{detail.question.scenario}</p><p>{detail.answer?`Saved answer: ${detail.answer.selectedOptionIds.join(', ')} · confidence ${detail.answer.confidence}`:'Not answered.'}{detail.correct!==null?` · Historical result: ${detail.correct?'correct':'incorrect'}`:''}</p>{detail.answer&&<><ul>{detail.question.options.map(option=><li key={option.id}>{option.id}: {option.text} — {option.explanation}</li>)}</ul><p>{detail.question.summaryExplanation}</p></>}</article>)}</details>):<p>No saved sessions match these filters.</p>}</section></div>;
}
