import {useState} from 'react';
import type {StudyRepository} from '../../storage/repository';
import type {DatabaseSnapshot} from '../../sessions/types';
import {workspaceValue,writeWorkspace} from '../../storage/workspace';
import {blankLab,labComplete,normaliseExplorer,readings,searchObjectives,sourceEvidence,teaching,type ExplorerState,type LabProgress} from './state';
import './explorer.css';
export function Explorer({repository,snapshot}:{repository:StudyRepository;snapshot:DatabaseSnapshot}){
 const [state,setState]=useState(()=>normaliseExplorer(workspaceValue(snapshot,'explorer:progress',{}))),[query,setQuery]=useState(''),[objective,setObjective]=useState(''),[selected,setSelected]=useState(''),[observations,setObservations]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 const objectives=searchObjectives(query,objective),lab=teaching.walkthroughs.find(l=>l.id===selected),progress=lab?(state.labs[lab.id]??blankLab(lab.id)):null;
 async function save(next:ExplorerState){setBusy(true);setStatus('Saving personal explorer progress…');try{const safe=normaliseExplorer(next);await writeWorkspace(repository,'explorer:progress',{...safe});setState(safe);setStatus('Personal explorer progress saved.')}catch{setStatus('Could not save. Your observations remain here; retry saving.')}finally{setBusy(false)}}
 function open(id:string){setSelected(id);setObservations(state.labs[id]?.observations??'');void save({...state,resume:id,labs:{...state.labs,[id]:state.labs[id]??blankLab(id)}})}
 function updateLab(next:LabProgress){if(lab)void save({...state,labs:{...state.labs,[lab.id]:next},resume:lab.id})}
 function citations(ids:string[]){return <ul className="explorer-citations">{ids.map(id=>{const ref=teaching.references.find(r=>r.id===id),proof=sourceEvidence.find(s=>s.id===id);return ref?<li key={id}><a href={ref.url} target="_blank" rel="noreferrer">Microsoft Learn: {id}</a><span> — online; source checked {ref.checkedAt.slice(0,10)}</span>{proof&&<details><summary>Retrieved evidence excerpt (AI-assisted)</summary><p>{proof.evidenceExcerpt}</p></details>}</li>:null})}</ul>}
 return <section className="explorer"><h1>Cited learning explorer</h1><p className="explorer-notice">{teaching.notice}</p><p>Bundled study aids work offline after installation. Microsoft Learn links require internet. Walkthroughs are manual: this app executes no Azure actions. Personal completion is self-reported and does not change scores or certify mastery.</p><p>{Object.keys(state.readings).length} reading objectives self-reported complete; {Object.values(state.labs).filter(labComplete).length} walkthroughs self-reported complete; {state.bookmarks.length} official reading bookmarks.</p><div role="status" aria-live="polite">{status}</div><div className="explorer-tools"><label>Search cited teaching material<input type="search" value={query} maxLength={500} onChange={e=>setQuery(e.target.value)}/></label><label>Objective filter<select value={objective} onChange={e=>setObjective(e.target.value)}><option value="">All objectives</option>{teaching.objectives.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label><button onClick={()=>window.print()}>Print cited revision sheet</button></div>
 <div className="explorer-sheet"><h2>Cited revision sheet</h2><p className="explorer-print-notice">AI-assisted draft — independent human factual review required. Personal completion does not certify mastery.</p>{objectives.length===0&&<p>No teaching material matches these filters.</p>}{objectives.map(o=><article key={o.id}><h3>{o.title}</h3><p>{o.focus}</p>{o.claims.map((claim,i)=><div key={i}><p>{claim.text}</p>{citations(claim.referenceIds)}</div>)}<label className="explorer-tools"><input type="checkbox" disabled={busy} checked={Boolean(state.readings[o.id])} onChange={e=>{const next={...state.readings};if(e.target.checked)next[o.id]=new Date().toISOString();else delete next[o.id];void save({...state,readings:next})}}/>I have read {o.title}</label>{state.readings[o.id]&&<p>Self-reported read: {state.readings[o.id]}</p>}{readings.filter(r=>r.objectiveId===o.id).map(r=><div key={r.url}><a href={r.url} target="_blank" rel="noreferrer">{r.title}</a><p>Online official reading; checked {r.checkedAt.slice(0,10)}.</p><label className="explorer-tools"><input type="checkbox" disabled={busy} checked={state.bookmarks.includes(r.url)} onChange={e=>void save({...state,bookmarks:e.target.checked?[...state.bookmarks,r.url]:state.bookmarks.filter(url=>url!==r.url)})}/>Bookmark {r.title}</label></div>)}</article>)}</div>
 <div className="explorer-tools"><h2>Practical walkthroughs</h2>{state.resume&&!labComplete(state.labs[state.resume]??blankLab(state.resume))&&<button disabled={busy} onClick={()=>open(state.resume)}>Resume {teaching.walkthroughs.find(l=>l.id===state.resume)?.title}</button>}{teaching.walkthroughs.filter(l=>(!objective||l.objectiveId===objective)&&(!query||JSON.stringify(l).toLowerCase().includes(query.toLowerCase().trim()))).map(l=><p key={l.id}><button disabled={busy} onClick={()=>open(l.id)}>Start {l.title}</button>{state.labs[l.id]&&<span> {state.labs[l.id].steps.filter(Boolean).length}/{l.steps.length} steps self-reported; cleanup {state.labs[l.id].cleanup?'checked':'pending'}</span>}</p>)}</div>
 {lab&&progress&&<article className="explorer-lab"><h2>{lab.title}</h2><p>AI-assisted draft manual walkthrough. No resources are deployed by the app.</p><p>{lab.cost}</p><h3>Prerequisites</h3>{lab.prerequisites.map((text,i)=><label key={i} className="explorer-check"><input type="checkbox" disabled={busy} checked={progress.prerequisites[i]} onChange={e=>updateLab({...progress,prerequisites:progress.prerequisites.map((v,j)=>j===i?e.target.checked:v)})}/>Prerequisite {i+1}: {text}</label>)}<h3>Steps</h3>{!progress.prerequisites.every(Boolean)&&<p>Check every prerequisite before tracking steps.</p>}{lab.steps.map((step,i)=><div key={i}><label className="explorer-check"><input type="checkbox" disabled={busy||!progress.prerequisites.every(Boolean)} checked={progress.steps[i]} onChange={e=>updateLab({...progress,steps:progress.steps.map((v,j)=>j===i?e.target.checked:v)})}/>Step {i+1}: {step.text}</label>{citations(step.referenceIds)}</div>)}<h3>Cleanup checklist</h3><label className="explorer-check"><input type="checkbox" disabled={busy} checked={progress.cleanup} onChange={e=>updateLab({...progress,cleanup:e.target.checked})}/>Cleanup: {lab.cleanup}</label><label>Personal lab observations<textarea maxLength={4000} value={observations} onChange={e=>setObservations(e.target.value)}/></label><p>Personal notes, not verified teaching material. {observations.length}/4000 characters.</p><button disabled={busy} onClick={()=>updateLab({...progress,observations})}>Save observations</button></article>}
 </section>;
}
