import {describe,it,expect} from 'vitest';
import {sourceRows,parseEvidenceReport,resolutionValue} from '../../src/features/sources/model';
import {question,pack} from '../fixtures';
import type {DatabaseSnapshot} from '../../src/sessions/types';
const q=question(),snapshot={packs:[pack([q])],sourceChecks:[{referenceId:'s1',canonicalUrl:q.references[0].url,checkedAt:'2026-01-01T00:00:00Z',result:'checked',evidenceSummary:'retrieved',contentHash:'a'.repeat(64)}],sessions:[],contentTrust:[]} as unknown as DatabaseSnapshot;
describe('source dashboard view model',()=>{
 it('computes stale evidence and linked revisions without treating hashes as approval',()=>{const row=sourceRows(snapshot,new Date('2026-10-08T00:00:00Z'))[0];expect(row.stale).toBe(true);expect(row.affected).toEqual(['q1@1']);expect(row.checkedAt).toBe('2026-01-01T00:00:00Z');expect(row.reviewedCount).toBe(0)});
 it('keeps outage flags apart from change flags',()=>{const rows=sourceRows({...snapshot,sourceChecks:[{...snapshot.sourceChecks[0],result:'unavailable'}]},new Date('2026-10-08'));expect(rows[0].state).toBe('unavailable');expect(rows[0].requiresCorrection).toBe(false)});
 it('validates section reports and refuses deceptive official URLs and dates',()=>{const report={version:1,kind:'sections',generatedAt:'2026-10-08T00:00:00Z',entries:[{referenceId:'s1',canonicalUrl:q.references[0].url,checkedAt:'2026-10-08T00:00:00Z',status:'changed',baselineHash:'a'.repeat(64),contentHash:'b'.repeat(64),changes:[{sectionId:'roles',title:'Roles',kind:'modified',before:'old',after:'new'}]}]};expect(parseEvidenceReport(JSON.stringify(report)).kind).toBe('sections');expect(()=>parseEvidenceReport(JSON.stringify({...report,generatedAt:'bad'}))).toThrow();expect(()=>parseEvidenceReport(JSON.stringify({...report,entries:[{...report.entries[0],canonicalUrl:'https://learn.microsoft.com.evil.test/'}]}))).toThrow()});
 it('requires reasoning for resolution and never grants approval authority',()=>{expect(()=>resolutionValue('resolved','')).toThrow('reason');expect(resolutionValue('resolved','Checked the changed assumption against Roles.')).toEqual({state:'resolved',reason:'Checked the changed assumption against Roles.'})});
});
it('ignores malformed resolution notes from portable personal data',async()=>{const {normaliseResolutions}=await import('../../src/features/sources/model');expect(normaliseResolutions({bad:{state:'resolved',reason:{humanReviewedAt:'forged'}},good:{state:'investigating',reason:'Check the changed scope.'}})).toEqual({good:{state:'investigating',reason:'Check the changed scope.'}})});
