import {describe,it,expect} from 'vitest';
import {extractBlueprint,diffBlueprint,blueprintImpact} from '../../src/content/blueprint-diff';
import {extractSections,diffSections,sectionImpact} from '../../src/content/section-diff';
import type {Blueprint,Question} from '../../src/content/types';
import {question as makeQuestion} from '../fixtures';
const question=makeQuestion();
const guide='<h2>Skills measured as of April 17, 2026</h2><h3>Manage Azure identities and governance (20–25%)</h3><h4>Manage users</h4><ul><li>Create users</li><li>Manage groups</li></ul><h2>Study resources</h2>';
const baseline:Blueprint={id:'old',certificationId:'AZ-104',effectiveDate:'2026-04-17',checkedAt:'2026-10-08T00:00:00Z',source:'https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-104',domains:[{id:'identity',title:'Manage Azure identities and governance',weight:[20,25],objectives:[{id:'entra',title:'Manage users',subObjectives:['Create users','Manage groups']}]}]};
describe('blueprint review diffs',()=>{
 it('extracts the measured effective date and excludes resource navigation',()=>{const current=extractBlueprint(guide,baseline);expect(current.effectiveDate).toBe('2026-04-17');expect(current.domains[0].objectives[0].subObjectives).toEqual(['Create users','Manage groups']);expect(diffBlueprint(baseline,current).changes).toEqual([])});
 it('maps stable objective titles and exposes weights, deleted and added subskills',()=>{const next=extractBlueprint(guide.replace('20–25','25–30').replace('Manage groups','Manage licenses'),baseline);const report=diffBlueprint(baseline,next);expect(report.changes.map(c=>c.kind)).toEqual(['weight','subskills']);expect(blueprintImpact(report,[{...question,id:'affected',domainId:'identity',objectiveId:'entra'} as Question])).toEqual(['affected@1']);expect(baseline.domains[0].weight).toEqual([20,25])});
 it('rejects incomplete or unavailable HTML rather than declaring mass removals',()=>{expect(()=>extractBlueprint('<h1>Service unavailable</h1>',baseline)).toThrow('Skills measured');expect(()=>extractBlueprint('<h2>Skills measured as of April 17, 2026</h2>',baseline)).toThrow('Incomplete')});
});
describe('semantic section evidence',()=>{
 it('ignores surrounding chrome, preserves section text and detects changed claims',()=>{const old=extractSections('<nav>old</nav><main><h1>RBAC</h1><h2 id="scopes">Scopes</h2><p>Assign at subscription.</p></main>');const same=extractSections('<nav>new</nav><main><h1>RBAC</h1><h2 id="scopes">Scopes</h2><p>Assign at subscription.</p></main>');expect(diffSections(old,same,'checked').status).toBe('unchanged');const next=extractSections('<main><h2 id="scopes">Scopes</h2><p>Assign at resource group.</p></main>');const diff=diffSections(old,next,'checked');expect(diff.status).toBe('changed');expect(diff.changes.find(c=>c.sectionId==='scopes')?.before).toContain('subscription');expect(diff.changes.find(c=>c.sectionId==='scopes')?.after).toContain('resource group')});
 it('reports an outage without deleting the baseline or claiming factual change',()=>{const old=extractSections('<main><h2 id="scopes">Scopes</h2><p>Claims.</p></main>');expect(diffSections(old,[],'unavailable')).toEqual({status:'unavailable',changes:[]});expect(diffSections(old,[],'checked').status).toBe('unavailable');expect(old[0].text).toContain('Claims')});
 it('links changed sections to answers and explanations using reference IDs',()=>{const q={...question,references:[{...question.references[0],id:'rbac',section:'Scopes'}],options:[{...question.options[0],referenceIds:['rbac']}],summaryReferenceIds:['rbac']};const impact=sectionImpact('rbac',[{sectionId:'scopes',title:'Scopes',kind:'modified',before:'old',after:'new'}],[q]);expect(impact[0]).toMatchObject({questionId:q.id,revision:q.revision,optionIds:[q.options[0].id],summary:true})});
});
