import {afterEach,it,expect} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {ModuleAssessment} from '../../src/features/course/ModuleAssessment';
import type {ModuleAssessmentPack} from '../../src/features/course/assessment-types';
import {StudyDatabase} from '../../src/storage/database';
import {StudyRepository} from '../../src/storage/repository';
import {assessmentKey,initialAssessmentState} from '../../src/features/course/assessment-state';
import {exportBackup,restoreBackup} from '../../src/backup/restore';
const url='https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy';
const pack:ModuleAssessmentPack={moduleId:'storage-basics',revision:1,checkedAt:'2026-10-08T12:00:00Z',questions:Array.from({length:6},(_,index)=>({id:`question-${index+1}`,prompt:`Storage scenario ${index+1}`,lessonIds:['storage-intro'],correctOptionId:'a',options:[{id:'a',text:'Zone replication',explanation:'Replicas across availability zones meet this requirement.',sourceUrls:[url]},{id:'b',text:'Single location',explanation:'One physical location does not provide the requested zone resilience.',sourceUrls:[url]}]}))};
const databases:StudyDatabase[]=[];afterEach(async()=>{for(const db of databases.splice(0))await db.delete()});
function repository(){const db=new StudyDatabase(`assessment-${crypto.randomUUID()}`);databases.push(db);return new StudyRepository(db)}
async function view(repo:StudyRepository){const mounted=render(<ModuleAssessment pack={pack} moduleTitle="Storage basics" repository={repo} snapshot={await repo.getSnapshot()} onSaveQueued={write=>write}/>);await waitFor(()=>expect(screen.queryByText('Loading saved assessment…')).not.toBeInTheDocument());return mounted}
it('freezes checked answers and exposes supported wrong-answer feedback only after checking',async()=>{const repo=repository();await view(repo);expect(screen.getByRole('heading',{name:'Module assessment'})).toBeInTheDocument();expect(screen.getByText('Question 1 of 6')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Check answer'})).toBeDisabled();expect(screen.queryByText(pack.questions[0].options[0].explanation)).not.toBeInTheDocument();fireEvent.click(screen.getByRole('radio',{name:'Single location'}));fireEvent.click(screen.getByRole('button',{name:'Check answer'}));await screen.findByRole('heading',{name:'Incorrect'});expect(screen.getByRole('radio',{name:'Single location'})).toBeDisabled();expect(screen.getByText(pack.questions[0].options[1].explanation)).toBeInTheDocument();expect(screen.getByText(pack.questions[0].options[0].explanation)).toBeInTheDocument();expect(screen.getByRole('link',{name:'Microsoft Learn source 1'})).toHaveAttribute('href',url);await waitFor(()=>expect(screen.getByRole('button',{name:'Next question'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Next question'}));await waitFor(()=>expect(screen.getByRole('heading',{name:'Storage scenario 2'})).toHaveFocus())});
it('saved answers survive remount and workspace backup restoration',async()=>{const repo=repository(),mounted=await view(repo);fireEvent.click(screen.getByRole('radio',{name:'Zone replication'}));fireEvent.click(screen.getByRole('button',{name:'Check answer'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Next question'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Next question'}));await waitFor(async()=>expect((await repo.db.workspace.get(assessmentKey(pack.moduleId)))?.value.currentIndex).toBe(1));mounted.unmount();const snapshot=await repo.getSnapshot(),target=repository(),backup=JSON.parse(await exportBackup(snapshot).text());await restoreBackup(target,backup,{replaceConfirmed:true,recoveryBackup:exportBackup(await target.getSnapshot())});await view(target);expect(screen.getByText('Question 2 of 6')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Check answer'})).toBeDisabled();expect((await target.db.workspace.get(assessmentKey(pack.moduleId)))?.value.answers).toEqual({'question-1':{selectedOptionId:'a',submitted:true}})});
it('failed saves retain selections and offer a durable retry before continuing',async()=>{const repo=repository(),fail=()=>{throw Error('Quota exceeded')};repo.db.workspace.hook('creating',fail);await view(repo);fireEvent.click(screen.getByRole('radio',{name:'Zone replication'}));expect(await screen.findByRole('alert')).toHaveTextContent(/Retry saving/i);expect(screen.getByRole('radio',{name:'Zone replication'})).toBeChecked();expect(await repo.db.workspace.count()).toBe(0);repo.db.workspace.hook('creating').unsubscribe(fail);fireEvent.click(screen.getByRole('button',{name:'Retry saving'}));await waitFor(()=>expect(screen.queryByRole('alert')).not.toBeInTheDocument());fireEvent.click(screen.getByRole('button',{name:'Check answer'}));await screen.findByRole('heading',{name:'Correct'});await waitFor(()=>expect(screen.getByRole('button',{name:'Next question'})).toBeEnabled());expect((await repo.db.workspace.get(assessmentKey(pack.moduleId)))?.value.answers).toEqual({'question-1':{selectedOptionId:'a',submitted:true}})});
it('shows the final score and sourced review after six answers; retry retains compact previous history',async()=>{const repo=repository();await view(repo);for(let i=0;i<6;i++){fireEvent.click(screen.getByRole('radio',{name:i===0?'Single location':'Zone replication'}));fireEvent.click(screen.getByRole('button',{name:'Check answer'}));const next=screen.getByRole('button',{name:i===5?'Finish assessment':'Next question'});await waitFor(()=>expect(next).toBeEnabled());fireEvent.click(next)}await screen.findByRole('heading',{name:'Assessment complete'});expect(screen.getByText('5 / 6 correct')).toBeInTheDocument();fireEvent.click(screen.getByText('Review answers'));expect(screen.getAllByRole('link',{name:/Microsoft Learn source/})).toHaveLength(6);await waitFor(()=>expect(screen.getByRole('button',{name:'Try again'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Try again'}));expect(screen.getByText('Question 1 of 6')).toBeInTheDocument();expect(screen.getByText('Previous attempt: 5 / 6 correct')).toBeInTheDocument();await waitFor(async()=>expect((await repo.db.workspace.get(assessmentKey(pack.moduleId)))?.value.previousAttempt).toBeDefined());expect(screen.getByRole('button',{name:'Check answer'})).toBeDisabled()});
it('malformed restored completion starts a fresh assessment rather than displaying a forged score',async()=>{const repo=repository();await repo.db.workspace.put({id:assessmentKey(pack.moduleId),version:1,updatedAt:new Date().toISOString(),value:{...initialAssessmentState(pack),currentIndex:6,score:6}});await view(repo);expect(screen.getByText('Question 1 of 6')).toBeInTheDocument();expect(screen.queryByRole('heading',{name:'Assessment complete'})).not.toBeInTheDocument()});
it('reopening with the same stale snapshot reads authoritative saved progress before permitting edits',async()=>{const repo=repository(),staleSnapshot=await repo.getSnapshot();const first=render(<ModuleAssessment pack={pack} moduleTitle="Storage basics" repository={repo} snapshot={staleSnapshot} onSaveQueued={write=>write}/>);await screen.findByRole('radio',{name:'Zone replication'});fireEvent.click(screen.getByRole('radio',{name:'Zone replication'}));fireEvent.click(screen.getByRole('button',{name:'Check answer'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Next question'})).toBeEnabled());first.unmount();render(<ModuleAssessment pack={pack} moduleTitle="Storage basics" repository={repo} snapshot={staleSnapshot} onSaveQueued={write=>write}/>);expect(screen.queryByRole('radio')).not.toBeInTheDocument();await screen.findByRole('heading',{name:'Correct'});expect(screen.getByRole('radio',{name:'Zone replication'})).toBeChecked();expect(screen.getByRole('radio',{name:'Zone replication'})).toBeDisabled();expect(screen.queryByRole('button',{name:'Check answer'})).not.toBeInTheDocument()});
it('failed authoritative reads block answers and retry loading without overwriting progress',async()=>{const repo=repository(),state=initialAssessmentState(pack);state.answers={'question-1':{selectedOptionId:'b',submitted:true}};await repo.db.workspace.put({id:assessmentKey(pack.moduleId),version:1,updatedAt:new Date().toISOString(),value:{...state}});const snapshot=await repo.getSnapshot(),fail=()=>{throw Error('Database read unavailable')};repo.db.workspace.hook('reading',fail);render(<ModuleAssessment pack={pack} moduleTitle="Storage basics" repository={repo} snapshot={snapshot} onSaveQueued={write=>write}/>);expect(await screen.findByRole('alert')).toHaveTextContent(/Retry loading/);expect(screen.queryByRole('radio')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Check answer'})).not.toBeInTheDocument();repo.db.workspace.hook('reading').unsubscribe(fail);fireEvent.click(screen.getByRole('button',{name:'Retry loading'}));await screen.findByRole('heading',{name:'Incorrect'});expect(screen.getByRole('radio',{name:'Single location'})).toBeChecked();expect((await repo.db.workspace.get(assessmentKey(pack.moduleId)))?.value).toEqual(state)});
it('rapid selection changes and checking serialize complete writes to retain the latest frozen answer',async()=>{const repo=repository(),writes:Promise<void>[]=[];render(<ModuleAssessment pack={pack} moduleTitle="Storage basics" repository={repo} snapshot={await repo.getSnapshot()} onSaveQueued={write=>{writes.push(write);return write}}/>);await screen.findByRole('radio',{name:'Zone replication'});fireEvent.click(screen.getByRole('radio',{name:'Zone replication'}));fireEvent.click(screen.getByRole('radio',{name:'Single location'}));fireEvent.click(screen.getByRole('radio',{name:'Zone replication'}));fireEvent.click(screen.getByRole('button',{name:'Check answer'}));expect(screen.getByRole('radio',{name:'Zone replication'})).toBeDisabled();await waitFor(()=>expect(screen.getByRole('button',{name:'Next question'})).toBeEnabled());await Promise.all(writes);expect((await repo.db.workspace.get(assessmentKey(pack.moduleId)))?.value.answers).toEqual({'question-1':{selectedOptionId:'a',submitted:true}})});
