import type {Question} from '../content/types';
import {classifyQuestion} from '../content/trust';
import type {Attempt,DatabaseSnapshot,Session} from '../sessions/types';
import {isAssessmentSession,isTimedSession} from '../sessions/types';
import legacyMappings from '../../content/coverage/legacy-subskills.json';
import blueprint from '../../content/blueprints/az104-2026-04-17.json';
import {allocations} from './selection';
function mappedSubskills(q:Question):string[]{return q.subObjectiveIds??(legacyMappings as Record<string,string[]>)[`${q.id}@${q.revision}`]??[]}
export interface AnalyticsRange {from?:string;to?:string;now?:Date}
export function currentApprovedQuestions(snapshot:DatabaseSnapshot):Question[]{
 const latest=new Map<string,Question>();for(const q of snapshot.packs.flatMap(p=>p.questions)){if(!latest.has(q.id)||latest.get(q.id)!.revision<q.revision)latest.set(q.id,q)}
 return [...latest.values()].filter(q=>classifyQuestion(q,snapshot.contentTrust.find(t=>t.questionId===q.id&&t.revision===q.revision)??null)==='eligible');
}
export function currentScoredAttempts(snapshot:DatabaseSnapshot):Attempt[]{const current=new Map(currentApprovedQuestions(snapshot).map(q=>[q.id,q.revision]));return snapshot.attempts.filter(a=>a.mode!=='draft-preview'&&current.get(a.questionId)===a.questionRevision&&Number.isFinite(Date.parse(a.submittedAt))).sort((a,b)=>Date.parse(a.submittedAt)-Date.parse(b.submittedAt)||a.id.localeCompare(b.id))}
function inRange(date:string,range:AnalyticsRange){const value=Date.parse(date),from=range.from?Date.parse(range.from):-Infinity,to=range.to?Date.parse(range.to)+(range.to.length===10?86400000-1:0):Infinity;return value>=from&&value<=to}
function metric(data:Attempt[]){return {count:data.length,accuracy:data.length?data.filter(a=>a.correct).length/data.length:null}}
function median(values:number[]):number|null{if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b),middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:(sorted[middle-1]+sorted[middle])/2}
export function deriveAnalytics(snapshot:DatabaseSnapshot,range:AnalyticsRange={}){
 const questions=currentApprovedQuestions(snapshot),all=currentScoredAttempts(snapshot),valid=all.filter(a=>inRange(a.submittedAt,range)),firstIds=new Set<string>(),firstAttempts=new Set<string>();
 for(const a of all)if(!firstIds.has(a.questionId)){firstIds.add(a.questionId);firstAttempts.add(a.id)}
 const latest=[...new Map(valid.map(a=>[a.questionId,a])).values()];
 const exposure=snapshot.packs.flatMap(p=>p.questions).filter((q,i,list)=>list.findIndex(x=>x.id===q.id)===i).map(q=>{const seen=snapshot.attempts.filter(a=>a.questionId===q.id).sort((a,b)=>Date.parse(a.submittedAt)-Date.parse(b.submittedAt));return {questionId:q.id,seenCount:seen.length,firstSeenAt:seen[0]?.submittedAt??null,lastSeenAt:seen.at(-1)?.submittedAt??null,approved:questions.some(x=>x.id===q.id)}});
 const confidence=Object.fromEntries((['confident','unsure','guessed','unknown'] as const).map(level=>{const data=valid.filter(a=>a.confidence===level);return [level,{...metric(data),wrong:data.filter(a=>!a.correct).length}]}));
 const latency=[...new Set(questions.map(q=>q.domainId+'|'+q.difficulty+'|'+q.type))].map(key=>{const [domainId,difficulty,format]=key.split('|'),data=valid.filter(a=>{const q=questions.find(q=>q.id===a.questionId)!;return q.domainId===domainId&&q.difficulty===difficulty&&q.type===format&&Number.isFinite(a.responseMs)&&a.responseMs>0});return {domainId,difficulty,format,count:data.length,medianMs:median(data.map(a=>a.responseMs))}}).filter(x=>x.count);
 const mistakes=valid.filter(a=>!a.correct).reverse().map(a=>{const q=questions.find(q=>q.id===a.questionId)!;return {attemptId:a.id,questionId:q.id,revision:q.revision,prompt:q.prompt,domainId:q.domainId,objectiveId:q.objectiveId,confidence:a.confidence,submittedAt:a.submittedAt,selectedOptionIds:a.selectedOptionIds,practiceHref:`#/practice?question=${encodeURIComponent(q.id)}`}});
 const subskills=questions.flatMap(mappedSubskills).filter((id,i,list)=>list.indexOf(id)===i).map(id=>{const pool=questions.filter(q=>mappedSubskills(q).includes(id)),data=latest.filter(a=>pool.some(q=>q.id===a.questionId));return {id,available:pool.length,advancedAvailable:pool.filter(q=>q.difficulty==='advanced').length,studied:data.length,...metric(data),practiceHref:`#/practice?subskill=${encodeURIComponent(id)}`}});
 const days=[...new Set(valid.map(a=>a.submittedAt.slice(0,10)))].sort().map(date=>{const answers=valid.filter(a=>a.submittedAt.startsWith(date)),confident=answers.filter(a=>a.confidence==='confident'),confidentWrong=confident.filter(a=>!a.correct).length;return {date,...metric(answers),confidentWrong,confidentAnswers:confident.length,confidentWrongRate:answers.length?confidentWrong/answers.length:null}});
 return {exposure,first:metric(valid.filter(a=>firstAttempts.has(a.id))),repeat:metric(valid.filter(a=>!firstAttempts.has(a.id))),latest:metric(latest),confidence,latency,mistakes,subskills,days,excludedAttempts:snapshot.attempts.length-all.length,eligibleCount:questions.length,distinctStudied:latest.length};
}
export function reserveSummary(snapshot:DatabaseSnapshot){const current=new Map<string,Question>();for(const q of snapshot.packs.flatMap(p=>p.questions))if(!current.has(q.id)||current.get(q.id)!.revision<q.revision)current.set(q.id,q);const reserved=[...current.values()].filter(q=>q.assessmentReserved&&q.status!=='retired'),approved=currentApprovedQuestions(snapshot),seen=new Set(snapshot.attempts.map(a=>a.questionId)),released=new Set(snapshot.releasedHoldouts.map(r=>r.questionId));return {installed:reserved.length,approved:reserved.filter(q=>approved.some(a=>a.id===q.id)).length,unseen:reserved.filter(q=>!seen.has(q.id)).length,unreleased:reserved.filter(q=>!released.has(q.id)).length,events:snapshot.releasedHoldouts.map(event=>({questionId:event.questionId,releasedAt:('releasedAt' in event&&typeof event.releasedAt==='string')?event.releasedAt:null,sessionId:('sessionId' in event&&typeof event.sessionId==='string')?event.sessionId:null}))}}
function counts(values:string[]){return Object.fromEntries([...new Set(values)].sort().map(value=>[value,values.filter(x=>x===value).length]))}
export function assessmentDistribution(session:Session){const domains=blueprint.domains,weights=domains.map(d=>(d.weight[0]+d.weight[1])/2),total=weights.reduce((a,b)=>a+b,0),planned=allocations(session.questionSnapshots.length,weights.map(w=>w/total));return {domains:domains.map((d,i)=>({id:d.id,title:d.title,publishedRange:d.weight,planned:planned[i],actual:session.questionSnapshots.filter(q=>q.domainId===d.id).length})),objectives:counts(session.questionSnapshots.map(q=>q.objectiveId)),difficulty:counts(session.questionSnapshots.map(q=>q.difficulty)),formats:Object.fromEntries(['single','multiple','ordering','matching'].map(type=>[type,session.questionSnapshots.filter(q=>q.type===type).length]))}}
function configuration(session:Session){const distribution=assessmentDistribution(session);return JSON.stringify({timed:isTimedSession(session),duration:session.deadlineAt?Math.round((Date.parse(session.deadlineAt)-Date.parse(session.startedAt))/60000):null,count:session.questionSnapshots.length,domains:distribution.domains.map(d=>[d.id,d.actual]),objectives:distribution.objectives,difficulty:distribution.difficulty,formats:distribution.formats,cases:session.questionSnapshots.filter(q=>q.caseStudy).length})}
export function compareAssessments(snapshot:DatabaseSnapshot,range:AnalyticsRange={}){const eligible=currentApprovedQuestions(snapshot),attempts=currentScoredAttempts(snapshot),groups=new Map<string,Session[]>();for(const s of snapshot.sessions){if(s.status!=='submitted'||s.mode==='draft-preview'||!isAssessmentSession(s)||!s.result||!s.submittedAt||!inRange(s.submittedAt,range)||!s.questionSnapshots.every(q=>eligible.some(current=>q.id===current.id&&q.revision===current.revision))||s.questionSnapshots.some(q=>!attempts.some(a=>a.sessionId===s.id&&a.questionId===q.id)))continue;const key=configuration(s);groups.set(key,[...(groups.get(key)??[]),s])}return [...groups.entries()].filter(([,sessions])=>sessions.length>1).map(([configuration,sessions])=>({configuration,sessions:sessions.sort((a,b)=>Date.parse(a.submittedAt!)-Date.parse(b.submittedAt!)),scores:sessions.map(s=>({sessionId:s.id,...metric(attempts.filter(a=>a.sessionId===s.id))}))}))}
export function assessmentDepthGaps(snapshot:DatabaseSnapshot){const approved=currentApprovedQuestions(snapshot);return blueprint.domains.flatMap(d=>d.objectives.flatMap(o=>o.subObjectives.map((title,index)=>{const id=`${o.id}.${index+1}`,questions=approved.filter(q=>q.objectiveId===o.id&&mappedSubskills(q).includes(id));return {id,title,objectiveId:o.id,available:questions.length,advanced:questions.filter(q=>q.difficulty==='advanced').length,practiceHref:`#/practice?subskill=${encodeURIComponent(id)}`}}))).filter(g=>g.advanced<2)}
